
# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: br-ms-atencao-basica

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Cobertura da Atenção Básica

# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Exemplos: br-ibge, br-tse, br-rj-gov
organization:
    - br-ms

# Descrição do conjunto
notes: Cobertura populacional estimada de equipes de saúde da família (eSF) e de equipes
    de Atenção Básica (eAB) utilizada para o monitoramento do acesso aos serviços
    de Atenção Básica, com vistas ao fortalecimento do planejamento do Sistema Único
    de Saúde (SUS).

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
    - saude

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos: fertilidade, preco, desmatamento.
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
    - atencao basica
    - municipio
    - sus

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified: 
