
# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: world-gsps-consortium-gsps

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: The Global Survey of Public Servants Global Indicator Data Set


# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Exemplos: br-ibge, br-tse, br-rj-gov
organization: world-gsps-consortium

# Descrição do conjunto
notes: The Global Survey of Public Servants Consortium has collected surveys of public servants across the world.  To maximize their usefulness to the global community while ensuring confidentiality of responses, we have released a twenty-one-country dataset that averages responses at the institution-level (the GSPS `Global Indicator Data Set').  

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups: 
  - gov-fin-pub

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos: fertilidade, preco, desmatamento.
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
  - administracao publica
  - servidor
  - salario
  - burocracia
  - cargo comissionado
  - politica publica
  - financa publicas
  - governo
  - instituicoes

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified:
