# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: br-inpe-prodes

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Desmatamento PRODES

# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Exemplos: br-ibge, br-tse, br-rj-gov
organization:
    - br-inpe

# Descrição do conjunto
notes: "O projeto PRODES realiza o monitoramento por satélites do desmatamento por\
    \ corte raso na Amazônia Legal e produz, desde 1988, as taxas anuais de desmatamento\
    \ na região, que são usadas pelo governo brasileiro para o estabelecimento de\
    \ políticas públicas. As taxas anuais são estimadas a partir dos incrementos de\
    \ desmatamento identificados em cada imagem de satélite que cobre a Amazônia Legal.\
    \ A primeira apresentação dos dados é realizada para dezembro de cada ano, na\
    \ forma de estimativa. Os dados consolidados são apresentados no primeiro semestre\
    \ do ano seguinte.\r\n\r\nO PRODES utiliza imagens de satélites da classe LANDSAT\
    \ (20 a 30 metros de resolução espacial e taxa de revisita de 16 dias) numa combinação\
    \ que busca minimizar o problema da cobertura de nuvens e garantir critérios de\
    \ interoperabilidade. As imagens do satélite americano LANDSAT-5/TM foram, historicamente,\
    \ as mais utilizadas pelo projeto, mas as imagens do sensor CCD a bordo do CBERS-2/2B,\
    \ satélites do programa sino-brasileiro de sensoriamento remoto, foram bastante\
    \ usadas. O PRODES também fez uso de imagens LISS-3 do satélite indiano IRS-1\
    \ e também das imagens do satélite inglês UK-DMC2. Atualmente faz uso massivo\
    \ das imagens do LANDSAT 8/OLI, CBERS 4 e IRS-2. Independente do instrumento utilizado,\
    \ a área mínima mapeada pelo PRODES é de 6,25 hectares.\r\n\r\nAs estimativas\
    \ do PRODES são consideradas confiáveis pelos cientistas nacionais e internacionais\
    \ (Kintish, 2007). Esse sistema tem demonstrado ser de grande importância para\
    \ ações e planejamento de políticas públicas da Amazônia. Resultados recentes,\
    \ a partir de análises realizadas com especialistas independentes, indicam nível\
    \ de precisão próximo a 95%."

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
    - meio-ambiente

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos: fertilidade, preco, desmatamento.
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
    - conservacao
    - desmatamento
    - mudancas climaticas
    - uso da terra

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified: '2022-06-08T17:59:23.824842'
