# Igual ao dataset.name mas como lower case.
# Exemplos: br_ibge_populacao, br_inep_censo_escolar
dataset_id: br_ibge_pof

table_id: caracteristicas_dieta_2017

# Título da tabela.
title: Características da Dieta

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description: Microdados do Registro de Características da Dieta da Pesquisa de Orçamentos Familiares.

# As máximas unidades espaciais que a tabela cobre.
# Exemplo:
#   - sa.br
spatial_coverage:
    - sa.br

# Anos cobertos pela tabela.
# Preencher como lista de intervalos.
# Exemplos: ['1995(1)2019'], ['2002(2)2010', '2016', '2020'].
temporal_coverage:
    - 2017(1)2018

# A unidade temporal com qual a tabela é atualizada.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
update_frequency:
    - ten_years

# Nível de observação da tabela: o que representa cada linha.
observation_level: 

last_updated:
    metadata: '2022-10-19'
    data: '2022-05-19 12:00:00'
    release:

# Versão da tabela. Seguindo o padrão de semantic versioning.
# Exemplo: v1.1.3
version: v1.0

# Quem está preenchendo esses metadados?
published_by: 
    name: Arthur de Figueiredo Gusmão
    email: arthur.gusmao@basedosdados.org
    github_user: arthurfg
    ckan_user: arthurfg
    website: 

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by: 
    name: Arthur de Figueiredo Gusmão
    email: arthur.gusmao@basedosdados.org
    github_user: arthurfg
    ckan_user: arthurfg
    website:

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: |
    Renomeação e ordenamento das variáveis, criação de identificadores de Unidade de Consumo, Domicilio e Informante, padronização do código dos produtos para os 5 dígitos.

# Url do código de limpeza dos dados.
data_cleaning_code_url: https://github.com/basedosdados/mais/tree/master/bases/br_ibge_pof/code

# Organização que ajudou institucionalmente na disponibilização dos dados.
partner_organization:
    name:
    organization_id:

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions:
    - sigla_uf

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Algumas colunas existirão apenas na tabela final, você as construirá em `publish.sql`.
# Para esses, defina is_in_staging como False.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: sigla_uf
      bigquery_type: string
      description: Sigla da Unidade da Federação
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: uf
          column_name: sigla
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: true
    - name: situacao
      bigquery_type: string
      description: 'Situação do Domicílio '
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: id_estrato
      bigquery_type: string
      description: Identificador dos estratos do plano amostral da pesquisa
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: id_unidade_primaria_amostragem
      bigquery_type: string
      description: Código da Unidade Primária de Amostragem
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: id_domicilio
      bigquery_type: string
      description: Identificador do Domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: id_unidade_consumo
      bigquery_type: string
      description: Identificador da Unidade de Consumo
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: id_informante
      bigquery_type: string
      description: Identificador do informante
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V7101
      bigquery_type: string
      description: Identifica se o informante utiliza tais produtos com frequência
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V7102
      bigquery_type: string
      description: Identifica se o informante tem o hábito de adicionar sal ao prato
          de comida
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V71031
      bigquery_type: string
      description: Identifica se o informante utilizou nos últimos 30 dias multivitaminas/complexo
          multivitaminico
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V71032
      bigquery_type: string
      description: Identifica se o informante utilizou nos últimos 30 dias, ferro,
          sulfato ferroso
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V71033
      bigquery_type: string
      description: Identifica se o informante utilizou nos últimos 30 dias vitaminas
          do complexo B
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V71034
      bigquery_type: string
      description: Identifica se o informante utilizou nos últimos 30 dias vitamina
          C
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V71035
      bigquery_type: string
      description: Identifica se o informante utilizou nos últimos 30 dias ômega 3,
          óleo de peixe
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V71036
      bigquery_type: string
      description: Identifica se o informante utilizou nos últimos 30 dias cálcio,
          cálcio com vitamina
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V71037
      bigquery_type: string
      description: Identifica se o informante utilizou nos últimos 30 dias proteína,
          creatina, outro suplemento para atleta
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V71038
      bigquery_type: string
      description: Identifica se o informante utilizou nos últimos 30 dias outros
          suplementos
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V7104
      bigquery_type: string
      description: Identifica se o informante fez alguma dieta
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V71051
      bigquery_type: string
      description: Identifica se a dieta foi para emagrecer
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V71052
      bigquery_type: string
      description: Identifica se a dieta foi para pressão alta
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V71053
      bigquery_type: string
      description: Identifica se a dieta foi para colesterol
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V71054
      bigquery_type: string
      description: Identifica se a dieta foi para diabetes
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V71055
      bigquery_type: string
      description: Identifica se a dieta foi para doença no coração
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V71056
      bigquery_type: string
      description: Identifica se a dieta foi para outra necessidade
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V71A01
      bigquery_type: string
      description: Identifica se a informante está grávida
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V71A02
      bigquery_type: string
      description: Identifica se a informante está amamentando
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V72C01
      bigquery_type: int64
      description: Peso em Kg do informante
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: kilogram
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: V72C02
      bigquery_type: int64
      description: Altura em Cm do informante
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: centimeter
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: peso
      bigquery_type: float64
      description: Fator de expansão atribuído ao domicílio pertencente a uma Unidade
          Primária de Amostragem
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:
    - name: peso_final
      bigquery_type: float64
      description: Fator de expansão (peso) ajustado às estimativas populacionais
          de 15 de janeiro de 2018, segundo cada Unidade da Federação e pós estratos
          definidos
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition:

number_rows:

metadata_modified:
