#!/bin/bash

echo ------------------------------------------------------
echo Sort
echo ------------------------------------------------------

python -m isort --check-only --profile black .github python-package

echo ------------------------------------------------------
echo Format
echo ------------------------------------------------------

python -m black --check .github python-package

echo ------------------------------------------------------
echo Lint
echo ------------------------------------------------------

python -m pylint --exit-zero .github/**/*.py python-package

echo ------------------------------------------------------
echo Test
echo ------------------------------------------------------

python -m pytest python-package/tests

echo ------------------------------------------------------
echo Commit
echo ------------------------------------------------------
