#!/bin/bash

echo ------------------------------------------------------
echo Sort
echo ------------------------------------------------------

python -m isort --check-only --profile black .github
python -m isort --check-only --profile black python-package

echo ------------------------------------------------------
echo Format
echo ------------------------------------------------------

python -m black --check .github
python -m black --check python-package

echo ------------------------------------------------------
echo Lint
echo ------------------------------------------------------

python -m pylint --exit-zero .github/**/*.py
python -m pylint --exit-zero python-package

echo ------------------------------------------------------
echo Commit
echo ------------------------------------------------------
