# -*- coding: utf-8 -*-
"""country.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NTy4zsq_6ce9xDC1SXIEHiUHVFy9UDG6
"""

import pandas as pd
import numpy as np

#Reading the Local File
x = pd.read_csv('country.txt', sep='\t', dtype=str)

# Organization for future sort
x['year'] = x['year'].astype(int)
x['rank'] = x['rank'].fillna(0).astype(int)
x['rank'] = x['rank'].replace(0, "")
x['number_sources'] = x['number_sources'].fillna(0).astype(int)
x['number_sources'] = x['number_sources'].replace(0, "")

#Rename of columns
x = x.rename({'IMD World Competitiveness Yearbook': 'world_competitiveness_yearbook'},
             axis = 'columns')

#Initialize the Merge
y=x.query('year==2012')

c = x.query('year==2021')[['country_id_iso_3', 'country']]

#Merge from country 
x = pd.merge(x, c, how = 'left', on='country')

#Rename of column
x = x.rename({'country_id_iso_3_y': 'country_id_iso_3'},
             axis = 'columns')

#Select Columns
x = x[['year',
       'country_id_iso_3',
       'country',
       'corruption_index_score',
       'rank',
       'standard_error',
       'number_sources',
       'lower_ci',
       'upper_ci',
       'african_development_bank',
       'bertelsmann_foundation_sustainable_index',
       'bertelsmann_foundation_transformation_index',
       'economist_intelligence_ratings',
       'freedom_house_nations_transit',
       'global_insight_country_risk_ratings',
       'world_competitiveness_yearbook',
       'asia_risk_guide_perc',
       'international_contry_risk_guide',
       'varieties_democracy_project',
       'world_bank_country_policy_institutional_assessment',
       'world_economic_forum',
       'world_justice_project_rule_law_index']]

#Sort of year and Rank
x.sort_values(by=['year', 'rank'])

# Save to csv in Base dos Dados Standard
x.to_csv('country.csv', sep=',', index=False, header=True)