pull_request_rules:
  - name: Automatic update for PRs
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
    actions:
      update:
  - name: Warn author on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} esse pull request tem conflitos 😩"
      label:
        add:
          - conflict