repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  # - id: check-yaml
  - id: detect-private-key
  # - id: end-of-file-fixer
  # - id: no-commit-to-branch
  #   args: [-b, main]
  # - id: trailing-whitespace
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
    args:
    - "--rcfile=.pylintrc"
    exclude: .github/
# - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
#   rev: v2.3.0
#   hooks:
#   - id: pretty-format-yaml
#     args: [--autofix, --indent, '2']
