version: '3'

services:
  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/src/docs
    command: mkdocs serve --dev-addr=0.0.0.0:8000
