/*

Query para publicar a tabela.

Esse é o lugar para:
    - modificar nomes, ordem e tipos de colunas
    - dar join com outras tabelas
    - criar colunas extras (e.g. logs, proporções, etc.)

Qualquer coluna definida aqui deve também existir em `table_config.yaml`.

# Além disso, sinta-se à vontade para alterar alguns nomes obscuros
# para algo um pouco mais explícito.

TIPOS:
    - Para modificar tipos de colunas, basta substituir STRING por outro tipo válido.
    - Exemplo: `SAFE_CAST(column_name AS NUMERIC) column_name`
    - Mais detalhes: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types

*/

CREATE VIEW basedosdados.br_ms_srag2020.microdados AS
SELECT 
SAFE_CAST(data_notificacao AS DATE) data_notificacao,
SAFE_CAST(semana_notificacao AS INT64) semana_notificacao,
SAFE_CAST(data_primeiros_sintomas AS DATE) data_primeiros_sintomas,
SAFE_CAST(semana_primeiros_sintomas AS INT64) semana_primeiros_sintomas,
SAFE_CAST(sigla_uf_notificacao AS STRING) sigla_uf_notificacao,
SAFE_CAST(regiao_saude_notificacao AS STRING) regiao_saude_notificacao,
SAFE_CAST(id_regiao_saude_notificacao AS INT64) id_regiao_saude_notificacao,
SAFE_CAST(municipio_notificacao AS STRING) municipio_notificacao,
SAFE_CAST(id_municipio_notificacao AS INT64) id_municipio_notificacao,
SAFE_CAST(id_municipio_6_notificacao AS INT64) id_municipio_6_notificacao,
SAFE_CAST(unidade_notificacao AS STRING) unidade_notificacao,
SAFE_CAST(id_unidade_notificacao AS INT64) id_unidade_notificacao,
SAFE_CAST(sexo AS INT64) sexo,
SAFE_CAST(data_nascimento AS DATE) data_nascimento,
SAFE_CAST(idade AS INT64) idade,
SAFE_CAST(tipo_idade AS INT64) tipo_idade,
SAFE_CAST(id_idade AS INT64) id_idade,
SAFE_CAST(id_gestante AS INT64) id_gestante,
SAFE_CAST(id_raca AS INT64) id_raca,
SAFE_CAST(id_etnia AS INT64) id_etnia,
SAFE_CAST(id_escolaridade AS INT64) id_escolaridade,
SAFE_CAST(pais AS STRING) pais,
SAFE_CAST(id_pais AS INT64) id_pais,
SAFE_CAST(sigla_uf_residencia AS STRING) sigla_uf_residencia,
SAFE_CAST(regiao_saude_residencia AS STRING) regiao_saude_residencia,
SAFE_CAST(id_regiao_saude_residencia AS INT64) id_regiao_saude_residencia,
SAFE_CAST(municipio_residencia AS STRING) municipio_residencia,
SAFE_CAST(id_municipio_residencia AS INT64) id_municipio_residencia,
SAFE_CAST(id_municipio_6_residencia AS INT64) id_municipio_6_residencia,
SAFE_CAST(zona_residencia AS INT64) zona_residencia,
SAFE_CAST(surto_sg AS INT64) surto_sg,
SAFE_CAST(nosocomial AS INT64) nosocomial,
SAFE_CAST(ave_suino AS INT64) ave_suino,
SAFE_CAST(febre AS INT64) febre,
SAFE_CAST(tosse AS INT64) tosse,
SAFE_CAST(garganta AS INT64) garganta,
SAFE_CAST(dispneia AS INT64) dispneia,
SAFE_CAST(desconforto_respiratorio AS INT64) desconforto_respiratorio,
SAFE_CAST(saturacao AS INT64) saturacao,
SAFE_CAST(diarreia AS INT64) diarreia,
SAFE_CAST(vomito AS INT64) vomito,
SAFE_CAST(outros_sintomas AS INT64) outros_sintomas,
SAFE_CAST(descricao_outros_sintomas AS STRING) descricao_outros_sintomas,
SAFE_CAST(puerpera AS INT64) puerpera,
SAFE_CAST(fator_risco AS STRING) fator_risco,
SAFE_CAST(cardiopatica AS INT64) cardiopatica,
SAFE_CAST(hematologica AS INT64) hematologica,
SAFE_CAST(sindrome_down AS INT64) sindrome_down,
SAFE_CAST(hepatica AS INT64) hepatica,
SAFE_CAST(asma AS INT64) asma,
SAFE_CAST(diabetes AS INT64) diabetes,
SAFE_CAST(neurologica AS INT64) neurologica,
SAFE_CAST(pneumopatia AS INT64) pneumopatia,
SAFE_CAST(imunodepressiva AS INT64) imunodepressiva,
SAFE_CAST(renal AS INT64) renal,
SAFE_CAST(obesidade AS INT64) obesidade,
SAFE_CAST(valor_imc AS FLOAT64) valor_imc,
SAFE_CAST(outras_morbidades AS INT64) outras_morbidades,
SAFE_CAST(descricao_outras_morbidades AS STRING) descricao_outras_morbidades,
SAFE_CAST(vacina AS INT64) vacina,
SAFE_CAST(data_ultima_dose AS DATE) data_ultima_dose,
SAFE_CAST(mae_vacinada AS INT64) mae_vacinada,
SAFE_CAST(data_mae_vacinada AS DATE) data_mae_vacinada,
SAFE_CAST(mae_amamenta AS INT64) mae_amamenta,
SAFE_CAST(data_dose_unica AS DATE) data_dose_unica,
SAFE_CAST(data_primeira_dose AS DATE) data_primeira_dose,
SAFE_CAST(data_segunda_dose AS DATE) data_segunda_dose,
SAFE_CAST(antiviral AS INT64) antiviral,
SAFE_CAST(tipo_antiviral AS INT64) tipo_antiviral,
SAFE_CAST(outro_antiviral AS STRING) outro_antiviral,
SAFE_CAST(data_antiviral AS DATE) data_antiviral,
SAFE_CAST(internacao AS INT64) internacao,
SAFE_CAST(data_internacao AS DATE) data_internacao,
SAFE_CAST(sigla_uf_internacao AS STRING) sigla_uf_internacao,
SAFE_CAST(regiao_saude_internacao AS STRING) regiao_saude_internacao,
SAFE_CAST(id_regiao_saude_internacao AS INT64) id_regiao_saude_internacao,
SAFE_CAST(municipio_internacao AS STRING) municipio_internacao,
SAFE_CAST(id_municipio_internacao AS INT64) id_municipio_internacao,
SAFE_CAST(id_municipio_6_internacao AS INT64) id_municipio_6_internacao,
SAFE_CAST(uti AS INT64) uti,
SAFE_CAST(data_entrada_uti AS DATE) data_entrada_uti,
SAFE_CAST(data_saida_uti AS DATE) data_saida_uti,
SAFE_CAST(suporte_ventilatorio AS INT64) suporte_ventilatorio,
SAFE_CAST(resultado_raio_x AS INT64) resultado_raio_x,
SAFE_CAST(resultado_raio_x_outro AS STRING) resultado_raio_x_outro,
SAFE_CAST(data_raio_x AS DATE) data_raio_x,
SAFE_CAST(amostra_coletada AS INT64) amostra_coletada,
SAFE_CAST(data_amostra_coletada AS DATE) data_amostra_coletada,
SAFE_CAST(tipo_amostra_coletada AS INT64) tipo_amostra_coletada,
SAFE_CAST(tipo_amostra_outra AS STRING) tipo_amostra_outra,
SAFE_CAST(resultado_pcr AS INT64) resultado_pcr,
SAFE_CAST(data_pcr AS DATE) data_pcr,
SAFE_CAST(pcr_positivo_influenza AS INT64) pcr_positivo_influenza,
SAFE_CAST(pcr_tipo_influenza AS INT64) pcr_tipo_influenza,
SAFE_CAST(pcr_influenza_a_subtipo AS INT64) pcr_influenza_a_subtipo,
SAFE_CAST(pcr_influenza_a_subtipo_outro AS STRING) pcr_influenza_a_subtipo_outro,
SAFE_CAST(pcr_influenza_b_linhagem AS INT64) pcr_influenza_b_linhagem,
SAFE_CAST(pcr_influenza_b_linhagem_outro AS STRING) pcr_influenza_b_linhagem_outro,
SAFE_CAST(pcr_positivo_outros_virus AS INT64) pcr_positivo_outros_virus,
SAFE_CAST(pcr_vsr AS INT64) pcr_vsr,
SAFE_CAST(pcr_sars2 AS INT64) pcr_sars2,
SAFE_CAST(pcr_para_1 AS INT64) pcr_para_1,
SAFE_CAST(pcr_para_2 AS INT64) pcr_para_2,
SAFE_CAST(pcr_para_3 AS INT64) pcr_para_3,
SAFE_CAST(pcr_para_4 AS INT64) pcr_para_4,
SAFE_CAST(pcr_adeno AS INT64) pcr_adeno,
SAFE_CAST(pcr_metap AS INT64) pcr_metap,
SAFE_CAST(pcr_boca AS INT64) pcr_boca,
SAFE_CAST(pcr_rino AS INT64) pcr_rino,
SAFE_CAST(pcr_outro AS INT64) pcr_outro,
SAFE_CAST(descricao_pcr_outro AS STRING) descricao_pcr_outro,
SAFE_CAST(classificacao_final AS INT64) classificacao_final,
SAFE_CAST(classificacao_final_outro AS STRING) classificacao_final_outro,
SAFE_CAST(criterio AS INT64) criterio,
SAFE_CAST(evolucao AS INT64) evolucao,
SAFE_CAST(data_evolucao AS DATE) data_evolucao,
SAFE_CAST(data_encerramento AS DATE) data_encerramento,
SAFE_CAST(data_digitacao AS DATE) data_digitacao,
SAFE_CAST(historico_viagem AS INT64) historico_viagem,
SAFE_CAST(pais_viagem AS STRING) pais_viagem,
SAFE_CAST(id_pais_viagem AS INT64) id_pais_viagem,
SAFE_CAST(local_pais_viagem AS STRING) local_pais_viagem,
SAFE_CAST(data_viagem AS DATE) data_viagem,
SAFE_CAST(data_retorno_viagem AS DATE) data_retorno_viagem,
SAFE_CAST(cbo_2002_paciente AS STRING) cbo_2002_paciente,
SAFE_CAST(cbo_2002_mae AS STRING) cbo_2002_mae,
SAFE_CAST(contato_outro_animal AS STRING) contato_outro_animal,
SAFE_CAST(dor_abdominal AS INT64) dor_abdominal,
SAFE_CAST(fadiga AS INT64) fadiga,
SAFE_CAST(perda_olfato AS INT64) perda_olfato,
SAFE_CAST(perda_paladar AS INT64) perda_paladar,
SAFE_CAST(resultado_tomografia AS INT64) resultado_tomografia,
SAFE_CAST(resultado_tomografia_outro AS STRING) resultado_tomografia_outro,
SAFE_CAST(data_tomografia AS DATE) data_tomografia,
SAFE_CAST(tipo_teste_an AS INT64) tipo_teste_an,
SAFE_CAST(data_teste_an AS DATE) data_teste_an,
SAFE_CAST(resultado_teste_an AS INT64) resultado_teste_an,
SAFE_CAST(teste_an_positivo_influenza AS INT64) teste_an_positivo_influenza,
SAFE_CAST(teste_an_tipo_influenza AS INT64) teste_an_tipo_influenza,
SAFE_CAST(teste_an_positivo_outro AS INT64) teste_an_positivo_outro,
SAFE_CAST(resultado_teste_an_sars2 AS INT64) resultado_teste_an_sars2,
SAFE_CAST(resultado_teste_an_vsr AS INT64) resultado_teste_an_vsr,
SAFE_CAST(resultado_teste_an_para_1 AS INT64) resultado_teste_an_para_1,
SAFE_CAST(resultado_teste_an_para_2 AS INT64) resultado_teste_an_para_2,
SAFE_CAST(resultado_teste_an_para_3 AS INT64) resultado_teste_an_para_3,
SAFE_CAST(resultado_teste_an_adeno AS INT64) resultado_teste_an_adeno,
SAFE_CAST(resultado_teste_an_outro AS INT64) resultado_teste_an_outro,
SAFE_CAST(descricao_teste_an_outro AS STRING) descricao_teste_an_outro,
SAFE_CAST(tipo_amostra_sorologica AS INT64) tipo_amostra_sorologica,
SAFE_CAST(tipo_amostra_sorologica_outro AS STRING) tipo_amostra_sorologica_outro,
SAFE_CAST(data_coleta_amostra_sorologica AS DATE) data_coleta_amostra_sorologica,
SAFE_CAST(tipo_teste_sorologico AS INT64) tipo_teste_sorologico,
SAFE_CAST(tipo_teste_sorologico_outro AS STRING) tipo_teste_sorologico_outro,
SAFE_CAST(data_resultado_teste_sorologico AS DATE) data_resultado_teste_sorologico,
SAFE_CAST(resultado_teste_sorologico_igg AS INT64) resultado_teste_sorologico_igg,
SAFE_CAST(resultado_teste_sorologico_igm AS INT64) resultado_teste_sorologico_igm,
SAFE_CAST(resultado_teste_sorologico_iga AS INT64) resultado_teste_sorologico_iga
from basedosdados-staging.br_ms_srag2020_staging.microdados as t