# Igual ao dataset.name mas como lower case.
# Exemplos: br_ibge_populacao, br_inep_censo_escolar
dataset_id: br_ms_atencao_basica

table_id: municipio

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description: Cobertura populacional estimada de equipes de saúde da família (eSF) e de equipes de Atenção Básica (eAB) utilizada para o monitoramento do acesso aos serviços de Atenção Básica no nível municipal.
# A máxima unidade espacial que a tabela cobre.
# Exemplo:
#   - continent: south_america
#     country: br
spatial_coverage:
    continent:
        - south_america
    country:
        - br

# Anos cobertos pela tabela.
# Preencher como lista de intervalos.
# Exemplos: ['1995(1)2019'], ['2002(2)2010', '2016', '2020'].
temporal_coverage: 
    - 2007-07(1)2020-12

# A unidade temporal com qual a tabela é atualizada.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
update_frequency: month

# Nível de observação da tabela: o que representa cada linha.
observation_level:
    - município

last_updated:
    metadata:
    data:
    release:

# Versão da tabela. Seguindo o padrão de semantic versioning.
# Exemplo: v1.1.3
version: v1.0

# Quem está preenchendo esses metadados?
published_by:
    name: Laura Lopes Amaral
    email: laura.amaral@basedosdados.org
    github_user: https://github.com/laura-l-amaral
    ckan_user: ''
    website: ''

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
    name: Laura Lopes Amaral
    email: laura.amaral@basedosdados.org
    github_user: https://github.com/laura-l-amaral
    ckan_user: ''
    website: ''

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: 
    - Criação da coluna 'id_municipio' padrão 7 dígitos IBGE
    - Separação das colunas de ano-mes
    - Ajuste nos nomes das colunas

# Url do código de limpeza dos dados.
data_cleaning_code_url: https://drive.google.com/file/d/1tSQtzeeLhkKYWbtqa23Q_aBhIODhae5W/view?usp=sharing

# Organização que ajudou institucionalmente na disponibilização dos dados.
partner_organization:
    name:
    organization_id:

# Url dos dados originais no GCP Storage.
raw_files_url: 

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url: 

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions:

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Algumas colunas existirão apenas na tabela final, você as construirá em `publish.sql`.
# Para esses, defina is_in_staging como False.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: ano
      bigquery_type: int64
      description: Ano
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: ano
          column_name: ano
      measurement_unit: year
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: mes
      bigquery_type: int64
      description: Mês
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: mes
          column_name: mes
      measurement_unit: month
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: sigla_uf
      bigquery_type: string
      description: Sigla da Unidade da Federação
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: uf
          column_name: sigla
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: id_municipio
      bigquery_type: string
      description: ID Município IBGE - 7 Dígitos
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: municipio
          column_name: id_municipio_7
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: id_municipio_6
      bigquery_type: string
      description: ID Município IBGE - 6 Dígitos
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: municipio
          column_name: id_municipio_6
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: populacao
      bigquery_type: int64
      description: População considerada
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: person
      has_sensitive_data: no
      observations: É considerada sempre a estimativa feita pelo IBGE do ano anterior,
          com referência em 1º de julho.
      is_in_staging: true
      is_partition: false
    - name: carga_horaria_medica_atencao_basica_tradicional
      bigquery_type: float64
      description: Carga horária ambulatorial médica na atenção básica tradicional
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations: Consideram-se os profissionais cadastrados no SCNES com o código
          da Classificação Brasileira de Ocupações (CBO) 223115, 223116, 223129, 223132,
          223149, 2231F7, 225125, 225170, 225124, 225250, 225142 e 225130; e lotados
          nos estabelecimentos tipo 01 posto de saúde, 02 centro de saúde / unidade
          básica de saúde, 32 unidade móvel fluvial, ou 40 unidade móvel terrestre.
      is_in_staging: true
      is_partition: false
    - name: carga_horaria_enfermagem_atencao_basica_tradicional
      bigquery_type: float64
      description: Carga horária ambulatorial de enfermagem na atenção básica tradicional
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations: Consideram-se os profissionais cadastrados no SCNES na família
          CBO 2235; e lotados nos  estabelecimentos tipo 01 posto de saúde, 02 centro
          de saúde / unidade básica de saúde, 32 unidade móvel fluvial, ou 40 unidade
          móvel terrestre.
      is_in_staging: true
      is_partition: false
    - name: quantidade_equipes_atencao_basica_equivalente
      bigquery_type: int64
      description: Número de equipes de atenção básica tradicional equivalentes a
          equipes da Estratégia Saúde da Família
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations: Número de equipes de Atenção Básica tradicional equivalentes a
          equipes da Estratégia Saúde da Família, conforme carga horária ambulatorial
          de médicos e enfermeiros na Atenção Básica. Uma equipe equivalente é formada
          a partir do mínimo de 60h de carga horária ambulatorial médica e mínimo
          de 40h de carga horária ambulatorial de enfermagem na Atenção Básica.
      is_in_staging: true
      is_partition: false
    - name: quantidade_equipes_atencao_basica_parametrizada
      bigquery_type: int64
      description: Número de equipes de atenção básica tradicional parametrizadas
          para adesão ao Programa de Melhoria do Acesso e da Qualidade
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations: Corresponde aos códigos 16 a 21 desde que vinculadas aos estabelecimentos
          de saúde instituídas em sua respectiva portaria e cadastradas no SCNES.
          Essas equipes são ponderadas conforme Portaria nº 576/2011 (16 e 19 = 1
          equipe; 17 e 20 = 2 equipes; 18 e 21 = 3 equipes). (Portaria nº 576, de
          19 de setembro de 2011)
      is_in_staging: true
      is_partition: false
    - name: quantidade_equipes_saude_familia
      bigquery_type: int64
      description: Número de equipes da Estratégia Saúde da Família
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations: As equipes da Estratégia Saúde da Família são formada por médico,
          enfermeiro, técnico ou auxiliar de enfermagem e agentes comunitários de
          saúde, podendo haver uma equipe de Saúde Bucal vinculada, formada por cirurgião-dentista,
          auxiliar de consultório dentário e técnico em higiene dental. Corresponde
          aos códigos 01 a 03, 12 a 15 e 24 a 39 desde que vinculadas aos estabelecimentos
          de saúde instituídas em sua respectiva portaria e cadastradas no SCNES.
          As equipes de 24 a 38 são ponderadas conforme Portaria nº 703/2011 (24 a
          26 = 1 equipe; 27 a 29 = 2 equipes; 30 a 32 = 3 equipes; 33 a 35 = 0,85
          equipe; 36 a 38 = 0,6 equipe).
      is_in_staging: true
      is_partition: false
    - name: quantidade_equipes_atencao_basica_total
      bigquery_type: int64
      description: Número de equipes de Estratégia Saúde da Família e de atenção básica
          tradicional equivalentes e parametrizadas
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: populacao_coberta_estrategia_saude_familia
      bigquery_type: int64
      description: Estimativa da população coberta pela Estratégia Saúde da Família
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations: Considera-se o parâmetro de 3.450 indivíduos cobertos por equipe
          de saúde da família
      is_in_staging: true
      is_partition: false
    - name: porcentagem_cobertura_estrategia_saude_familia
      bigquery_type: float64
      description: Percentual da população coberta pela Estratégia Saúde da Família
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: populacao_coberta_total_atencao_basica
      bigquery_type: int64
      description: Estimativa da população coberta pela atenção básica
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations: População coberta por equipes da Estratégia Saúde da Família e
          por equipes de Atenção Básica tradicional equivalentes e parametrizadas
          em relação à estimativa populacional. Para equipes de atenção básica tradicional
          equivalentes e parametrizdas, considera-se o parâmetro de 3.000 indivíduos
          cobertos por equipe. Considera-se o parâmetro de 3.450 indivíduos cobertos
          por equipe de saúde da família.
      is_in_staging: true
      is_partition: false
    - name: porcentagem_cobertura_total_atencao_basica
      bigquery_type: float64
      description: Percentual da população coberta pela atenção básica
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false

metadata_modified:
