
# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: br-ibge-estadic

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Pesquisa de Informações Básicas Estaduais - ESTADIC

# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Exemplos: br-ibge, br-tse, br-rj-gov
organization: br-ibge

# Descrição do conjunto
notes: A Pesquisa de Informações Básicas Estaduais - ESTADIC é um levantamento pormenorizado de registros administrativos sobre a estrutura, a dinâmica e o funcionamento das instituições públicas estaduais.

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
  - gov-fin-pub
  - politica

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos: fertilidade, preco, desmatamento.
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
  - sistema
  - administracao publica
  - informacao

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified:
