
# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: br-inep-sinopse-estatistica-educacao-basica

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Sinopses Estatísticas da Educação Básica

# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Se a organização não estiver na lista acima ou o nome não estiver conforme o manual de estilo
# criar ou renomear a organização em https://basedosdados.org/organization/
# Exemplos: br-ibge, br-tse, br-rj-gov
organization:
    - br-inep

# Descrição do conjunto
notes: As Sinopses Estatísticas do Inep correspondem a um conjunto de tabelas com
    dados recolhidos por suas pesquisas estatísticas, avaliações e exames. Elaborada
    anualmente pela Diretoria de Estatísticas Educacionais (Deed), a Sinopse Estatística
    traz um resumo dos principais dados coletados no Censo Escolar da Educação Básica.

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
    - educacao

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos:
#    - fertilidade
#    - preco
#    - desmatamento
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
    - aluno
    - aprendizagem
    - educacao basica
    - escola
    - indicadores educacionais
    - matricula

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified: '2022-12-20T18:47:38.481695'
