
# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: br-fgv-igp

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Índice Geral de Preços

# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Exemplos: br-ibge, br-tse, br-rj-gov
organization: br-fgv

# Descrição do conjunto
notes: |
    Os índices de preços medem a variação média dos preços entre dois períodos na economia, sendo o meio de cálculo da inflação e cada índice possui suas próprias características. O Índice Geral de Preços (IGP) registra o ritmo evolutivo de preços como medida síntese da inflação nacional. Apresenta-se em três versões: Índice Geral de Preços - 10 (IGP-10), Índice Geral de Preços do Mercado (IGP-M) e Índice Geral de Preços – Disponibilidade Interna (IGP-DI). A diferença entre eles está no período de apuração das informações para cálculo do índice.

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
    - economia

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos: fertilidade, preco, desmatamento.
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
  - preco
  - inflacao

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified:
