
# Igual ao dataset.name mas como lower case.
# Exemplos: br_ibge_populacao, br_inep_censo_escolar
dataset_id: br_mma_extincao

table_id: fauna_ameacada

# Título da tabela.
title: Fauna ameaçada de extinção

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description: A tabela mostra o anexo da portaria nº 148 (junho/2022) do Ministério do Meio Ambiente a respeito da lista oficial de espécies da fauna brasileira ameaçadas de extinção

# As máximas unidades espaciais que a tabela cobre.
# Exemplo:
#   - sa.br
spatial_coverage:
  - sa.br

# Anos cobertos pela tabela.
# Preencher como lista de intervalos.
# Exemplos: ['1995(1)2019'], ['2002(2)2010', '2016', '2020'].
temporal_coverage:
  - '2022'

# A unidade temporal com qual a tabela é atualizada.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
update_frequency: uncertain

# Nível de observação da tabela: o que representa cada linha.
observation_level:
   - entity: animal

last_updated:
    metadata: '2022-07-25'
    data: '2022-07-25 08:30:45'
    release: '2022-07-23'

# Versão da tabela. Seguindo o padrão de semantic versioning.
# Exemplo: v1.1.3
version: v1.0

# Quem está preenchendo esses metadados?
published_by:
    name: Lucas Moreira
    email: lucas.moreira@basedosdados.org.br
    github_user: lucasnascm
    ckan_user: lucasnascm
    website:

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
    name: Bruno Mioto
    email: brunomioto97@gmail.com
    github_user: brunomioto
    ckan_user:
    website:

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: Extração dos dados em pdf disponibilizados pelo Ministério

# Url do código de limpeza dos dados.
data_cleaning_code_url: https://github.com/basedosdados/mais/tree/master/bases/br_mma_extincao/code

# Organização que ajudou institucionalmente na disponibilização dos dados.
partner_organization:
    name:
    organization_id:

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions:

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Algumas colunas existirão apenas na tabela final, você as construirá em `publish.sql`.
# Para esses, defina is_in_staging como False.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: grupo
      bigquery_type: string
      description: Agrupamento por grandes grupos dos animais (e.g. anfibios, aves, peixes)
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: ordem
      bigquery_type: string
      description: Classificação taxonômica a nível de Ordem
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: familia
      bigquery_type: string
      description: Classificação taxonômica a nível de Família
      temporal_coverage: 
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: especie_ou_subespecie
      bigquery_type: string
      description: Espécie ou subespécie 
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: 
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: categoria
      bigquery_type: string
      description: Estado de conservação da espécie ou subespécie segundo a União Internacional para a Conservação da Natureza e dos Recursos Naturais
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations: A sigla "VU" significa que a espécie está vulnerável e corre riscos de extinção no futuro bem próximo. "EN" mostra que a espécie está em perigo. "CR" significa criticamente em perigo, "CR (PEX)" provavelmente extinto, "EW" quer dizer que a espécie está extinta na natureza, "ER" mostra que a espécie está extinta regionalmente e "EX" quer dizer que espécie está extinta.
      is_in_staging: true
      is_partition: false
    - name: lista_2014
      bigquery_type: int64
      description: Evidencia se a espécie já estava listada na Portaria nº 443 de 17 de dezembro de 2014
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false

metadata_modified:
