
# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: eu-fra-lgbt

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Pesquisa Online Sobre a Comunidade LGBT (Fundamental Rights Agency)

# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Exemplos: br-ibge, br-tse, br-rj-gov
organization:
    - eu-fra

# Descrição do conjunto
notes: "O dataset contém tabelas relacionadas a uma ampla pesquisa online sobre e\
    \ para a comunidade LGBT, conduzida em 2012 em quase todos os países europeus.\
    \ A pesquisa continha diferentes grupos de questões, que motivaram as diferentes\
    \ tabelas criadas. Cada tabela abrange uma temática e contém perguntas dessa temática.\
    \ São exemplos: discriminação, direitos e cotidiano.\n"

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
    - diversidade
    - populacao

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos: fertilidade, preco, desmatamento.
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
    - Homofobia
    - LGBT
    - LGBTfobia
    - Lesbofobia
    - Pessoas trans

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified: '2022-07-28T23:00:37.592620'
