# -*- coding: utf-8 -*-
"""[dados] br_bd_diretorios_brasil.area_conhecimento

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PJNioQfIKWE2OHxSQZWI93HqdjUkoGrR
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

#arquivo
ac = pd.read_excel('/content/drive/MyDrive/area_conhecimento.xlsx', dtype='str')

#separando o id conforme classificação
ac['grande_area'] = ac['id'].str[0]
ac['area'] = ac['id'].str[1:3]
ac['subarea'] = ac['id'].str[3:5]
ac['esp'] = ac['id'].str[5:7]
ac['especialidade'] = ac['id'].str[5:7] + "-" + ac['id'].str[7]

#criando sub-dataframes para o formato de diretório
grande_area = ac.query('area == "00"')
grande_area.drop(['id', 'area', 'subarea', 'esp', 'especialidade'], axis=1, inplace=True)

area = ac.query('subarea == "00" & area != "00"')
area.drop(['id', 'subarea', 'esp', 'especialidade'], axis=1, inplace=True)

subarea = ac.query('subarea != "00" & esp == "00"')
subarea.drop(['id', 'esp', 'especialidade'], axis=1, inplace=True)

especialidade = ac.query('esp != "00"')
especialidade.drop(['esp', 'especialidade'], axis=1, inplace=True)

#agrupando os subdataframes para obtenção das colunas
ac1 = pd.merge(especialidade, subarea, how='left', on=['grande_area', 'area', 'subarea'])
ac1.rename(columns={'descricao_y':'descricao_subarea', 'descricao_x':'descricao_especialidade'}, inplace=True)
ac2 = pd.merge(ac1, area, how='left', on=['grande_area', 'area'])
ac3 = pd.merge(ac2, grande_area, how='left', on=['grande_area'])

#rename
ac3.rename(columns={'id':'especialidade', 'descricao_x':'descricao_area', 'descricao_y':'descricao_grande_area'}, inplace=True)
ac3 = ac3[['especialidade', 'descricao_especialidade', 'subarea', 'descricao_subarea', 'area', 'descricao_area',
           'grande_area', 'descricao_grande_area']]

#incluindo dados de multidisciplinar
multi = [['90191000',0,'91', 'MEIO AMBIENTE E AGRÁRIAS', '01', 'INTERDISCIPLINAR', '9', 'MULTIDISCIPLINAR'],
         ['90192000',0,'92', 'SOCIAIS E HUMANIDADES', '01', 'INTERDISCIPLINAR', '9', 'MULTIDISCIPLINAR'],
         ['90193000',0,'93', 'ENGENHARIA/TECNOLOGIA/GESTÃO', '01', 'INTERDISCIPLINAR', '9', 'MULTIDISCIPLINAR'],
         ['90194000',0,'94', 'SAÚDE E BIOLÓGICAS', '01', 'INTERDISCIPLINAR', '9', 'MULTIDISCIPLINAR'],
         ['90201000',0,'01', 'ENSINO DE CIÊNCIAS E MATEMÁTICA', '02', 'ENSINO', '9', 'MULTIDISCIPLINAR'],
         ['90300009',0,0,0, '03', 'MATERIAIS', '9', 'MULTIDISCIPLINAR'],
         ['90400003',0,0,0, '03', 'BIOTECNOLOGIA', '9', 'MULTIDISCIPLINAR'],
         ['90500008',0,0,0, '03', 'CIÊNCIAS AMBIENTAIS', '9', 'MULTIDISCIPLINAR']]
ac_multi = pd.DataFrame(multi, columns=['especialidade', 'descricao_especialidade', 'subarea', 'descricao_subarea', 'area', 'descricao_area',
           'grande_area', 'descricao_grande_area'])
ac_multi = ac_multi.replace(0, '')

ac3 = ac3.append(ac_multi)
ac3.to_csv('/content/area_conhecimento.csv', index=False, na_rep='', float_format='%.0f', encoding='utf-8')