
# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: br-ibge-ipca

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Índice Nacional de Preços ao Consumidor Amplo (IPCA)

# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Exemplos: br-ibge, br-tse, br-rj-gov
organization:
    - br-ibge

# Descrição do conjunto
notes: Índice Nacional de Preços ao Consumidor Amplo - IPCA é produzido pelo IBGE
    desde dezembro de 1979. O IPCA é utilizado como indicador oficial do País desde
    1985 para corrigir salários, aluguéis, taxa de câmbio, poupança, entre outros.
    São divulgados os índices gerais, por grupos de produtos, subgrupos, itens e subitens,
    para as regiões pesquisadas, além do agregado Brasil.

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
    - economia

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos: fertilidade, preco, desmatamento.
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
    - inflacao
    - preco

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified: '2022-07-28T22:50:53.453318'
