/*

Query para publicar a tabela.

Esse é o lugar para:
    - modificar nomes, ordem e tipos de colunas
    - dar join com outras tabelas
    - criar colunas extras (e.g. logs, proporções, etc.)

Qualquer coluna definida aqui deve também existir em `table_config.yaml`.

# Além disso, sinta-se à vontade para alterar alguns nomes obscuros
# para algo um pouco mais explícito.

TIPOS:
    - Para modificar tipos de colunas, basta substituir STRING por outro tipo válido.
    - Exemplo: `SAFE_CAST(column_name AS NUMERIC) column_name`
    - Mais detalhes: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types

*/

CREATE VIEW basedosdados-dev.br_inep_censo_escolar.escola AS
SELECT 
SAFE_CAST(ano AS INT64) ano,
SAFE_CAST(sigla_uf AS STRING) sigla_uf,
SAFE_CAST(id_municipio AS INT64) id_municipio,
SAFE_CAST(id_orgao_regional AS INT64) id_orgao_regional,
SAFE_CAST(id_escola AS INT64) id_escola,
SAFE_CAST(rede AS STRING) rede,
SAFE_CAST(tipo_situacao_funcionamento AS INT64) tipo_situacao_funcionamento,
SAFE_CAST(data_ano_letivo_inicio AS STRING) data_ano_letivo_inicio,
SAFE_CAST(data_ano_letivo_termino AS STRING) data_ano_letivo_termino,
SAFE_CAST(tipo_localizacao AS INT64) tipo_localizacao,
SAFE_CAST(tipo_categoria_escola_privada AS INT64) tipo_categoria_escola_privada,
SAFE_CAST(conveniada_poder_publico AS INT64) conveniada_poder_publico,
SAFE_CAST(tipo_convenio_poder_publico AS INT64) tipo_convenio_poder_publico,
SAFE_CAST(mantenedora_escola_privada_emp AS INT64) mantenedora_escola_privada_emp,
SAFE_CAST(mantenedora_escola_privada_ong AS INT64) mantenedora_escola_privada_ong,
SAFE_CAST(mantenedora_escola_privada_sind AS INT64) mantenedora_escola_privada_sind,
SAFE_CAST(mantenedora_escola_privada_sist_s AS INT64) mantenedora_escola_privada_sist_s,
SAFE_CAST(mantenedora_escola_privada_s_fins AS INT64) mantenedora_escola_privada_s_fins,
SAFE_CAST(tipo_regulamentacao AS INT64) tipo_regulamentacao,
SAFE_CAST(tipo_ocupacao_predio_escolar AS INT64) tipo_ocupacao_predio_escolar,
SAFE_CAST(local_func_salas_empresa AS INT64) local_func_salas_empresa,
SAFE_CAST(local_func_socioeducativo AS INT64) local_func_socioeducativo,
SAFE_CAST(predio_compartilhado AS INT64) predio_compartilhado,
SAFE_CAST(local_func_unid_prisional AS INT64) local_func_unid_prisional,
SAFE_CAST(local_func_templo_igreja AS INT64) local_func_templo_igreja,
SAFE_CAST(local_func_casa_professor AS INT64) local_func_casa_professor,
SAFE_CAST(tipo_ocupacao_galpao AS INT64) tipo_ocupacao_galpao,
SAFE_CAST(local_func_outros AS INT64) local_func_outros,
SAFE_CAST(local_func_salas_outra_esc AS INT64) local_func_salas_outra_esc,
SAFE_CAST(agua_potavel AS INT64) agua_potavel,
SAFE_CAST(agua_rede_publica AS INT64) agua_rede_publica,
SAFE_CAST(agua_poco_artesiano AS INT64) agua_poco_artesiano,
SAFE_CAST(agua_cacimba AS INT64) agua_cacimba,
SAFE_CAST(agua_fonte_rio AS INT64) agua_fonte_rio,
SAFE_CAST(agua_inexistente AS INT64) agua_inexistente,
SAFE_CAST(energia_rede_publica AS INT64) energia_rede_publica,
SAFE_CAST(energia_gerador AS INT64) energia_gerador,
SAFE_CAST(energia_outros AS INT64) energia_outros,
SAFE_CAST(energia_inexistente AS INT64) energia_inexistente,
SAFE_CAST(esgoto_rede_publica AS INT64) esgoto_rede_publica,
SAFE_CAST(esgoto_fossa AS INT64) esgoto_fossa,
SAFE_CAST(esgoto_inexistente AS INT64) esgoto_inexistente,
SAFE_CAST(lixo_servico_coleta AS INT64) lixo_servico_coleta,
SAFE_CAST(lixo_queima AS INT64) lixo_queima,
SAFE_CAST(lixo_descarta_outra_area AS INT64) lixo_descarta_outra_area,
SAFE_CAST(tratamento_lixo_reciclagem AS INT64) tratamento_lixo_reciclagem,
SAFE_CAST(lixo_enterra AS INT64) lixo_enterra,
SAFE_CAST(lixo_outros AS INT64) lixo_outros,
SAFE_CAST(sala_diretoria AS INT64) sala_diretoria,
SAFE_CAST(sala_professor AS INT64) sala_professor,
SAFE_CAST(laboratorio_informatica AS INT64) laboratorio_informatica,
SAFE_CAST(laboratorio_ciencias AS INT64) laboratorio_ciencias,
SAFE_CAST(sala_atendimento_especial AS INT64) sala_atendimento_especial,
SAFE_CAST(quadra_esportes AS INT64) quadra_esportes,
SAFE_CAST(quadra_esportes_coberta AS INT64) quadra_esportes_coberta,
SAFE_CAST(quadra_esportes_descoberta AS INT64) quadra_esportes_descoberta,
SAFE_CAST(cozinha AS INT64) cozinha,
SAFE_CAST(biblioteca AS INT64) biblioteca,
SAFE_CAST(sala_leitura AS INT64) sala_leitura,
SAFE_CAST(parque_infantil AS INT64) parque_infantil,
SAFE_CAST(bercario AS INT64) bercario,
SAFE_CAST(banheiro_fora_predio AS INT64) banheiro_fora_predio,
SAFE_CAST(banheiro_dentro_predio AS INT64) banheiro_dentro_predio,
SAFE_CAST(banheiro_ei AS INT64) banheiro_ei,
SAFE_CAST(banheiro_pne AS INT64) banheiro_pne,
SAFE_CAST(dependencias_pne AS INT64) dependencias_pne,
SAFE_CAST(secretaria AS INT64) secretaria,
SAFE_CAST(banheiro_chuveiro AS INT64) banheiro_chuveiro,
SAFE_CAST(refeitorio AS INT64) refeitorio,
SAFE_CAST(despensa AS INT64) despensa,
SAFE_CAST(almoxarifado AS INT64) almoxarifado,
SAFE_CAST(auditorio AS INT64) auditorio,
SAFE_CAST(patio_coberto AS INT64) patio_coberto,
SAFE_CAST(patio_descoberto AS INT64) patio_descoberto,
SAFE_CAST(alojamento_aluno AS INT64) alojamento_aluno,
SAFE_CAST(alojamento_professor AS INT64) alojamento_professor,
SAFE_CAST(area_verde AS INT64) area_verde,
SAFE_CAST(lavanderia AS INT64) lavanderia,
SAFE_CAST(dependencias_outras AS INT64) dependencias_outras,
SAFE_CAST(quantidade_salas_utilizadas AS INT64) quantidade_salas_utilizadas,
SAFE_CAST(quantidade_salas_existentes AS INT64) quantidade_salas_existentes,
SAFE_CAST(equipamento_tv AS INT64) equipamento_tv,
SAFE_CAST(quantidade_equipamento_tv AS INT64) quantidade_equipamento_tv,
SAFE_CAST(equipamento_videocassete AS INT64) equipamento_videocassete,
SAFE_CAST(quantidade_equipamento_videocassete AS INT64) quantidade_equipamento_videocassete,
SAFE_CAST(equipamento_dvd AS INT64) equipamento_dvd,
SAFE_CAST(quantidade_equipamento_dvd AS INT64) quantidade_equipamento_dvd,
SAFE_CAST(equipamento_parabolica AS INT64) equipamento_parabolica,
SAFE_CAST(equipamento_copiadora AS INT64) equipamento_copiadora,
SAFE_CAST(quantidade_equipamento_copiadora AS INT64) quantidade_equipamento_copiadora,
SAFE_CAST(equipamento_retroprojetor AS INT64) equipamento_retroprojetor,
SAFE_CAST(equipamento_impressora AS INT64) equipamento_impressora,
SAFE_CAST(quantidade_equipamento_impressora AS INT64) quantidade_equipamento_impressora,
SAFE_CAST(equipamento_som AS INT64) equipamento_som,
SAFE_CAST(quantidade_equipamento_som AS INT64) quantidade_equipamento_som,
SAFE_CAST(equipamento_multimidia AS INT64) equipamento_multimidia,
SAFE_CAST(quantidade_equipamento_multimidia AS INT64) quantidade_equipamento_multimidia,
SAFE_CAST(equipamento_fax AS INT64) equipamento_fax,
SAFE_CAST(equipamento_foto AS INT64) equipamento_foto,
SAFE_CAST(quantidade_computador AS INT64) quantidade_computador,
SAFE_CAST(quantidade_comp_administrativo AS INT64) quantidade_comp_administrativo,
SAFE_CAST(quantidade_comp_aluno AS INT64) quantidade_comp_aluno,
SAFE_CAST(internet AS INT64) internet,
SAFE_CAST(banda_larga AS INT64) banda_larga,
SAFE_CAST(quantidade_funcionarios AS INT64) quantidade_funcionarios,
SAFE_CAST(alimentacao AS INT64) alimentacao,
SAFE_CAST(tipo_atendimento_educacional_especial AS INT64) tipo_atendimento_educacional_especial,
SAFE_CAST(tipo_atividade_complementar AS INT64) tipo_atividade_complementar,
SAFE_CAST(regular AS INT64) regular,
SAFE_CAST(comum_creche AS INT64) comum_creche,
SAFE_CAST(comum_pre AS INT64) comum_pre,
SAFE_CAST(comum_fund_ai AS INT64) comum_fund_ai,
SAFE_CAST(comum_fund_af AS INT64) comum_fund_af,
SAFE_CAST(comum_medio_medio AS INT64) comum_medio_medio,
SAFE_CAST(comum_medio_integrado AS INT64) comum_medio_integrado,
SAFE_CAST(comum_medio_normal AS INT64) comum_medio_normal,
SAFE_CAST(comum_prof AS INT64) comum_prof,
SAFE_CAST(especial_exclusiva AS INT64) especial_exclusiva,
SAFE_CAST(especial_exclusiva_creche AS INT64) especial_exclusiva_creche,
SAFE_CAST(especial_exclusiva_pre AS INT64) especial_exclusiva_pre,
SAFE_CAST(especial_exclusiva_fund_ai AS INT64) especial_exclusiva_fund_ai,
SAFE_CAST(especial_exclusiva_fund_af AS INT64) especial_exclusiva_fund_af,
SAFE_CAST(especial_exclusiva_medio_medio AS INT64) especial_exclusiva_medio_medio,
SAFE_CAST(especial_exclusiva_medio_integr AS INT64) especial_exclusiva_medio_integr,
SAFE_CAST(especial_exclusiva_medio_normal AS INT64) especial_exclusiva_medio_normal,
SAFE_CAST(especial_exclusiva_prof AS INT64) especial_exclusiva_prof,
SAFE_CAST(especial_exclusiva_eja_fund AS INT64) especial_exclusiva_eja_fund,
SAFE_CAST(especial_exclusiva_eja_medio AS INT64) especial_exclusiva_eja_medio,
SAFE_CAST(eja AS INT64) eja,
SAFE_CAST(comum_eja_fund AS INT64) comum_eja_fund,
SAFE_CAST(comum_eja_medio AS INT64) comum_eja_medio,
SAFE_CAST(comum_eja_prof AS INT64) comum_eja_prof,
SAFE_CAST(fundamental_ciclos AS INT64) fundamental_ciclos,
SAFE_CAST(tipo_localizacao_diferenciada AS INT64) tipo_localizacao_diferenciada,
SAFE_CAST(material_esp_nao_utiliza AS INT64) material_esp_nao_utiliza,
SAFE_CAST(material_esp_quilombola AS INT64) material_esp_quilombola,
SAFE_CAST(material_ped_indigena AS INT64) material_ped_indigena,
SAFE_CAST(educacao_indigena AS INT64) educacao_indigena,
SAFE_CAST(id_lingua_indigena AS INT64) id_lingua_indigena,

from basedosdados-dev.br_inep_censo_escolar_staging.escola as t