/*

Query para publicar a tabela.

Esse é o lugar para:
    - modificar nomes, ordem e tipos de colunas
    - dar join com outras tabelas
    - criar colunas extras (e.g. logs, proporções, etc.)

Qualquer coluna definida aqui deve também existir em `table_config.yaml`.

# Além disso, sinta-se à vontade para alterar alguns nomes obscuros
# para algo um pouco mais explícito.

TIPOS:
    - Para modificar tipos de colunas, basta substituir STRING por outro tipo válido.
    - Exemplo: `SAFE_CAST(column_name AS NUMERIC) column_name`
    - Mais detalhes: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types

*/

CREATE VIEW basedosdados-dev.br_inep_censo_escolar.escola AS
SELECT 
SAFE_CAST(ano AS INT64) ano,
SAFE_CAST(sigla_uf AS STRING) sigla_uf,
SAFE_CAST(id_municipio AS INT64) id_municipio,
SAFE_CAST(id_escola AS INT64) id_escola,
SAFE_CAST(nome_escola AS STRING) nome_escola,
SAFE_CAST(co_orgao_regional AS INT64) co_orgao_regional,
SAFE_CAST(tp_situacao_funcionamento AS INT64) tp_situacao_funcionamento,
SAFE_CAST(dt_ano_letivo_inicio AS STRING) dt_ano_letivo_inicio,
SAFE_CAST(dt_ano_letivo_termino AS STRING) dt_ano_letivo_termino,
SAFE_CAST(tp_dependencia AS INT64) tp_dependencia,
SAFE_CAST(tp_localizacao AS INT64) tp_localizacao,
SAFE_CAST(tp_categoria_escola_privada AS INT64) tp_categoria_escola_privada,
SAFE_CAST(in_conveniada_pp AS INT64) in_conveniada_pp,
SAFE_CAST(tp_convenio_poder_publico AS INT64) tp_convenio_poder_publico,
SAFE_CAST(in_mant_escola_privada_emp AS INT64) in_mant_escola_privada_emp,
SAFE_CAST(in_mant_escola_privada_ong AS INT64) in_mant_escola_privada_ong,
SAFE_CAST(in_mant_escola_privada_sind AS INT64) in_mant_escola_privada_sind,
SAFE_CAST(in_mant_escola_privada_sist_s AS INT64) in_mant_escola_privada_sist_s,
SAFE_CAST(in_mant_escola_privada_s_fins AS INT64) in_mant_escola_privada_s_fins,
SAFE_CAST(tp_regulamentacao AS INT64) tp_regulamentacao,
SAFE_CAST(tp_ocupacao_predio_escolar AS INT64) tp_ocupacao_predio_escolar,
SAFE_CAST(in_local_func_salas_empresa AS INT64) in_local_func_salas_empresa,
SAFE_CAST(in_local_func_socioeducativo AS INT64) in_local_func_socioeducativo,
SAFE_CAST(in_predio_compartilhado AS INT64) in_predio_compartilhado,
SAFE_CAST(in_local_func_unid_prisional AS INT64) in_local_func_unid_prisional,
SAFE_CAST(in_local_func_templo_igreja AS INT64) in_local_func_templo_igreja,
SAFE_CAST(in_local_func_casa_professor AS INT64) in_local_func_casa_professor,
SAFE_CAST(tp_ocupacao_galpao AS INT64) tp_ocupacao_galpao,
SAFE_CAST(in_local_func_outros AS INT64) in_local_func_outros,
SAFE_CAST(in_local_func_salas_outra_esc AS INT64) in_local_func_salas_outra_esc,
SAFE_CAST(in_agua_potavel AS INT64) in_agua_potavel,
SAFE_CAST(in_agua_rede_publica AS INT64) in_agua_rede_publica,
SAFE_CAST(in_agua_poco_artesiano AS INT64) in_agua_poco_artesiano,
SAFE_CAST(in_agua_cacimba AS INT64) in_agua_cacimba,
SAFE_CAST(in_agua_fonte_rio AS INT64) in_agua_fonte_rio,
SAFE_CAST(in_agua_inexistente AS INT64) in_agua_inexistente,
SAFE_CAST(in_energia_rede_publica AS INT64) in_energia_rede_publica,
SAFE_CAST(in_energia_gerador AS INT64) in_energia_gerador,
SAFE_CAST(in_energia_outros AS INT64) in_energia_outros,
SAFE_CAST(in_energia_inexistente AS INT64) in_energia_inexistente,
SAFE_CAST(in_esgoto_rede_publica AS INT64) in_esgoto_rede_publica,
SAFE_CAST(in_esgoto_fossa AS INT64) in_esgoto_fossa,
SAFE_CAST(in_esgoto_inexistente AS INT64) in_esgoto_inexistente,
SAFE_CAST(in_lixo_servico_coleta AS INT64) in_lixo_servico_coleta,
SAFE_CAST(in_lixo_queima AS INT64) in_lixo_queima,
SAFE_CAST(in_lixo_descarta_outra_area AS INT64) in_lixo_descarta_outra_area,
SAFE_CAST(in_tratamento_lixo_reciclagem AS INT64) in_tratamento_lixo_reciclagem,
SAFE_CAST(in_lixo_enterra AS INT64) in_lixo_enterra,
SAFE_CAST(in_lixo_outros AS INT64) in_lixo_outros,
SAFE_CAST(in_sala_diretoria AS INT64) in_sala_diretoria,
SAFE_CAST(in_sala_professor AS INT64) in_sala_professor,
SAFE_CAST(in_laboratorio_informatica AS INT64) in_laboratorio_informatica,
SAFE_CAST(in_laboratorio_ciencias AS INT64) in_laboratorio_ciencias,
SAFE_CAST(in_sala_atendimento_especial AS INT64) in_sala_atendimento_especial,
SAFE_CAST(in_quadra_esportes AS INT64) in_quadra_esportes,
SAFE_CAST(in_quadra_esportes_coberta AS INT64) in_quadra_esportes_coberta,
SAFE_CAST(in_quadra_esportes_descoberta AS INT64) in_quadra_esportes_descoberta,
SAFE_CAST(in_cozinha AS INT64) in_cozinha,
SAFE_CAST(in_biblioteca AS INT64) in_biblioteca,
SAFE_CAST(in_sala_leitura AS INT64) in_sala_leitura,
SAFE_CAST(in_parque_infantil AS INT64) in_parque_infantil,
SAFE_CAST(in_bercario AS INT64) in_bercario,
SAFE_CAST(in_banheiro_fora_predio AS INT64) in_banheiro_fora_predio,
SAFE_CAST(in_banheiro_dentro_predio AS INT64) in_banheiro_dentro_predio,
SAFE_CAST(in_banheiro_ei AS INT64) in_banheiro_ei,
SAFE_CAST(in_banheiro_pne AS INT64) in_banheiro_pne,
SAFE_CAST(in_dependencias_pne AS INT64) in_dependencias_pne,
SAFE_CAST(in_secretaria AS INT64) in_secretaria,
SAFE_CAST(in_banheiro_chuveiro AS INT64) in_banheiro_chuveiro,
SAFE_CAST(in_refeitorio AS INT64) in_refeitorio,
SAFE_CAST(in_despensa AS INT64) in_despensa,
SAFE_CAST(in_almoxarifado AS INT64) in_almoxarifado,
SAFE_CAST(in_auditorio AS INT64) in_auditorio,
SAFE_CAST(in_patio_coberto AS INT64) in_patio_coberto,
SAFE_CAST(in_patio_descoberto AS INT64) in_patio_descoberto,
SAFE_CAST(in_alojam_aluno AS INT64) in_alojam_aluno,
SAFE_CAST(in_alojam_professor AS INT64) in_alojam_professor,
SAFE_CAST(in_area_verde AS INT64) in_area_verde,
SAFE_CAST(in_lavanderia AS INT64) in_lavanderia,
SAFE_CAST(in_dependencias_outras AS INT64) in_dependencias_outras,
SAFE_CAST(qt_salas_utilizadas AS INT64) qt_salas_utilizadas,
SAFE_CAST(qt_salas_existentes AS INT64) qt_salas_existentes,
SAFE_CAST(in_equip_tv AS INT64) in_equip_tv,
SAFE_CAST(qt_equip_tv AS INT64) qt_equip_tv,
SAFE_CAST(in_equip_videocassete AS INT64) in_equip_videocassete,
SAFE_CAST(qt_equip_videocassete AS INT64) qt_equip_videocassete,
SAFE_CAST(in_equip_dvd AS INT64) in_equip_dvd,
SAFE_CAST(qt_equip_dvd AS INT64) qt_equip_dvd,
SAFE_CAST(in_equip_parabolica AS INT64) in_equip_parabolica,
SAFE_CAST(in_equip_copiadora AS INT64) in_equip_copiadora,
SAFE_CAST(qt_equip_copiadora AS INT64) qt_equip_copiadora,
SAFE_CAST(in_equip_retroprojetor AS INT64) in_equip_retroprojetor,
SAFE_CAST(in_equip_impressora AS INT64) in_equip_impressora,
SAFE_CAST(qt_equip_impressora AS INT64) qt_equip_impressora,
SAFE_CAST(in_equip_som AS INT64) in_equip_som,
SAFE_CAST(qt_equip_som AS INT64) qt_equip_som,
SAFE_CAST(in_equip_multimidia AS INT64) in_equip_multimidia,
SAFE_CAST(qt_equip_multimidia AS INT64) qt_equip_multimidia,
SAFE_CAST(in_equip_fax AS INT64) in_equip_fax,
SAFE_CAST(in_equip_foto AS INT64) in_equip_foto,
SAFE_CAST(qt_computador AS INT64) qt_computador,
SAFE_CAST(qt_comp_administrativo AS INT64) qt_comp_administrativo,
SAFE_CAST(qt_comp_aluno AS INT64) qt_comp_aluno,
SAFE_CAST(in_internet AS INT64) in_internet,
SAFE_CAST(in_banda_larga AS INT64) in_banda_larga,
SAFE_CAST(qt_funcionarios AS INT64) qt_funcionarios,
SAFE_CAST(in_alimentacao AS INT64) in_alimentacao,
SAFE_CAST(tp_aee AS INT64) tp_aee,
SAFE_CAST(tp_atividade_complementar AS INT64) tp_atividade_complementar,
SAFE_CAST(in_regular AS INT64) in_regular,
SAFE_CAST(in_comum_creche AS INT64) in_comum_creche,
SAFE_CAST(in_comum_pre AS INT64) in_comum_pre,
SAFE_CAST(in_comum_fund_ai AS INT64) in_comum_fund_ai,
SAFE_CAST(in_comum_fund_af AS INT64) in_comum_fund_af,
SAFE_CAST(in_comum_medio_medio AS INT64) in_comum_medio_medio,
SAFE_CAST(in_comum_medio_integrado AS INT64) in_comum_medio_integrado,
SAFE_CAST(in_comum_medio_normal AS INT64) in_comum_medio_normal,
SAFE_CAST(in_comum_prof AS INT64) in_comum_prof,
SAFE_CAST(in_especial_exclusiva AS INT64) in_especial_exclusiva,
SAFE_CAST(in_esp_exclusiva_creche AS INT64) in_esp_exclusiva_creche,
SAFE_CAST(in_esp_exclusiva_pre AS INT64) in_esp_exclusiva_pre,
SAFE_CAST(in_esp_exclusiva_fund_ai AS INT64) in_esp_exclusiva_fund_ai,
SAFE_CAST(in_esp_exclusiva_fund_af AS INT64) in_esp_exclusiva_fund_af,
SAFE_CAST(in_esp_exclusiva_medio_medio AS INT64) in_esp_exclusiva_medio_medio,
SAFE_CAST(in_esp_exclusiva_medio_integr AS INT64) in_esp_exclusiva_medio_integr,
SAFE_CAST(in_esp_exclusiva_medio_normal AS INT64) in_esp_exclusiva_medio_normal,
SAFE_CAST(in_esp_exclusiva_prof AS INT64) in_esp_exclusiva_prof,
SAFE_CAST(in_esp_exclusiva_eja_fund AS INT64) in_esp_exclusiva_eja_fund,
SAFE_CAST(in_esp_exclusiva_eja_medio AS INT64) in_esp_exclusiva_eja_medio,
SAFE_CAST(in_eja AS INT64) in_eja,
SAFE_CAST(in_comum_eja_fund AS INT64) in_comum_eja_fund,
SAFE_CAST(in_comum_eja_medio AS INT64) in_comum_eja_medio,
SAFE_CAST(in_comum_eja_prof AS INT64) in_comum_eja_prof,
SAFE_CAST(in_fundamental_ciclos AS INT64) in_fundamental_ciclos,
SAFE_CAST(tp_localizacao_diferenciada AS INT64) tp_localizacao_diferenciada,
SAFE_CAST(in_material_esp_nao_utiliza AS INT64) in_material_esp_nao_utiliza,
SAFE_CAST(in_material_esp_quilombola AS INT64) in_material_esp_quilombola,
SAFE_CAST(in_material_ped_indigena AS INT64) in_material_ped_indigena,
SAFE_CAST(in_educacao_indigena AS INT64) in_educacao_indigena,
SAFE_CAST(co_lingua_indigena AS INT64) co_lingua_indigena
from basedosdados-dev.br_inep_censo_escolar_staging.escola as t