
# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: br-ibge-ipp

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Índice de Preços ao Produtor

# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Exemplos: br-ibge, br-tse, br-rj-gov
organization: br-ibge

# Descrição do conjunto
notes: Índice de Preços ao Produtor (IPP). Índice Geral para o Brasil, a partir de janeiro/2022.

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups: 
  - economia

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos: fertilidade, preco, desmatamento.
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags: 
  - preco
  - inflacao
  - producao

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified: '2022-04-20T19:47:06.508119'
