/*
Query para publicar a tabela.

Esse é o lugar para:
    - modificar nomes, ordem e tipos de colunas
    - dar join com outras tabelas
    - criar colunas extras (e.g. logs, proporções, etc.)

Qualquer coluna definida aqui deve também existir em `table_config.yaml`.

# Além disso, sinta-se à vontade para alterar alguns nomes obscuros
# para algo um pouco mais explícito.

TIPOS:
    - Para modificar tipos de colunas, basta substituir STRING por outro tipo válido.
    - Exemplo: `SAFE_CAST(column_name AS NUMERIC) column_name`
    - Mais detalhes: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types
*/

CREATE VIEW basedosdados-dev.br_ibge_censo_agropecuario.municipio AS
SELECT 
SAFE_CAST(ano AS INT64) ano,
SAFE_CAST(sigla_uf AS STRING) sigla_uf,
SAFE_CAST(id_municipio AS STRING) id_municipio,
SAFE_CAST(area_total AS FLOAT64) area_total,
SAFE_CAST(area_proprietario AS FLOAT64) area_proprietario,
SAFE_CAST(area_arrendatario AS FLOAT64) area_arrendatario,
SAFE_CAST(area_parceiro AS FLOAT64) area_parceiro,
SAFE_CAST(area_ocupante AS FLOAT64) area_ocupante,
SAFE_CAST(area_lavoura_peramenente AS STRING) area_lavoura_peramenente,
SAFE_CAST(area_lavoura_temporaria AS FLOAT64) area_lavoura_temporaria,
SAFE_CAST(area_pastagem_natural AS FLOAT64) area_pastagem_natural,
SAFE_CAST(area_pastagem_plantada AS FLOAT64) area_pastagem_plantada,
SAFE_CAST(area_pastagem AS FLOAT64) area_pastagem,
SAFE_CAST(area_mata_natural AS FLOAT64) area_mata_natural,
SAFE_CAST(area_mata_plantada AS FLOAT64) area_mata_plantada,
SAFE_CAST(area_sistema_agroflorestal AS FLOAT64) area_sistema_agroflorestal,
SAFE_CAST(area_mata AS FLOAT64) area_mata,
SAFE_CAST(area_nao_utilizada AS FLOAT64) area_nao_utilizada,
SAFE_CAST(quantidade_estabelecimentos AS INT64) quantidade_estabelecimentos,
SAFE_CAST(producao_cafe AS FLOAT64) producao_cafe,
SAFE_CAST(area_cafe AS STRING) area_cafe,
SAFE_CAST(quantidade_estabelecimentos_cafe AS INT64) quantidade_estabelecimentos_cafe,
SAFE_CAST(valor_total_producao_cafe AS FLOAT64) valor_total_producao_cafe,
SAFE_CAST(quantidade_bovinos_total AS INT64) quantidade_bovinos_total,
SAFE_CAST(quantidade_bezerros AS INT64) quantidade_bezerros,
SAFE_CAST(quantidade_bovinos_garrote AS INT64) quantidade_bovinos_garrote,
SAFE_CAST(quantidade_bovinos_vaca AS INT64) quantidade_bovinos_vaca,
SAFE_CAST(quantidade_bovinos_trabalho AS INT64) quantidade_bovinos_trabalho,
SAFE_CAST(quantidade_bovinos_touro AS INT64) quantidade_bovinos_touro,
SAFE_CAST(quantidade_estabelecimentos_energia_eletrica AS INT64) quantidade_estabelecimentos_energia_eletrica,
SAFE_CAST(despesa_total AS FLOAT64) despesa_total,
SAFE_CAST(despesa_adubos AS FLOAT64) despesa_adubos,
SAFE_CAST(despesa_sementes AS FLOAT64) despesa_sementes,
SAFE_CAST(despesa_arrendamentos AS FLOAT64) despesa_arrendamentos,
SAFE_CAST(despesa_salarios AS FLOAT64) despesa_salarios,
SAFE_CAST(despesa_defensivos AS FLOAT64) despesa_defensivos,
SAFE_CAST(despesa_cotas AS FLOAT64) despesa_cotas,
SAFE_CAST(areas_irrigacao AS STRING) areas_irrigacao,
SAFE_CAST(producao_leite AS FLOAT64) producao_leite,
SAFE_CAST(numero_estabelecimentos_total AS INT64) numero_estabelecimentos_total,
SAFE_CAST(numero_estabelecimentos_proprietario AS INT64) numero_estabelecimentos_proprietario,
SAFE_CAST(numero_estabelecimentos_arrendatario AS STRING) numero_estabelecimentos_arrendatario,
SAFE_CAST(numero_estabelecimentos_parceiros AS INT64) numero_estabelecimentos_parceiros,
SAFE_CAST(numero_estabelecimentos_ocupantes AS INT64) numero_estabelecimentos_ocupantes,
SAFE_CAST(numero_estabelecimentos_outros AS INT64) numero_estabelecimentos_outros,
SAFE_CAST(numero_estabelecimentos_nenhuma AS INT64) numero_estabelecimentos_nenhuma,
SAFE_CAST(numero_estabelecimentos_cooperativas AS STRING) numero_estabelecimentos_cooperativas,
SAFE_CAST(numero_estabelecimentos_cooperativas_credito AS INT64) numero_estabelecimentos_cooperativas_credito,
SAFE_CAST(numero_estabelecimentos_cooperativa_energia_eletrica AS INT64) numero_estabelecimentos_cooperativa_energia_eletrica,
SAFE_CAST(numero_estabelecimentos_cooperativa_energia_outras AS INT64) numero_estabelecimentos_cooperativa_energia_outras,
SAFE_CAST(quantidade_tratores AS INT64) quantidade_tratores,
SAFE_CAST(quantidade_maquina_colheita AS INT64) quantidade_maquina_colheita,
SAFE_CAST(quantidade_maquinas_plantio AS STRING) quantidade_maquinas_plantio,
SAFE_CAST(quantidade_tratores_estabelecimentos_menor_10 AS INT64) quantidade_tratores_estabelecimentos_menor_10,
SAFE_CAST(quantidade_tratores_estabelecimentos_maior_10 AS INT64) quantidade_tratores_estabelecimentos_maior_10,
SAFE_CAST(pessoal_ocupado_total AS INT64) pessoal_ocupado_total,
SAFE_CAST(pessoal_ocupado_parentesco_produtor AS INT64) pessoal_ocupado_parentesco_produtor,
SAFE_CAST(pessoal_14_mais_sem_parentesco AS INT64) pessoal_14_mais_sem_parentesco,
SAFE_CAST(pessoal_14_mais_com_parentesco_produtor AS INT64) pessoal_14_mais_com_parentesco_produtor,
SAFE_CAST(pessoal_14_mais_emp AS STRING) pessoal_14_mais_emp,
SAFE_CAST(pessoal_14_mais_ocupado AS INT64) pessoal_14_mais_ocupado,
SAFE_CAST(valor_producao_total AS STRING) valor_producao_total,
SAFE_CAST(valor_producao_total_animal AS STRING) valor_producao_total_animal,
SAFE_CAST(valor_total_producao_animal_grande AS FLOAT64) valor_total_producao_animal_grande,
SAFE_CAST(valor_total_producao_animal_medio AS FLOAT64) valor_total_producao_animal_medio,
SAFE_CAST(valor_total_producao_aves AS FLOAT64) valor_total_producao_aves,
SAFE_CAST(valor_total_producao_vegetal AS FLOAT64) valor_total_producao_vegetal,
SAFE_CAST(valor_total_producao_hortifruti AS FLOAT64) valor_total_producao_hortifruti,
SAFE_CAST(valor_total_producao_silvicultura AS FLOAT64) valor_total_producao_silvicultura,
SAFE_CAST(valor_total_producao_vegicultura AS FLOAT64) valor_total_producao_vegicultura,
SAFE_CAST(valor_total_producao_lavoura_temporaria AS FLOAT64) valor_total_producao_lavoura_temporaria,
SAFE_CAST(valor_total_producao_lavoura_permanente AS FLOAT64) valor_total_producao_lavoura_permanente,
SAFE_CAST(producao_total_arroz AS FLOAT64) producao_total_arroz,
SAFE_CAST(producao_total_feijao AS FLOAT64) producao_total_feijao,
SAFE_CAST(producao_total_milho AS FLOAT64) producao_total_milho,
SAFE_CAST(producao_total_mandioca AS FLOAT64) producao_total_mandioca,
SAFE_CAST(producao_total_soja AS FLOAT64) producao_total_soja,
SAFE_CAST(producao_total_algodao AS FLOAT64) producao_total_algodao,
SAFE_CAST(producao_total_cana AS FLOAT64) producao_total_cana,
SAFE_CAST(producao_total_trigo AS FLOAT64) producao_total_trigo,
SAFE_CAST(area_arroz AS FLOAT64) area_arroz,
SAFE_CAST(area_feijao AS FLOAT64) area_feijao,
SAFE_CAST(area_milho AS FLOAT64) area_milho,
SAFE_CAST(area_mandioca AS FLOAT64) area_mandioca,
SAFE_CAST(area_soja AS FLOAT64) area_soja,
SAFE_CAST(area_algodao AS FLOAT64) area_algodao,
SAFE_CAST(area_cana AS FLOAT64) area_cana,
SAFE_CAST(area_trigo AS FLOAT64) area_trigo,
SAFE_CAST(numero_estabelecimentos_arroz AS INT64) numero_estabelecimentos_arroz,
SAFE_CAST(numero_estabelecimentos_feijao AS INT64) numero_estabelecimentos_feijao,
SAFE_CAST(numero_estabelecimentos_milho AS INT64) numero_estabelecimentos_milho,
SAFE_CAST(numero_estabelecimentos_mandioca AS INT64) numero_estabelecimentos_mandioca,
SAFE_CAST(numero_estabelecimentos_soja AS INT64) numero_estabelecimentos_soja,
SAFE_CAST(numero_estabelecimentos_algodao AS INT64) numero_estabelecimentos_algodao,
SAFE_CAST(numero_estabelecimentos_cana AS INT64) numero_estabelecimentos_cana,
SAFE_CAST(numero_estabelecimentos_trigo AS INT64) numero_estabelecimentos_trigo,
SAFE_CAST(valor_total_arroz AS FLOAT64) valor_total_arroz,
SAFE_CAST(valor_total_feijao AS FLOAT64) valor_total_feijao,
SAFE_CAST(valor_total_milho AS FLOAT64) valor_total_milho,
SAFE_CAST(valor_total_mandioca AS FLOAT64) valor_total_mandioca,
SAFE_CAST(valor_total_soja AS FLOAT64) valor_total_soja,
SAFE_CAST(valor_total_algodao AS FLOAT64) valor_total_algodao,
SAFE_CAST(valor_total_cana AS FLOAT64) valor_total_cana,
SAFE_CAST(valor_total_trigo AS FLOAT64) valor_total_trigo,
SAFE_CAST(valor_total AS FLOAT64) valor_total,
SAFE_CAST(valor_total_terras AS FLOAT64) valor_total_terras,
SAFE_CAST(valor_total_cultura_permanente AS FLOAT64) valor_total_cultura_permanente,
SAFE_CAST(valor_total_matas_plantadas AS FLOAT64) valor_total_matas_plantadas,
SAFE_CAST(valor_total_predios_benfeitorias AS FLOAT64) valor_total_predios_benfeitorias,
SAFE_CAST(valor_total_animais AS FLOAT64) valor_total_animais,
SAFE_CAST(valor_total_animais_transporte AS FLOAT64) valor_total_animais_transporte,
SAFE_CAST(valor_total_maquinas_transporte AS FLOAT64) valor_total_maquinas_transporte,
SAFE_CAST(proporcao_despesa_fertilizante AS FLOAT64) proporcao_despesa_fertilizante,
SAFE_CAST(proporcao_despesa_defensivos AS FLOAT64) proporcao_despesa_defensivos,
SAFE_CAST(proporcao_despesa_sementes AS FLOAT64) proporcao_despesa_sementes,
SAFE_CAST(proporcao_despesa_salarios AS STRING) proporcao_despesa_salarios
FROM basedosdados-dev.br_ibge_censo_agropecuario_staging.municipio AS t