# Where to save all metadata data, such as Dataset and Table config files.
# We reccomend this path to be the same as the github repo clone
metadata_path = ""

# What is the bucket that you are saving all the data? It should be 
# an unique name.
bucket_name = ""

# Where the templates to generate configs and descriptions sit
templates_path =  ""

[gcloud-projects]

    [gcloud-projects.staging]
    name = ""
    credentials_path = ""

    [gcloud-projects.prod]
    name = ""
    credentials_path = ""

# Data about you to auto-fill config
# TODO: issue 20
[user]
name = ""
email = ""
website = ""

[ckan]
url = ""
api_key = ""
