/*
Query para publicar a tabela.

Esse é o lugar para:
    - modificar nomes, ordem e tipos de colunas
    - dar join com outras tabelas
    - criar colunas extras (e.g. logs, proporções, etc.)

Qualquer coluna definida aqui deve também existir em `table_config.yaml`.

# Além disso, sinta-se à vontade para alterar alguns nomes obscuros
# para algo um pouco mais explícito.

TIPOS:
    - Para modificar tipos de colunas, basta substituir FLOAT64 por outro tipo válido.
    - Exemplo: `SAFE_CAST(column_name AS NUMERIC) column_name`
    - Mais detalhes: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types
*/

CREATE VIEW basedosdados-dev.br_fundacao_lemann_projecoes_saeb.uf AS
SELECT 
SAFE_CAST(sigla_uf AS STRING) sigla_uf,
SAFE_CAST(ano AS INT64) ano,
SAFE_CAST(adequado_moderna_lp AS FLOAT64) adequado_moderna_lp,
SAFE_CAST(adequado_moderna_mt AS FLOAT64) adequado_moderna_mt,
SAFE_CAST(insuficiente_lp_publica AS FLOAT64) insuficiente_lp_publica,
SAFE_CAST(insuficiente_mt_publica AS FLOAT64) insuficiente_mt_publica,
SAFE_CAST(basico_lp_publica AS FLOAT64) basico_lp_publica,
SAFE_CAST(basico_mt_publica AS FLOAT64) basico_mt_publica,
SAFE_CAST(proficiente_lp_publica AS FLOAT64) proficiente_lp_publica,
SAFE_CAST(proficiente_mt_publica AS FLOAT64) proficiente_mt_publica,
SAFE_CAST(avancado_lp_publica AS FLOAT64) avancado_lp_publica,
SAFE_CAST(avancado_mt_publica AS FLOAT64) avancado_mt_publica,
SAFE_CAST(adequado_lp_publica AS FLOAT64) adequado_lp_publica,
SAFE_CAST(adequado_mt_publica AS FLOAT64) adequado_mt_publica,
SAFE_CAST(adequado_lp_publica_pretos AS FLOAT64) adequado_lp_publica_pretos,
SAFE_CAST(adequado_mt_publica_pretos AS FLOAT64) adequado_mt_publica_pretos,
SAFE_CAST(adequado_pb_lp_publica AS FLOAT64) adequado_pb_lp_publica,
SAFE_CAST(adequado_pb_mt_publica AS FLOAT64) adequado_pb_mt_publica,
SAFE_CAST(adequado_sp_lp_publica AS FLOAT64) adequado_sp_lp_publica,
SAFE_CAST(adequado_sp_mt_publica AS FLOAT64) adequado_sp_mt_publica,
SAFE_CAST(adequado_pb_lp_publica_pretos AS FLOAT64) adequado_pb_lp_publica_pretos,
SAFE_CAST(adequado_pb_mt_publica_pretos AS FLOAT64) adequado_pb_mt_publica_pretos,
SAFE_CAST(adequado_sp_lp_publica_pretos AS FLOAT64) adequado_sp_lp_publica_pretos,
SAFE_CAST(adequado_sp_mt_publica_pretos AS FLOAT64) adequado_sp_mt_publica_pretos,
SAFE_CAST(ideb AS FLOAT64) ideb,
SAFE_CAST(numero_matriculas_publica AS INT64) numero_matriculas_publica,
SAFE_CAST(porcentagem_nao_declarado_public AS FLOAT64) porcentagem_nao_declarado_public,
SAFE_CAST(porcentagem_branco_publica AS FLOAT64) porcentagem_branco_publica,
SAFE_CAST(porcentagem_preto_publica AS FLOAT64) porcentagem_preto_publica,
SAFE_CAST(porcentagem_pardo_publica AS FLOAT64) porcentagem_pardo_publica,
SAFE_CAST(porcentagem_amarelo_publica AS FLOAT64) porcentagem_amarelo_publica,
SAFE_CAST(porcentagem_indigena_publica AS FLOAT64) porcentagem_indigena_publica,
SAFE_CAST(numero_matriculas_privada AS INT64) numero_matriculas_privada,
SAFE_CAST(porcentagem_nao_declarado_privad AS FLOAT64) porcentagem_nao_declarado_privad,
SAFE_CAST(porcentagem_branco_privada AS FLOAT64) porcentagem_branco_privada,
SAFE_CAST(porcentagem_preto_privada AS FLOAT64) porcentagem_preto_privada,
SAFE_CAST(porcentagem_pardo_privada AS FLOAT64) porcentagem_pardo_privada,
SAFE_CAST(porcentagem_amarelo_privada AS FLOAT64) porcentagem_amarelo_privada,
SAFE_CAST(porcentagem_indigena_privada AS FLOAT64) porcentagem_indigena_privada,
SAFE_CAST(pib_pc AS FLOAT64) pib_pc,
SAFE_CAST(populacao AS INT64) populacao,
SAFE_CAST(familias_beneficiarias_pbf AS INT64) familias_beneficiarias_pbf,
SAFE_CAST(ln_matriculas AS FLOAT64) ln_matriculas,
SAFE_CAST(ln_populacao AS FLOAT64) ln_populacao,
SAFE_CAST(ln_pib_pc AS FLOAT64) ln_pib_pc,
SAFE_CAST(id_uf AS FLOAT64) id_uf,
SAFE_CAST(pib_pc_NA AS FLOAT64) pib_pc_NA,
SAFE_CAST(populacao_NA AS FLOAT64) populacao_NA,
SAFE_CAST(numero_matriculas_publica_NA AS FLOAT64) numero_matriculas_publica_NA,
SAFE_CAST(ln_matriculas_NA AS FLOAT64) ln_matriculas_NA,
SAFE_CAST(ln_populacao_NA AS FLOAT64) ln_populacao_NA,
SAFE_CAST(ln_pib_pc_NA AS FLOAT64) ln_pib_pc_NA,
SAFE_CAST(insuficiente_lp_publica_A AS FLOAT64) insuficiente_lp_publica_A,
SAFE_CAST(insuficiente_lp_publica_BS AS FLOAT64) insuficiente_lp_publica_BS,
SAFE_CAST(insuficiente_lp_publica_WS AS FLOAT64) insuficiente_lp_publica_WS,
SAFE_CAST(basico_lp_publica_A AS FLOAT64) basico_lp_publica_A,
SAFE_CAST(basico_lp_publica_BS AS FLOAT64) basico_lp_publica_BS,
SAFE_CAST(basico_lp_publica_WS AS FLOAT64) basico_lp_publica_WS,
SAFE_CAST(proficiente_lp_publica_A AS FLOAT64) proficiente_lp_publica_A,
SAFE_CAST(proficiente_lp_publica_BS AS FLOAT64) proficiente_lp_publica_BS,
SAFE_CAST(proficiente_lp_publica_WS AS FLOAT64) proficiente_lp_publica_WS,
SAFE_CAST(avancado_lp_publica_A AS FLOAT64) avancado_lp_publica_A,
SAFE_CAST(avancado_lp_publica_BS AS FLOAT64) avancado_lp_publica_BS,
SAFE_CAST(avancado_lp_publica_WS AS FLOAT64) avancado_lp_publica_WS,
SAFE_CAST(insuficiente_mt_publica_A AS FLOAT64) insuficiente_mt_publica_A,
SAFE_CAST(insuficiente_mt_publica_BS AS FLOAT64) insuficiente_mt_publica_BS,
SAFE_CAST(insuficiente_mt_publica_WS AS FLOAT64) insuficiente_mt_publica_WS,
SAFE_CAST(basico_mt_publica_A AS FLOAT64) basico_mt_publica_A,
SAFE_CAST(basico_mt_publica_BS AS FLOAT64) basico_mt_publica_BS,
SAFE_CAST(basico_mt_publica_WS AS FLOAT64) basico_mt_publica_WS,
SAFE_CAST(proficiente_mt_publica_A AS FLOAT64) proficiente_mt_publica_A,
SAFE_CAST(proficiente_mt_publica_BS AS FLOAT64) proficiente_mt_publica_BS,
SAFE_CAST(proficiente_mt_publica_WS AS FLOAT64) proficiente_mt_publica_WS,
SAFE_CAST(avancado_mt_publica_A AS FLOAT64) avancado_mt_publica_A,
SAFE_CAST(avancado_mt_publica_BS AS FLOAT64) avancado_mt_publica_BS,
SAFE_CAST(avancado_mt_publica_WS AS FLOAT64) avancado_mt_publica_WS,
SAFE_CAST(adequado_lp_publica_A AS FLOAT64) adequado_lp_publica_A,
SAFE_CAST(adequado_lp_publica_BS AS FLOAT64) adequado_lp_publica_BS,
SAFE_CAST(adequado_lp_publica_WS AS FLOAT64) adequado_lp_publica_WS,
SAFE_CAST(adequado_lp_publica_pretos_A AS FLOAT64) adequado_lp_publica_pretos_A,
SAFE_CAST(adequado_lp_publica_pretos_BS AS FLOAT64) adequado_lp_publica_pretos_BS,
SAFE_CAST(adequado_lp_publica_pretos_WS AS FLOAT64) adequado_lp_publica_pretos_WS,
SAFE_CAST(adequado_mt_publica_A AS FLOAT64) adequado_mt_publica_A,
SAFE_CAST(adequado_mt_publica_BS AS FLOAT64) adequado_mt_publica_BS,
SAFE_CAST(adequado_mt_publica_WS AS FLOAT64) adequado_mt_publica_WS,
SAFE_CAST(adequado_mt_publica_pretos_A AS FLOAT64) adequado_mt_publica_pretos_A,
SAFE_CAST(adequado_mt_publica_pretos_BS AS FLOAT64) adequado_mt_publica_pretos_BS,
SAFE_CAST(adequado_mt_publica_pretos_WS AS FLOAT64) adequado_mt_publica_pretos_WS,
SAFE_CAST(ideb_A AS FLOAT64) ideb_A,
SAFE_CAST(ideb_BS AS FLOAT64) ideb_BS,
SAFE_CAST(ideb_WS AS FLOAT64) ideb_WS,
SAFE_CAST(adequado_lp_publica_A_pb AS FLOAT64) adequado_lp_publica_A_pb,
SAFE_CAST(adequado_lp_publica_BS_pb AS FLOAT64) adequado_lp_publica_BS_pb,
SAFE_CAST(adequado_lp_publica_WS_pb AS FLOAT64) adequado_lp_publica_WS_pb,
SAFE_CAST(adequado_lp_publica_A_sp AS FLOAT64) adequado_lp_publica_A_sp,
SAFE_CAST(adequado_lp_publica_BS_sp AS FLOAT64) adequado_lp_publica_BS_sp,
SAFE_CAST(adequado_lp_publica_WS_sp AS FLOAT64) adequado_lp_publica_WS_sp,
SAFE_CAST(adequado_lp_publica_pretos_A_pb AS FLOAT64) adequado_lp_publica_pretos_A_pb,
SAFE_CAST(adequado_lp_publica_pretos_BS_pb AS FLOAT64) adequado_lp_publica_pretos_BS_pb,
SAFE_CAST(adequado_lp_publica_pretos_WS_pb AS FLOAT64) adequado_lp_publica_pretos_WS_pb,
SAFE_CAST(adequado_lp_publica_pretos_A_sp AS FLOAT64) adequado_lp_publica_pretos_A_sp,
SAFE_CAST(adequado_lp_publica_pretos_BS_sp AS FLOAT64) adequado_lp_publica_pretos_BS_sp,
SAFE_CAST(adequado_lp_publica_pretos_WS_sp AS FLOAT64) adequado_lp_publica_pretos_WS_sp,
SAFE_CAST(adequado_mt_publica_A_pb AS FLOAT64) adequado_mt_publica_A_pb,
SAFE_CAST(adequado_mt_publica_BS_pb AS FLOAT64) adequado_mt_publica_BS_pb,
SAFE_CAST(adequado_mt_publica_WS_pb AS FLOAT64) adequado_mt_publica_WS_pb,
SAFE_CAST(adequado_mt_publica_A_sp AS FLOAT64) adequado_mt_publica_A_sp,
SAFE_CAST(adequado_mt_publica_BS_sp AS FLOAT64) adequado_mt_publica_BS_sp,
SAFE_CAST(adequado_mt_publica_WS_sp AS FLOAT64) adequado_mt_publica_WS_sp,
SAFE_CAST(adequado_mt_publica_pretos_A_pb AS FLOAT64) adequado_mt_publica_pretos_A_pb,
SAFE_CAST(adequado_mt_publica_pretos_BS_pb AS FLOAT64) adequado_mt_publica_pretos_BS_pb,
SAFE_CAST(adequado_mt_publica_pretos_WS_pb AS FLOAT64) adequado_mt_publica_pretos_WS_pb,
SAFE_CAST(adequado_mt_publica_pretos_A_sp AS FLOAT64) adequado_mt_publica_pretos_A_sp,
SAFE_CAST(adequado_mt_publica_pretos_BS_sp AS FLOAT64) adequado_mt_publica_pretos_BS_sp,
SAFE_CAST(adequado_mt_publica_pretos_WS_sp AS FLOAT64) adequado_mt_publica_pretos_WS_sp
FROM basedosdados-dev.br_fundacao_lemann_projecoes_saeb_staging.uf AS t