
# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: br-sp-alesp

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Dados Abertos da ALESP

# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Exemplos: br-ibge, br-tse, br-rj-gov
organization:
    - br-sp-alesp

# Descrição do conjunto
notes: "O Portal Dados Abertos ALESP é a ferramenta disponibilizada pelo parlamento\
    \ paulista para que todos possam encontrar e utilizar os dados e as informações\
    \ públicas da casa. O portal também tem o objetivo de promover a interlocução\
    \ entre atores da sociedade e os seus representantes para pensar a melhor utilização\
    \ dos dados em prol de uma sociedade melhor.\r\n\r\nO portal tem o objetivo de\
    \ disponibilizar todo e qualquer tipo de dado relativo ao Poder Legislativo do\
    \ Estado de São Paulo. Por exemplo, dados do Processo Legislativo, informações\
    \ sobre os deputados estaduais (contatos, áreas de atuação, bases eleitorais,\
    \ produção legislativa), da prestação de contas dos deputados com os gastos de\
    \ gabinetes, etc. O portal funciona como um grande catálogo que facilita a busca\
    \ e uso de dados produzidos e publicados pela ALESP."

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
    - gov-fin-pub
    - politica

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos: fertilidade, preco, desmatamento.
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
    - burocracia
    - dados abertos
    - despesa
    - legislativo
    - politica publica
    - proposicao

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified: '2022-02-14T01:23:48.216553'
dataset_id: br_sp_alesp
