# Igual ao dataset.name mas como lower case.
# Exemplos: br_ibge_populacao, br_inep_censo_escolar
dataset_id: br_cnpq_bolsas

table_id: microdados

# Título da tabela.
title: Microdados

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description: Dados acerca dos pagamentos efetuados pelo CNPq para projetos de pesquisa

# As máximas unidades espaciais que a tabela cobre.
# Exemplo:
#    - sa.br
#  
#    - sa.br.sp
#  
#    - world
spatial_coverage:
    - sa.br

# Anos cobertos pela tabela.
# Exemplos:
#     - 1995(1)2019
# Caso a cobertura não seja contínua:
#     - 2002(2)2010
#     - 2016
#     - 2020
temporal_coverage:
    - 2002(1)2022

# A unidade temporal com qual a tabela é atualizada.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
update_frequency: one_year

# Nível de observação da tabela: o que representa cada linha.
# A combinação das colunas aqui deve construir uma chave única da tabelaOpções de entity em 'https://basedosdados.org/api/3/action/bd_available_options'
# Caso a entidade seja espacial incluir a informação de 'country' Exemplos:
#     - entity: year
#       columns:
#           - ano
#     - country: br
#       entity: state
#       columns:
#           - sigla_uf
observation_level:
    - entity: year
      columns:
        - ano
    - entity: person
      columns:
      - beneficiario

last_updated:
    metadata: '2022-07-13'
    data: '2022-07-13 08:00:01'
    release: '2022-07-13 08:00:01'

# Versão da tabela. Seguindo o padrão de semantic versioning.
# Exemplos: v1.0, v1.1.3
version: v1.0

# Quem está preenchendo esses metadados?
published_by:
    name: Patrick Teixeira
    email: patrick.teixeira@basedosdados.org
    github_user: tricktx
    ckan_user: patrickteixeira
    website:

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
    name: Patrick Teixeira
    email: patrick.teixeira@basedosdados.org
    github_user: tricktx
    ckan_user: patrickteixeira
    website:

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: Renomeação de Colunas e Ordenamento de Variáveis.

# Url do código de limpeza dos dados do github.
data_cleaning_code_url: https://github.com/basedosdados/mais/tree/master/bases/br_cnpq_bolsas/code

# Organização que ajudou institucionalmente na disponibilização dos dados.
partner_organization:
    name:
    organization_id:

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions:
    - ano

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: ano
      bigquery_type: int64
      description: Ano
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: ano
          column_name: ano
      measurement_unit: year
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: true
    - name: processo
      bigquery_type: string
      description: Numero do processo
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: data_inicio_processo
      bigquery_type: date
      description: Data de início do processo
      temporal_coverage:
          - 2022
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: dia
          column_name: dia
      measurement_unit: day
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: data_fim_processo
      bigquery_type: date
      description: Data de término do processo
      temporal_coverage:
          - 2022
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: dia
          column_name: dia
      measurement_unit: day
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: beneficiario
      bigquery_type: string
      description: Nome do beneficiário
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: yes
      observations:
      is_in_staging: true
      is_partition: false
    - name: titulo_projeto
      bigquery_type: string
      description: Título do projeto da bolsa
      temporal_coverage:
          - 2021(1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: palavra_chave
      bigquery_type: string
      description: Palavras Chave
      temporal_coverage:
          - 2021(1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: linha_fomento
      bigquery_type: string
      description: Linha de Fomento da bolsa
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: modalidade
      bigquery_type: string
      description: Modalidade da bolsa
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: categoria_nivel
      bigquery_type: string
      description: Categoria/Nível
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations: Não conseguimos encontrar o dicionário desta variável. Por favor, entre em contato conosco se tiver informações relevantes.
      is_in_staging: true
      is_partition: false
    - name: chamada
      bigquery_type: string
      description: Nome Chamada
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: programa_cnpq
      bigquery_type: string
      description: Programa CNPq
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: grande_area_conhecimento
      bigquery_type: string
      description: Grande Área do conhecimento
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: area_conhecimento
      bigquery_type: string
      description: Área do conhecimento
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: subarea_conhecimento
      bigquery_type: string
      description: Subárea do conhecimneto
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: pais_origem
      bigquery_type: string
      description: País de origem
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_mundo
          table_id: pais
          column_name: sigla_pais_iso3
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: sigla_uf_origem
      bigquery_type: string
      description: Sigla da Unidade da Federação de origem
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: instituicao_origem
      bigquery_type: string
      description: Nome da Instituição de origem
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: instituicao_ensino_superior
          column_name: nome
      measurement_unit:
      has_sensitive_data: no
      observations: Não necessariamente todas as instituições de origem são brasileiras, mas muitas estão atreladas a projetos originários no Brasil
      is_in_staging: true
      is_partition: false
    - name: pais_destino
      bigquery_type: string
      description: País de destino
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_mundo
          table_id: pais
          column_name: sigla_pais_iso3
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: sigla_uf_destino
      bigquery_type: string
      description: Sigla da Unidade da Federação de destino
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: municipio_destino
      bigquery_type: string
      description: Nome do município de destino
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: sigla_instituicao_destino
      bigquery_type: string
      description: Sigla da Instituição de destino
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: sigla_instituicao_macro
      bigquery_type: string
      description: Sigla da Instituição Macro
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: instituicao_destino
      bigquery_type: string
      description: Instituição de destino
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: nome
          column_name: nome
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: plano_interno
      bigquery_type: string
      description: Plano interno
      temporal_coverage:
          - 2022
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations: Não conseguimos encontrar o dicionário desta variável. Por favor, entre em contato conosco se tiver informações relevantes.
      is_in_staging: true
      is_partition: false
    - name: unidade_orcamentaria
      bigquery_type: string
      description: Unidade Orçamentária do recurso
      temporal_coverage:
          - 2021(1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: fonte_recurso
      bigquery_type: string
      description: Fonte do recurso
      temporal_coverage:
          - 2022
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations: Não conseguimos encontrar o dicionário desta variável. Por favor, entre em contato conosco se tiver informações relevantes.
      is_in_staging: true
      is_partition: false
    - name: natureza_despesa
      bigquery_type: string
      description: Natureza da despesa
      temporal_coverage:
          - 2021(1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations: Não conseguimos encontrar o dicionário desta variável. Por favor, entre em contato conosco se tiver informações relevantes.
      is_in_staging: true
      is_partition: false
    - name: programa_ppa
      bigquery_type: string
      description: Programa Plano Plurianual
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations: Não conseguimos encontrar o dicionário desta variável. Por favor, entre em contato conosco se tiver informações relevantes.
      is_in_staging: true
      is_partition: false
    - name: acao_ppa
      bigquery_type: string
      description: Ação Plano Plurianual
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations: Não conseguimos encontrar o dicionário desta variável. Por favor, entre em contato conosco se tiver informações relevantes.
      is_in_staging: true
      is_partition: false
    - name: valor
      bigquery_type: float64
      description: Valor pago da bolsa
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false

number_rows: 2774218

metadata_modified:
