
# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: br-ibge-pnadc

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Pesquisa Nacional por Amostra de Domicílios Contínua (PNAD-C)

# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Exemplos: br-ibge, br-tse, br-rj-gov
organization:
    - br-ibge

# Descrição do conjunto
notes: 'A Pesquisa Nacional por Amostra de Domicílios Contínua, PNAD Contínua, é uma
    pesquisa realizada pelo IBGE com o objetivo de produzir continuamente informações
    sobre mercado de trabalho, associadas a características demográficas e educacionais.
    Periodicamente, são analisados temas adicionais permanentes, como trabalho infantil
    e outras formas de trabalho, fecundidade e migração, e suplementares, selecionados
    segundo necessidade, relativos ao desenvolvimento socioeconômico do país.A pesquisa
    fornece informações mensais para um conjunto restrito de indicadores relativos
    à força de trabalho, trimestral para os indicadores de força de trabalho, anual
    para temas permanentes e adicionais sobre força e trabalho e variável para temas
    suplementares. As informações mensais são representativas apenas em nível nacional
    e as demais têm representatividade para os níveis geográficos: Brasil, Grandes
    Regiões, Unidades da Federação, 20 Regiões Metropolitanas que contêm Municípios
    das Capitais, Municípios das Capitais e Região Integrada de Desenvolvimento da
    Grande Teresina. A cada trimestre, são investigados cerca de 211.000 domicílios
    inseridos em aproximadamente 16.000 setores censitários de 3.500 municípios.'

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
    - economia
    - educacao
    - populacao
    - saude

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos: fertilidade, preco, desmatamento.
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
    - emprego
    - informalidade
    - ocupacao
    - trabalho

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified: '2022-02-14T01:23:50.300096'
