
# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: br-inmet-bdmep

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Banco de Dados Meteorológicos (BDMEP)

# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Se a organização não estiver na lista acima ou o nome não estiver conforme o manual de estilo
# criar ou renomear a organização em https://basedosdados.org/organization/
# Exemplos: br-ibge, br-tse, br-rj-gov
organization:
    - instituto-nacional-de-meteorologia-inmet

# Descrição do conjunto
notes: "O BDMEP abriga dados meteorológicos diários em forma digital, de séries históricas\
    \ das várias estações meteorológicas convencionais da rede de estações do INMET\
    \ com milhões de informações, referentes às medições diárias, de acordo com as\
    \ normas técnicas internacionais da Organização Meteorológica Mundial.\n"

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
    - meio-ambiente

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos:
#    - fertilidade
#    - preco
#    - desmatamento
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
    - clima
    - radiação
    - temperatura
    - umidade

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified: '2022-12-20T18:47:40.263178'
