/*

Query para publicar a tabela.

Esse é o lugar para:
    - modificar nomes, ordem e tipos de colunas
    - dar join com outras tabelas
    - criar colunas extras (e.g. logs, proporções, etc.)

Qualquer coluna definida aqui deve também existir em `table_config.yaml`.

# Além disso, sinta-se à vontade para alterar alguns nomes obscuros
# para algo um pouco mais explícito.

TIPOS:
    - Para modificar tipos de colunas, basta substituir STRING por outro tipo válido.
    - Exemplo: `SAFE_CAST(column_name AS NUMERIC) column_name`
    - Mais detalhes: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types

*/

CREATE VIEW basedosdados-dev.br_inep_censo_escolar.docente AS
SELECT 
SAFE_CAST(ano AS INT64) ano,
SAFE_CAST(sigla_uf AS STRING) sigla_uf,
SAFE_CAST(id_municipio AS STRING) id_municipio,
SAFE_CAST(id_escola AS STRING) id_escola,
SAFE_CAST(rede AS STRING) rede,
SAFE_CAST(id_docente AS STRING) id_docente,
SAFE_CAST(mes_nascimento_docente AS STRING) mes_nascimento_docente,
SAFE_CAST(ano_nascimento_docente AS INT64) ano_nascimento_docente,
SAFE_CAST(dia_nascimento_docente AS INT64) dia_nascimento_docente,
SAFE_CAST(idade AS INT64) idade,
SAFE_CAST(idade_referencia AS INT64) idade_referencia,
SAFE_CAST(sexo AS INT64) sexo,
SAFE_CAST(cor_raca AS INT64) cor_raca,
SAFE_CAST(nacionalidade AS STRING) nacionalidade,
SAFE_CAST(id_pais_origem AS STRING) id_pais_origem,
SAFE_CAST(id_uf_nascimento AS STRING) id_uf_nascimento,
SAFE_CAST(id_municipio_nascimento AS STRING) id_municipio_nascimento,
SAFE_CAST(id_uf_endereco AS STRING) id_uf_endereco,
SAFE_CAST(id_municipio_endereco AS STRING) id_municipio_endereco,
SAFE_CAST(zona_residencial AS INT64) zona_residencial,
SAFE_CAST(necessidade_especial AS INT64) necessidade_especial,
SAFE_CAST(cegueira AS INT64) cegueira,
SAFE_CAST(baixa_visao AS INT64) baixa_visao,
SAFE_CAST(surdez AS INT64) surdez,
SAFE_CAST(deficiencia_auditiva AS INT64) deficiencia_auditiva,
SAFE_CAST(surdocegueira AS INT64) surdocegueira,
SAFE_CAST(deficiencia_fisica AS INT64) deficiencia_fisica,
SAFE_CAST(deficiencia_intelectual AS INT64) deficiencia_intelectual,
SAFE_CAST(deficiencia_multipla AS INT64) deficiencia_multipla,
SAFE_CAST(escolaridade AS STRING) escolaridade,
SAFE_CAST(situacao_curso_1 AS STRING) situacao_curso_1,
SAFE_CAST(id_area_curso_1 AS STRING) id_area_curso_1,
SAFE_CAST(id_curso_1 AS STRING) id_curso_1,
SAFE_CAST(licenciatura_1 AS STRING) licenciatura_1,
SAFE_CAST(formacao_pedagogica_comp_1 AS STRING) formacao_pedagogica_comp_1,
SAFE_CAST(ano_inicio_curso_superior_1 AS STRING) ano_inicio_curso_superior_1,
SAFE_CAST(ano_conclusao_curso_superior_1 AS STRING) ano_conclusao_curso_superior_1,
SAFE_CAST(tipo_ies_1 AS STRING) tipo_ies_1,
SAFE_CAST(id_ies_1 AS STRING) id_ies_1,
SAFE_CAST(situacao_curso_2 AS STRING) situacao_curso_2,
SAFE_CAST(id_area_curso_2 AS STRING) id_area_curso_2,
SAFE_CAST(id_curso_2 AS STRING) id_curso_2,
SAFE_CAST(licenciatura_2 AS STRING) licenciatura_2,
SAFE_CAST(formacao_pedagogica_comp_2 AS STRING) formacao_pedagogica_comp_2,
SAFE_CAST(ano_inicio_curso_superior_2 AS STRING) ano_inicio_curso_superior_2,
SAFE_CAST(ano_conclusao_curso_superior_2 AS STRING) ano_conclusao_curso_superior_2,
SAFE_CAST(tipo_ies_2 AS STRING) tipo_ies_2,
SAFE_CAST(id_ies_2 AS STRING) id_ies_2,
SAFE_CAST(situacao_curso_3 AS STRING) situacao_curso_3,
SAFE_CAST(id_area_curso_3 AS STRING) id_area_curso_3,
SAFE_CAST(id_curso_3 AS STRING) id_curso_3,
SAFE_CAST(licenciatura_3 AS STRING) licenciatura_3,
SAFE_CAST(formacao_pedagogica_comp_3 AS STRING) formacao_pedagogica_comp_3,
SAFE_CAST(ano_inicio_curso_superior_3 AS STRING) ano_inicio_curso_superior_3,
SAFE_CAST(ano_conclusao_curso_superior_3 AS STRING) ano_conclusao_curso_superior_3,
SAFE_CAST(tipo_ies_3 AS STRING) tipo_ies_3,
SAFE_CAST(id_ies_3 AS STRING) id_ies_3,
SAFE_CAST(disciplina_quimica AS INT64) disciplina_quimica,
SAFE_CAST(disciplina_fisica AS INT64) disciplina_fisica,
SAFE_CAST(disciplina_matematica AS INT64) disciplina_matematica,
SAFE_CAST(disciplina_biologia AS INT64) disciplina_biologia,
SAFE_CAST(disciplina_ciencias AS INT64) disciplina_ciencias,
SAFE_CAST(disciplina_lingua_portuguesa AS INT64) disciplina_lingua_portuguesa,
SAFE_CAST(disciplina_lingua_ingles AS INT64) disciplina_lingua_ingles,
SAFE_CAST(disciplina_lingua_espanhol AS INT64) disciplina_lingua_espanhol,
SAFE_CAST(disciplina_lingua_frances AS INT64) disciplina_lingua_frances,
SAFE_CAST(disciplina_lingua_outra AS INT64) disciplina_lingua_outra,
SAFE_CAST(disciplina_lingua_indigena AS INT64) disciplina_lingua_indigena,
SAFE_CAST(disciplina_artes AS INT64) disciplina_artes,
SAFE_CAST(disciplina_educacao_fisica AS INT64) disciplina_educacao_fisica,
SAFE_CAST(disciplina_historia AS INT64) disciplina_historia,
SAFE_CAST(disciplina_geografia AS INT64) disciplina_geografia,
SAFE_CAST(disciplina_filosofia AS INT64) disciplina_filosofia,
SAFE_CAST(disciplina_ensino_religioso AS INT64) disciplina_ensino_religioso,
SAFE_CAST(disciplina_estudos_sociais AS INT64) disciplina_estudos_sociais,
SAFE_CAST(disciplina_sociologia AS INT64) disciplina_sociologia,
SAFE_CAST(disciplina_informatica_comp AS INT64) disciplina_informatica_comp,
SAFE_CAST(disciplina_profissionalizante AS INT64) disciplina_profissionalizante,
SAFE_CAST(disciplina_atend_especiais AS INT64) disciplina_atend_especiais,
SAFE_CAST(disciplina_diver_socio_cultural AS INT64) disciplina_diver_socio_cultural,
SAFE_CAST(disciplina_libras AS INT64) disciplina_libras,
SAFE_CAST(disciplina_pedagogicas AS INT64) disciplina_pedagogicas,
SAFE_CAST(disciplina_outras AS INT64) disciplina_outras,
SAFE_CAST(especializacao AS INT64) especializacao,
SAFE_CAST(mestrado AS INT64) mestrado,
SAFE_CAST(doutorado AS INT64) doutorado,
SAFE_CAST(pos_nenhum AS INT64) pos_nenhum,
SAFE_CAST(formacao_especif_creche AS INT64) formacao_especif_creche,
SAFE_CAST(formacao_especif_pre_escola AS INT64) formacao_especif_pre_escola,
SAFE_CAST(formacao_especif_anos_iniciais AS INT64) formacao_especif_anos_iniciais,
SAFE_CAST(formacao_especif_anos_finais AS INT64) formacao_especif_anos_finais,
SAFE_CAST(formacao_especif_ens_medio AS INT64) formacao_especif_ens_medio,
SAFE_CAST(formacao_especif_eja AS INT64) formacao_especif_eja,
SAFE_CAST(formacao_especif_ed_especial AS INT64) formacao_especif_ed_especial,
SAFE_CAST(formacao_especif_ed_indigena AS INT64) formacao_especif_ed_indigena,
SAFE_CAST(formacao_especif_campo AS INT64) formacao_especif_campo,
SAFE_CAST(formacao_especif_ambiental AS INT64) formacao_especif_ambiental,
SAFE_CAST(formacao_especif_dir_humanos AS INT64) formacao_especif_dir_humanos,
SAFE_CAST(formacao_especif_div_sexual AS INT64) formacao_especif_div_sexual,
SAFE_CAST(formacao_especif_dir_adolesc AS INT64) formacao_especif_dir_adolesc,
SAFE_CAST(formacao_especif_afro AS INT64) formacao_especif_afro,
SAFE_CAST(formacao_especif_outros AS INT64) formacao_especif_outros,
SAFE_CAST(formacao_especif_nenhum AS INT64) formacao_especif_nenhum,
SAFE_CAST(tipo_docente AS INT64) tipo_docente,
SAFE_CAST(tipo_contratacao AS STRING) tipo_contratacao,
SAFE_CAST(id_turma AS STRING) id_turma,
SAFE_CAST(tipo_turma AS STRING) tipo_turma,
SAFE_CAST(mediacao_didatico_pedago AS INT64) mediacao_didatico_pedago,
SAFE_CAST(especial_exclusiva AS INT64) especial_exclusiva,
SAFE_CAST(regular AS INT64) regular,
SAFE_CAST(eja AS INT64) eja,
SAFE_CAST(profissionalizante AS INT64) profissionalizante,
SAFE_CAST(etapa_ensino AS STRING) etapa_ensino,
SAFE_CAST(id_curso_educ_profissional AS STRING) id_curso_educ_profissional,
SAFE_CAST(localizacao AS STRING) localizacao,
SAFE_CAST(categoria_escola_privada AS STRING) categoria_escola_privada,
SAFE_CAST(conveniada_pp AS INT64) conveniada_pp,
SAFE_CAST(convenio_poder_publico AS INT64) convenio_poder_publico,
SAFE_CAST(mant_escola_privada_emp AS INT64) mant_escola_privada_emp,
SAFE_CAST(mant_escola_privada_ong AS INT64) mant_escola_privada_ong,
SAFE_CAST(mant_escola_privada_sind AS INT64) mant_escola_privada_sind,
SAFE_CAST(mant_escola_privada_sist_s AS INT64) mant_escola_privada_sist_s,
SAFE_CAST(mant_escola_privada_s_fins AS INT64) mant_escola_privada_s_fins,
SAFE_CAST(regulamentacao AS STRING) regulamentacao,
SAFE_CAST(localizacao_diferenciada AS INT64) localizacao_diferenciada,
SAFE_CAST(educacao_indigena AS INT64) educacao_indigena,

from basedosdados-dev.br_inep_censo_escolar_staging.docente as t