
# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Exemplos: br-ibge, br-tse, br-rj-gov
organization: br-inep

dataset_id: br_inep_indicador_nivel_socioeconomico

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Indicador Nível Socioeconômico (INSE)
 
# Descrição e anotações úteis sobre os dados.
description: O  Indicador de Nível Socioeconômico (INSE)  trata-se de uma medida cujo objetivo é situar o conjunto dos alunos atendidos por cada escola em um estrato, definido pela posse de bens domésticos, renda e contratação de serviços pela família dos alunos e pelo nível de escolaridade de seus pais.

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
    - economia
    - educacao

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos: fertilidade, preco, desmatamento.
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
    - nivel socioeconomico

# Url completa do CKAN já contendo o dataset-id
# Exemplo: https://basedosdados.org/dataset/<dataset-id>
ckan_url: https://basedosdados.org/dataset/br-inep-indicador-nivel-socioeconomico

# Url completa do Github já contendo o dataset_id
# Exemplo: https://github.com/basedosdados/mais/tree/master/bases/<dataset_id>
github_url: https://basedosdados.org/dataset/br_inep_indicador_nivel_socioeconomico

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified:
