# Igual ao dataset.name mas como lower case.
# Exemplos: br_ibge_populacao, br_inep_censo_escolar
dataset_id: br_rj_tce_iegm

table_id: indicadores

# Título da tabela.
title: Indicadores

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description: O Índice de Efetividade da Gestão Municipal (IEGM) é composto por uma avaliação realizada em sete indicadores envolvendo boas práticas nas temáticas de educação, saúde, planejamento, gestão fiscal, meio ambiente, proteção das cidades e governança da tecnologia da informação.

# As máximas unidades espaciais que a tabela cobre.
# Exemplo:
#    - sa.br
#  
#    - sa.br.sp
#  
#    - world
spatial_coverage:
    - sa.br.rj

# Anos cobertos pela tabela.
# Exemplos:
#     - 1995(1)2019
# Caso a cobertura não seja contínua:
#     - 2002(2)2010
#     - 2016
#     - 2020
temporal_coverage:
    - 2019

# A unidade temporal com qual a tabela é atualizada.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
update_frequency: unique

# Nível de observação da tabela: o que representa cada linha.
# A combinação das colunas aqui deve construir uma chave única da tabelaOpções de entity em 'https://basedosdados.org/api/3/action/bd_available_options'
# Caso a entidade seja espacial incluir a informação de 'country' Exemplos:
#     - entity: year
#       columns:
#           - ano
#     - country: br
#       entity: state
#       columns:
#           - sigla_uf
observation_level:
    - country: br    
      entity: municipality
      columns:
        - id_municipio

last_updated:
    metadata: '2023-01-04'
    data: '2023-01-04 17:10:13'
    release: '2023-01-04 17:10:33'

# Versão da tabela. Seguindo o padrão de semantic versioning.
# Exemplos: v1.0, v1.1.3
version: v1.0

# Quem está preenchendo esses metadados?
published_by:
    name: Gabrielle Carvalho
    email: gabrielle.carvalho@basedosdados.org
    github_user: gabrielle-carv
    ckan_user: gabs_carvalho
    website:

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
    name: Gabrielle Carvalho
    email: gabrielle.carvalho@basedosdados.org
    github_user: gabrielle-carv
    ckan_user: gabs_carvalho
    website:

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: Padronização das variáveis pelas normas da BD.

# Url do código de limpeza dos dados do github.
data_cleaning_code_url: https://github.com/basedosdados/mais/tree/master/bases/br_rj_tce_iegm/code

# Organização que ajudou institucionalmente na disponibilização dos dados.
partner_organization:
    name:
    organization_id:

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions:

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: ano
      bigquery_type: int64
      description: Ano
      temporal_coverage:
          - 2019
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: ano
          column_name: ano
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true 
      is_partition: false
    - name: sigla_uf
      bigquery_type: string
      description: Sigla da Unidade da Federação
      temporal_coverage:
          - 2019
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: uf
          column_name: sigla
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: id_municipio
      bigquery_type: string
      description: ID Município - IBGE 7 Dígitos
      temporal_coverage:
          - 2019
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: municipio
          column_name: id_municipio
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: categoria
      bigquery_type: string
      description: Categoria em que o Município foi classificado a partir da nota
          final do Índice de Efetividade da Gestão Municipal (IEGM)
      temporal_coverage:
          - 2019
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: meio_ambiente
      bigquery_type: float64
      description: Nota do indicador - Meio ambiente
      temporal_coverage:
          - 2019
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: protecao_cidade
      bigquery_type: float64
      description: Nota do indicador - Proteção das cidades
      temporal_coverage:
          - 2019
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: educacao
      bigquery_type: float64
      description: Nota do indicador - Educação
      temporal_coverage:
          - 2019
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: gestao_fiscal
      bigquery_type: float64
      description: Nota do indicador - Gestão Fiscal
      temporal_coverage:
          - 2019
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: governanca_ti
      bigquery_type: float64
      description: Nota do indicador - Governança da tecnologia da informação
      temporal_coverage:
          - 2019
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: planejamento
      bigquery_type: float64
      description: Nota do indicador - Planejamento
      temporal_coverage:
          - 2019
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: saude
      bigquery_type: float64
      description: Nota do indicador - Saúde
      temporal_coverage:
          - 2019
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: nota_final
      bigquery_type: float64
      description: Nota final do Índice de Efetividade da Gestão Municipal (IEGM)
      temporal_coverage:
          - 2019
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false

number_rows: 91

metadata_modified:
