/*

Query para publicar a tabela.

Esse é o lugar para:
    - modificar nomes, ordem e tipos de colunas
    - dar join com outras tabelas
    - criar colunas extras (e.g. logs, proporções, etc.)

Qualquer coluna definida aqui deve também existir em `table_config.yaml`.

# Além disso, sinta-se à vontade para alterar alguns nomes obscuros
# para algo um pouco mais explícito.

TIPOS:
    - Para modificar tipos de colunas, basta substituir STRING por outro tipo válido.
    - Exemplo: `SAFE_CAST(column_name AS NUMERIC) column_name`
    - Mais detalhes: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types

*/

CREATE VIEW basedosdados-dev.br_inep_saeb.aluno_ef_1995_2005 AS
SELECT 
SAFE_CAST(ano AS INT64) ano,
SAFE_CAST(mascara AS STRING) mascara,
SAFE_CAST(serie AS STRING) serie,
SAFE_CAST(disciplina AS STRING) disciplina,
SAFE_CAST(turma AS STRING) turma,
SAFE_CAST(id_aluno AS STRING) id_aluno,
SAFE_CAST(estrato AS STRING) estrato,
SAFE_CAST(rede AS STRING) rede,
SAFE_CAST(localizacao AS STRING) localizacao,
SAFE_CAST(sigla_uf AS STRING) sigla_uf,
SAFE_CAST(peso_aluno_turma AS FLOAT64) peso_aluno_turma,
SAFE_CAST(peso_aluno_disciplina AS FLOAT64) peso_aluno_disciplina,
SAFE_CAST(peso_turma AS FLOAT64) peso_turma,
SAFE_CAST(peso_escola AS FLOAT64) peso_escola,
SAFE_CAST(caderno AS STRING) caderno,
SAFE_CAST(bloco_1 AS STRING) bloco_1,
SAFE_CAST(bloco_2 AS STRING) bloco_2,
SAFE_CAST(bloco_3 AS STRING) bloco_3,
SAFE_CAST(resposta_bloco_1_q001 AS STRING) resposta_bloco_1_q001,
SAFE_CAST(resposta_bloco_1_q002 AS STRING) resposta_bloco_1_q002,
SAFE_CAST(resposta_bloco_1_q003 AS STRING) resposta_bloco_1_q003,
SAFE_CAST(resposta_bloco_1_q004 AS STRING) resposta_bloco_1_q004,
SAFE_CAST(resposta_bloco_1_q005 AS STRING) resposta_bloco_1_q005,
SAFE_CAST(resposta_bloco_1_q006 AS STRING) resposta_bloco_1_q006,
SAFE_CAST(resposta_bloco_1_q007 AS STRING) resposta_bloco_1_q007,
SAFE_CAST(resposta_bloco_1_q008 AS STRING) resposta_bloco_1_q008,
SAFE_CAST(resposta_bloco_1_q009 AS STRING) resposta_bloco_1_q009,
SAFE_CAST(resposta_bloco_1_q010 AS STRING) resposta_bloco_1_q010,
SAFE_CAST(resposta_bloco_1_q011 AS STRING) resposta_bloco_1_q011,
SAFE_CAST(resposta_bloco_1_q012 AS STRING) resposta_bloco_1_q012,
SAFE_CAST(resposta_bloco_1_q013 AS STRING) resposta_bloco_1_q013,
SAFE_CAST(resposta_bloco_2_q001 AS STRING) resposta_bloco_2_q001,
SAFE_CAST(resposta_bloco_2_q002 AS STRING) resposta_bloco_2_q002,
SAFE_CAST(resposta_bloco_2_q003 AS STRING) resposta_bloco_2_q003,
SAFE_CAST(resposta_bloco_2_q004 AS STRING) resposta_bloco_2_q004,
SAFE_CAST(resposta_bloco_2_q005 AS STRING) resposta_bloco_2_q005,
SAFE_CAST(resposta_bloco_2_q006 AS STRING) resposta_bloco_2_q006,
SAFE_CAST(resposta_bloco_2_q007 AS STRING) resposta_bloco_2_q007,
SAFE_CAST(resposta_bloco_2_q008 AS STRING) resposta_bloco_2_q008,
SAFE_CAST(resposta_bloco_2_q009 AS STRING) resposta_bloco_2_q009,
SAFE_CAST(resposta_bloco_2_q010 AS STRING) resposta_bloco_2_q010,
SAFE_CAST(resposta_bloco_2_q011 AS STRING) resposta_bloco_2_q011,
SAFE_CAST(resposta_bloco_2_q012 AS STRING) resposta_bloco_2_q012,
SAFE_CAST(resposta_bloco_2_q013 AS STRING) resposta_bloco_2_q013,
SAFE_CAST(resposta_bloco_3_q001 AS STRING) resposta_bloco_3_q001,
SAFE_CAST(resposta_bloco_3_q002 AS STRING) resposta_bloco_3_q002,
SAFE_CAST(resposta_bloco_3_q003 AS STRING) resposta_bloco_3_q003,
SAFE_CAST(resposta_bloco_3_q004 AS STRING) resposta_bloco_3_q004,
SAFE_CAST(resposta_bloco_3_q005 AS STRING) resposta_bloco_3_q005,
SAFE_CAST(resposta_bloco_3_q006 AS STRING) resposta_bloco_3_q006,
SAFE_CAST(resposta_bloco_3_q007 AS STRING) resposta_bloco_3_q007,
SAFE_CAST(resposta_bloco_3_q008 AS STRING) resposta_bloco_3_q008,
SAFE_CAST(resposta_bloco_3_q009 AS STRING) resposta_bloco_3_q009,
SAFE_CAST(resposta_bloco_3_q010 AS STRING) resposta_bloco_3_q010,
SAFE_CAST(resposta_bloco_3_q011 AS STRING) resposta_bloco_3_q011,
SAFE_CAST(resposta_bloco_3_q012 AS STRING) resposta_bloco_3_q012,
SAFE_CAST(resposta_bloco_3_q013 AS STRING) resposta_bloco_3_q013,
SAFE_CAST(gabarito_bloco_1 AS STRING) gabarito_bloco_1,
SAFE_CAST(gabarito_bloco_2 AS STRING) gabarito_bloco_2,
SAFE_CAST(gabarito_bloco_3 AS STRING) gabarito_bloco_3,
SAFE_CAST(proficiencia_250 AS FLOAT64) proficiencia_250,
SAFE_CAST(proficiencia_saeb AS FLOAT64) proficiencia_saeb,
SAFE_CAST(taxa_resposta_q001 AS STRING) taxa_resposta_q001,
SAFE_CAST(taxa_resposta_q002 AS STRING) taxa_resposta_q002,
SAFE_CAST(taxa_resposta_q003 AS STRING) taxa_resposta_q003,
SAFE_CAST(taxa_resposta_q004 AS STRING) taxa_resposta_q004,
SAFE_CAST(taxa_resposta_q005 AS STRING) taxa_resposta_q005,
SAFE_CAST(taxa_resposta_q006 AS STRING) taxa_resposta_q006,
SAFE_CAST(taxa_resposta_q007 AS STRING) taxa_resposta_q007,
SAFE_CAST(taxa_resposta_q008 AS STRING) taxa_resposta_q008,
SAFE_CAST(taxa_resposta_q009 AS STRING) taxa_resposta_q009,
SAFE_CAST(taxa_resposta_q010 AS STRING) taxa_resposta_q010,
SAFE_CAST(taxa_resposta_q011 AS STRING) taxa_resposta_q011,
SAFE_CAST(taxa_resposta_q012 AS STRING) taxa_resposta_q012,
SAFE_CAST(taxa_resposta_q013 AS STRING) taxa_resposta_q013,
SAFE_CAST(taxa_resposta_q014 AS STRING) taxa_resposta_q014,
SAFE_CAST(taxa_resposta_q015 AS STRING) taxa_resposta_q015,
SAFE_CAST(taxa_resposta_q016 AS STRING) taxa_resposta_q016,
SAFE_CAST(taxa_resposta_q017 AS STRING) taxa_resposta_q017,
SAFE_CAST(taxa_resposta_q018 AS STRING) taxa_resposta_q018,
SAFE_CAST(taxa_resposta_q019 AS STRING) taxa_resposta_q019,
SAFE_CAST(taxa_resposta_q020 AS STRING) taxa_resposta_q020,
SAFE_CAST(taxa_resposta_q021 AS STRING) taxa_resposta_q021,
SAFE_CAST(taxa_resposta_q022 AS STRING) taxa_resposta_q022,
SAFE_CAST(taxa_resposta_q023 AS STRING) taxa_resposta_q023,
SAFE_CAST(taxa_resposta_q024 AS STRING) taxa_resposta_q024,
SAFE_CAST(taxa_resposta_q025 AS STRING) taxa_resposta_q025,
SAFE_CAST(taxa_resposta_q026 AS STRING) taxa_resposta_q026,
SAFE_CAST(taxa_resposta_q027 AS STRING) taxa_resposta_q027,
SAFE_CAST(taxa_resposta_q028 AS STRING) taxa_resposta_q028,
SAFE_CAST(taxa_resposta_q029 AS STRING) taxa_resposta_q029,
SAFE_CAST(taxa_resposta_q030 AS STRING) taxa_resposta_q030,
SAFE_CAST(taxa_resposta_q031 AS STRING) taxa_resposta_q031,
SAFE_CAST(taxa_resposta_q032 AS STRING) taxa_resposta_q032,
SAFE_CAST(taxa_resposta_q033 AS STRING) taxa_resposta_q033,
SAFE_CAST(taxa_resposta_q034 AS STRING) taxa_resposta_q034,
SAFE_CAST(taxa_resposta_q035 AS STRING) taxa_resposta_q035,
SAFE_CAST(taxa_resposta_q036 AS STRING) taxa_resposta_q036,
SAFE_CAST(taxa_resposta_q037 AS STRING) taxa_resposta_q037,
SAFE_CAST(taxa_resposta_q038 AS STRING) taxa_resposta_q038,
SAFE_CAST(taxa_resposta_q039 AS STRING) taxa_resposta_q039,
SAFE_CAST(taxa_resposta_q040 AS STRING) taxa_resposta_q040,
SAFE_CAST(taxa_resposta_q041 AS STRING) taxa_resposta_q041,
SAFE_CAST(taxa_resposta_q042 AS STRING) taxa_resposta_q042,
SAFE_CAST(taxa_resposta_q043 AS STRING) taxa_resposta_q043,
SAFE_CAST(taxa_resposta_q044 AS STRING) taxa_resposta_q044,
SAFE_CAST(taxa_resposta_q045 AS STRING) taxa_resposta_q045,
SAFE_CAST(taxa_resposta_q046 AS STRING) taxa_resposta_q046,
SAFE_CAST(taxa_resposta_q047 AS STRING) taxa_resposta_q047,
SAFE_CAST(taxa_resposta_q048 AS STRING) taxa_resposta_q048,
SAFE_CAST(taxa_resposta_q049 AS STRING) taxa_resposta_q049,
SAFE_CAST(taxa_resposta_q050 AS STRING) taxa_resposta_q050,
SAFE_CAST(taxa_resposta_q051 AS STRING) taxa_resposta_q051,
SAFE_CAST(taxa_resposta_q052 AS STRING) taxa_resposta_q052,
SAFE_CAST(taxa_resposta_q053 AS STRING) taxa_resposta_q053,
SAFE_CAST(taxa_resposta_q054 AS STRING) taxa_resposta_q054,
SAFE_CAST(taxa_resposta_q055 AS STRING) taxa_resposta_q055,
SAFE_CAST(taxa_resposta_q056 AS STRING) taxa_resposta_q056,
SAFE_CAST(taxa_resposta_q057 AS STRING) taxa_resposta_q057,
SAFE_CAST(taxa_resposta_q058 AS STRING) taxa_resposta_q058,
SAFE_CAST(taxa_resposta_q059 AS STRING) taxa_resposta_q059,
SAFE_CAST(taxa_resposta_q060 AS STRING) taxa_resposta_q060,
SAFE_CAST(taxa_resposta_q061 AS STRING) taxa_resposta_q061,
SAFE_CAST(taxa_resposta_q062 AS STRING) taxa_resposta_q062,
SAFE_CAST(taxa_resposta_q063 AS STRING) taxa_resposta_q063,
SAFE_CAST(taxa_resposta_q064 AS STRING) taxa_resposta_q064,
SAFE_CAST(taxa_resposta_q065 AS STRING) taxa_resposta_q065,
SAFE_CAST(taxa_resposta_q066 AS STRING) taxa_resposta_q066,
SAFE_CAST(taxa_resposta_q067 AS STRING) taxa_resposta_q067,
SAFE_CAST(taxa_resposta_q068 AS STRING) taxa_resposta_q068,
SAFE_CAST(taxa_resposta_q069 AS STRING) taxa_resposta_q069,
SAFE_CAST(taxa_resposta_q070 AS STRING) taxa_resposta_q070,
SAFE_CAST(taxa_resposta_q071 AS STRING) taxa_resposta_q071,
SAFE_CAST(taxa_resposta_q072 AS STRING) taxa_resposta_q072,
SAFE_CAST(taxa_resposta_q073 AS STRING) taxa_resposta_q073,
SAFE_CAST(taxa_resposta_q074 AS STRING) taxa_resposta_q074,
SAFE_CAST(taxa_resposta_q075 AS STRING) taxa_resposta_q075,
SAFE_CAST(taxa_resposta_q076 AS STRING) taxa_resposta_q076,
SAFE_CAST(taxa_resposta_q077 AS STRING) taxa_resposta_q077,
SAFE_CAST(taxa_resposta_q078 AS STRING) taxa_resposta_q078,
SAFE_CAST(taxa_resposta_q079 AS STRING) taxa_resposta_q079,
SAFE_CAST(taxa_resposta_q080 AS STRING) taxa_resposta_q080,
SAFE_CAST(taxa_resposta_q081 AS STRING) taxa_resposta_q081,
SAFE_CAST(taxa_resposta_q082 AS STRING) taxa_resposta_q082,
SAFE_CAST(taxa_resposta_q083 AS STRING) taxa_resposta_q083,
SAFE_CAST(taxa_resposta_q084 AS STRING) taxa_resposta_q084,
SAFE_CAST(taxa_resposta_q085 AS STRING) taxa_resposta_q085,
SAFE_CAST(taxa_resposta_q086 AS STRING) taxa_resposta_q086,
SAFE_CAST(taxa_resposta_q087 AS STRING) taxa_resposta_q087
from basedosdados-dev.br_inep_saeb_staging.aluno_ef_1995_2005 as t