
# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: br-bcb-agencia

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Agências Bancárias

# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Se a organização não estiver na lista acima ou o nome não estiver conforme o manual de estilo
# criar ou renomear a organização em https://basedosdados.org/organization/
# Exemplos: br-ibge, br-tse, br-rj-gov
organization: br-bcb

# Descrição do conjunto
notes: O conjunto contém a relação de agências e postos de atendimento das instituições financeiras e filiais das administradoras de consórcio informados mensalmente pelas Instituições Financeiras (IFs) ao Banco Central do Brasil (BCB).

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
  - economia
# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos:
#    - fertilidade
#    - preco
#    - desmatamento
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
  - financas
  - credito
  

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified:
  