
# Igual ao dataset.name mas como lower case.
# Exemplos: br_ibge_populacao, br_inep_censo_escolar
dataset_id: br_inmet_bdmep

table_id: microdados

# Título da tabela.
title: Histórico de Dados Meteorológicos

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description: "O BDMEP abriga dados meteorológicos diários em forma digital, de séries históricas das várias estações meteorológicas convencionais da rede de estações do INMET com milhões de informações, referentes às medições diárias, de acordo com as normas técnicas internacionais da Organização Meteorológica Mundial"

# As máximas unidades espaciais que a tabela cobre.
# Exemplo:
#    - sa.br
#  
#    - sa.br.sp
#  
#    - world
spatial_coverage:
    - sa.br

# Anos cobertos pela tabela.
# Exemplos:
#     - 1995(1)2019
# Caso a cobertura não seja contínua:
#     - 2002(2)2010
#     - 2016
#     - 2020
temporal_coverage:
    - 2000(1)2022

# A unidade temporal com qual a tabela é atualizada.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
update_frequency: quarter

# Nível de observação da tabela: o que representa cada linha.
# A combinação das colunas aqui deve construir uma chave única da tabelaOpções de entity em 'https://basedosdados.org/api/3/action/bd_available_options'
# Caso a entidade seja espacial incluir a informação de 'country' Exemplos:
#     - entity: year
#       columns:
#           - ano
#     - country: br
#       entity: state
#       columns:
#           - sigla_uf
observation_level:
    - columns:
          - id_estacao
    - entity: date
      columns:
          - data
    - columns:
          - hora

last_updated:
    metadata: '2023-03-29'
    data: '2023-03-29 17:20:10'
    release: '2023-03-29 17:20:10'

# Versão da tabela. Seguindo o padrão de semantic versioning.
# Exemplos: v1.0, v1.1.3
version: v1.1

# Quem está preenchendo esses metadados?
published_by:
    name: Arthur Gusmão
    email: arthur.gusmao@basedosdados.org
    github_user: arthurfg
    ckan_user: arthurfg
    website: 

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
    name: Arthur Gusmão
    email: arthur.gusmao@basedosdados.org
    github_user: arthurfg
    ckan_user: arthurfg
    website: 

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: "1- Fazer download de todas as bases diretamente do site do INMET. 2- Extrair informações de todas as estações. 3- Concatenar as informações em uma tabela única."

# Url do código de limpeza dos dados do github.
data_cleaning_code_url: https://github.com/basedosdados/mais/tree/master/bases/br_inmet_bdmep/code

# Organização que ajudou institucionalmente na disponibilização dos dados.
partner_organization:
    name: 
    organization_id: 

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions:
    - ano

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: ano
      bigquery_type: int64
      description: Ano
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: ano
          column_name: ano
      measurement_unit: year
      has_sensitive_data: no
      observations:
      is_in_staging: false
      is_partition: true
    - name: data
      bigquery_type: date
      description: Data
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: data
          column_name: data
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true 
      is_partition: false
    - name: hora
      bigquery_type: time
      description: Hora (UTC)
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column: 
          dataset_id: br_bd_diretorios_data_tempo
          table_id: tempo
          column_name: tempo
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: id_estacao
      bigquery_type: string
      description: ID da estação meteorológica
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: precipitacao_total
      bigquery_type: float64
      description: Precipitação total, horária
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: militre
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: pressao_atm_hora
      bigquery_type: float64
      description: Pressão atmosférica ao nível da estação, horária
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: pressao_atm_max
      bigquery_type: float64
      description: Pressão atmosférica máxima ao nível da estação, na hora anterior
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: pressao_atm_min
      bigquery_type: float64
      description: Pressão atmosférica mínima ao nível da estação, na hora anterior
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: radiacao_global
      bigquery_type: float64
      description: Radiação global
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: temperatura_bulbo_hora
      bigquery_type: float64
      description: Temperatura do ar - bulbo seco, horária
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: temperatura_orvalho_hora
      bigquery_type: float64
      description: Temperatura do ponto de orvalho, horária
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: temperatura_max
      bigquery_type: float64
      description: Temperatura máxima, hora anterior
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: temperatura_min
      bigquery_type: float64
      description: Temperatura mínima, hora anterior
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: temperatura_orvalho_max
      bigquery_type: float64
      description: Temperatura de orvalho máxima, hora anterior
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: temperatura_orvalho_min
      bigquery_type: float64
      description: Temperatura de orvalho mínima, hora anterior
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: umidade_rel_max
      bigquery_type: float64
      description: Umidade relativa máxima, hora anterior
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: umidade_rel_min
      bigquery_type: float64
      description: Umidade relativa mínima, hora anterior
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: gram / (m * m * m)
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: umidade_rel_hora
      bigquery_type: float64
      description: Umidade relativa, horária
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: gram / (meter * meter * meter)
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: vento_direcao
      bigquery_type: float64
      description: Direção do vento
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: kilometer / hour
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: vento_rajada_max
      bigquery_type: float64
      description: Vento, rajada máxima
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: kilometer / hour
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: vento_velocidade
      bigquery_type: float64
      description:  Vento, velocidade horária
      temporal_coverage:
        - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: kilometer / hour
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false

number_rows: 70113960

metadata_modified: '2022-11-25T10:08:24.505249'
