library(dplyr)

anos <- c("09", "10", "11","12","13", "14", "15","16","17","18","19")

files_por_ano <- purrr::map(anos, ~ fs::dir_ls("input/") %>% grep(.x,., value=TRUE))

cols = c(
  "deficiencia_transtorno_paciente",
  "deficiencia_fisica_paciente",
  "deficiencia_mental_paciente",
  "deficiencia_visual_paciente",
  "deficiencia_auditiva_paciente",
  "transtorno_mental_paciente",
  "transtorno_comportamental_paciente",
  "outras_deficiencias_paciente",
  "outras_vezes_ocorrencia",
  "lesao_autoprovocada",
  "ocorreu_violencia_fisica",
  "ocorreu_violencia_psicologica",
  "ocorreu_tortura",
  "ocorreu_violencia_sexual",
  "ocorreu_trafico_ser_humano",
  "ocorreu_violencia_financeira",
  "ocorreu_negligencia_abandono",
  "ocorreu_trabalho_infantil",
  "ocorreu_intervencao_legal",
  "ocorreu_outra_violencia",
  "meio_forca",
  "meio_enforcamento",
  "meio_objeto_contundente",
  "meio_objeto_perfurante",
  "meio_objeto_quente",
  "meio_envenenamento",
  "meio_arma_fogo",
  "meio_ameaca",
  "meio_outros",
  "houve_assedio",
  "houve_estupro",
  "houve_pornografia_infantil",
  "houve_exploracao_sexual",
  "houve_outra_violencia_sexual",
  "profilaxia_dst",
  "profilaxia_hiv",
  "profilaxia_hepatite_b",
  "profilaxia_contraceptivo",
  "aborto",
  "coleta_sangue",
  "coleta_semen",
  "coleta_secrecao_vaginal",
  "autor_pai",
  "autor_mae",
  "autor_padrasto",
  "autor_madrasta",
  "autor_conjugue",
  "autor_ex_conjugue",
  "autor_namorado_a",
  "autor_ex_namorado_a",
  "autor_filho_a",
  "autor_irmao",
  "autor_conhecido",
  "autor_desconhecido",
  "autor_cuidador",
  "autor_patrao_chefe",
  "autor_institucional",
  "autor_policial",
  "autor_propria_pessoa",
  "autor_outros",
  "autor_usou_alcool",
  "encaminhamento_saude",
  "encaminhamento_assistencia_social", 
  "encaminhamento_educacao",
  "encaminhamento_atendimento_mulher",
  "encaminhamento_conselho_tutelar",
  "encaminhamento_conselho_idoso",
  "encaminhamento_delegacia_idoso",
  "encaminhamento_direitos_humanos",
  "encaminhamento_mpu",
  "encaminhamento_delegacia_crianca",
  "encaminhamento_delegacia_mulher",
  "encaminhamento_delegacia",
  "encaminhamento_justica_infancia_juventude",
  "encaminhamento_defensoria_publica",
  "violencia_relacionada_trabalho",
  "emitiu_cat"
)

municipios = data.table::fread("tmp/diretorios_municipios.csv", colClasses = "character") %>% 
  select(id_municipio, id_municipio_6)

parse_sinan <- function(file){
  
  base = data.table::fread(file)
  #base = file
  
  base_parsed = base %>%
  rename(
    id_categoria_cid10 = ID_AGRAVO,
    tipo_notificacao = TP_NOT,
    data_notificacao = DT_NOTIFIC, 
    #semana_notificacao = SEM_NOT,
    ano_notificacao = NU_ANO,
    id_uf_notificacao = SG_UF_NOT, 
    id_municipio_6_notificacao = ID_MUNICIP,
    id_regional_saude_notificacao = ID_REGIONA,
    tipo_unidade_notificacao = TP_UNI_EXT,
    id_unidade_notificacao = ID_UNIDADE,
    data_ocorrencia = DT_OCOR,
    id_uf_residencia = SG_UF,
    id_municipio_6_residencia = ID_MN_RESI,
    id_regional_saude_residencia = ID_RG_RESI,
    idade_paciente = NU_IDADE_N,
    sexo_paciente = CS_SEXO,
    gestante_paciente = CS_GESTANT,
    raca_paciente = CS_RACA,
    escolaridade_paciente = CS_ESCOL_N,
    ocupacao_paciente= ID_OCUPA_N,
    situacao_conjugal_paciente = SIT_CONJUG,
    orientacao_sexual_paciente = ORIENT_SEX,
    identidade_genero_paciente = IDENT_GEN,
    deficiencia_transtorno_paciente = DEF_TRANS,
    deficiencia_fisica_paciente = DEF_FISICA,
    deficiencia_mental_paciente = DEF_MENTAL,
    deficiencia_visual_paciente = DEF_VISUAL,
    deficiencia_auditiva_paciente = DEF_AUDITI,
    transtorno_mental_paciente = TRAN_MENT,
    transtorno_comportamental_paciente= TRAN_COMP,
    outras_deficiencias_paciente = DEF_OUT,
    quais_outras_deficiencias_paciente = DEF_ESPEC,
    id_uf_ocorrencia = SG_UF_OCOR,
    id_municipio_6_ocorrencia = ID_MN_OCOR,
    #id_distrito_ocorrencia = ID_DIS_OCOR,
    hora_ocorrencia = HORA_OCOR,
    local_ocorrencia = LOCAL_OCOR,
    outro_local_ocorrencia = LOCAL_ESPE,
    outras_vezes_ocorrencia = OUT_VEZES,
    lesao_autoprovocada = LES_AUTOP,
    motivacao_violencia = VIOL_MOTIV,
    ocorreu_violencia_fisica = VIOL_FISIC,
    ocorreu_violencia_psicologica = VIOL_PSICO,
    ocorreu_tortura = VIOL_TORT,
    ocorreu_violencia_sexual = VIOL_SEXU,
    ocorreu_trafico_ser_humano = VIOL_TRAF,
    ocorreu_violencia_financeira = VIOL_FINAN,
    ocorreu_negligencia_abandono = VIOL_NEGLI,
    ocorreu_trabalho_infantil = VIOL_INFAN,
    ocorreu_intervencao_legal = VIOL_LEGAL,
    ocorreu_outra_violencia = VIOL_OUTR,
    ocorreu_qual_outra = VIOL_ESPEC,
    meio_forca = AG_FORCA,
    meio_enforcamento = AG_ENFOR,
    meio_objeto_contundente = AG_OBJETO,
    meio_objeto_perfurante = AG_CORTE,
    meio_objeto_quente = AG_QUENTE,
    meio_envenenamento = AG_ENVEN,
    meio_arma_fogo = AG_FOGO,
    meio_ameaca = AG_AMEACA,
    meio_outros = AG_OUTROS,
    meio_qual_outro = AG_ESPEC,
    houve_assedio = SEX_ASSEDI,
    houve_estupro = SEX_ESTUPR,
    houve_pornografia_infantil = SEX_PORNO,
    houve_exploracao_sexual = SEX_EXPLO,
    houve_outra_violencia_sexual = SEX_OUTRO,
    houve_qual_outra_violencia_sexual = SEX_ESPEC,
    profilaxia_dst = PROC_DST,
    profilaxia_hiv = PROC_HIV,
    profilaxia_hepatite_b = PROC_HEPB,
    profilaxia_contraceptivo = PROC_CONTR,
    aborto = PROC_ABORT,
    coleta_sangue = PROC_SANG,
    coleta_semen = PROC_SEMEN, 
    coleta_secrecao_vaginal = PROC_VAGIN,
    numero_envolvidos_violencia = NUM_ENVOLV,
    autor_pai = REL_PAI,
    autor_mae = REL_MAE, 
    autor_padrasto = REL_PAD, 
    autor_madrasta = REL_MAD,
    autor_conjugue = REL_CONJ,
    autor_ex_conjugue = REL_EXCON,
    autor_namorado_a = REL_NAMO,
    autor_ex_namorado_a = REL_EXNAM,
    autor_filho_a = REL_FILHO,
    autor_irmao = REL_IRMAO,
    autor_conhecido = REL_CONHEC,
    autor_desconhecido = REL_DESCO,
    autor_cuidador = REL_CUIDA,
    autor_patrao_chefe = REL_PATRAO,
    autor_institucional = REL_INST,
    autor_policial = REL_POL,
    autor_propria_pessoa = REL_PROPRI,
    autor_outros = REL_OUTROS,
    autor_relacao_outros = REL_ESPEC,
    autor_sexo = AUTOR_SEXO,
    autor_usou_alcool = AUTOR_ALCO,
    #autor_ciclo_vida = CICL_VID_AUTOR,
    encaminhamento_saude = REDE_SAU, #OBS: Está diferente no Dicionario
    encaminhamento_assistencia_social = ASSIST_SOC,
    encaminhamento_educacao = REDE_EDUCA,
    encaminhamento_atendimento_mulher = ATEND_MULH,
    encaminhamento_conselho_tutelar = CONS_TUTEL,
    encaminhamento_conselho_idoso = CONS_IDO,
    encaminhamento_delegacia_idoso = DELEG_IDOS,      
    encaminhamento_direitos_humanos = DIR_HUMAN,
    encaminhamento_mpu = MPU,
    encaminhamento_delegacia_crianca = DELEG_CRIA,
    encaminhamento_delegacia_mulher = DELEG_MULH,
    encaminhamento_delegacia = DELEG,
    encaminhamento_justica_infancia_juventude = INFAN_JUV,
    encaminhamento_defensoria_publica = DEFEN_PUBL,
    violencia_relacionada_trabalho = REL_TRAB,
    emitiu_cat = REL_CAT,
    id_subcategoria_cid10 = CIRC_LESAO,
    data_encerramento = DT_ENCERRA
  ) %>%
    mutate(encaminhamento_mpu = ifelse(is.na(encaminhamento_mpu), ENC_MPU, encaminhamento_mpu), 
           encaminhamento_conselho_tutelar = ifelse(is.na(encaminhamento_conselho_tutelar),
                                                    ENC_TUTELA, encaminhamento_conselho_tutelar),
           encaminhamento_delegacia_mulher = ifelse(is.na(encaminhamento_delegacia_mulher),
                                                    ENC_DEAM, encaminhamento_delegacia_mulher),
           encaminhamento_delegacia_crianca = ifelse(is.na(encaminhamento_delegacia_crianca),
                                                     ENC_DPCA, encaminhamento_delegacia_crianca),
           encaminhamento_mpu = ifelse(is.na(encaminhamento_mpu), 
                                       ENC_MPU, encaminhamento_mpu)) %>%
    select(-V1, -ENC_TUTELA, -ENC_DEAM, -ENC_DPCA, -PEN_ORAL, -PEN_ANAL, -PEN_VAGINA,
           -SEM_NOT, NDUPLIC, ID_PAIS, - REL_SEXUAL, - CO_UNI_EXT, - NM_UNI_EXT,
           - tipo_unidade_notificacao, -DT_INVEST, NDUPLIC, SEM_PRI, DT_NASC, 
           - starts_with("ENC_"),           -EVOLUCAO, -DT_OBITO, - ID_PAIS,
           - NDUPLIC, - starts_with("CONS_"), - CLASSI_FIN, - LESAO_NAT,
           - LESAO_ESPE, - LESAO_CORP, - CICL_VID, -SEX_PUDOR, - TPUNINOT, 
           - SEM_PRI, - DT_NASC, - ano_notificacao) %>% 
    mutate(across(everything(),.fns= ~gsub("\\*", NA, .x))) %>%
    collapse::ftransform(
      tipo_notificacao = as.numeric(tipo_notificacao), 
      gestante_paciente = as.numeric(gestante_paciente), 
      raca_paciente = as.numeric(raca_paciente), 
      escolaridade_paciente = as.numeric(escolaridade_paciente),
      situacao_conjugal_paciente = as.numeric(situacao_conjugal_paciente),
      quais_outras_deficiencias_paciente = stringr::str_to_lower(quais_outras_deficiencias_paciente), 
      outro_local_ocorrencia = stringr::str_to_lower(outro_local_ocorrencia), 
      ocorreu_qual_outra = stringr::str_to_lower(ocorreu_qual_outra),
      meio_qual_outro = stringr::str_to_lower(meio_qual_outro),
      autor_relacao_outros = stringr::str_to_lower(autor_relacao_outros),
      orientacao_sexual_paciente = as.numeric(orientacao_sexual_paciente),
      identidade_genero_paciente = as.numeric(identidade_genero_paciente),
      numero_envolvidos_violencia = gsub("[39]", NA, numero_envolvidos_violencia)
    ) %>% 
    mutate(
      raca_paciente = na_if(raca_paciente, 9),
      sexo_paciente = case_when(sexo_paciente =="M" ~ 1, sexo_paciente=="F" ~ 0),
      escolaridade_paciente = na_if(escolaridade_paciente, 0),
      escolaridade_paciente = na_if(escolaridade_paciente, 9),
      gestante_paciente = na_if(gestante_paciente, 9), 
      situacao_conjugal_paciente = na_if(situacao_conjugal_paciente, 9),
      idade_paciente = as.numeric(substr(idade_paciente,2,4)),
      orientacao_sexual_paciente = na_if(orientacao_sexual_paciente, 9),
      identidade_genero_paciente = na_if(identidade_genero_paciente, 9),
      numero_envolvidos_violencia = as.numeric(numero_envolvidos_violencia),
      autor_sexo = gsub("9", NA, autor_sexo), 
      autor_sexo = as.numeric(autor_sexo), 
      local_ocorrencia = stringi::stri_reverse(local_ocorrencia), 
      local_ocorrencia = as.numeric(local_ocorrencia),
      local_ocorrencia = na_if(local_ocorrencia, 99),
      motivacao_violencia = stringr::str_pad(motivacao_violencia, 2, pad="0"),
      motivacao_violencia = stringi::stri_reverse(motivacao_violencia), 
      motivacao_violencia = as.numeric(motivacao_violencia),
      motivacao_violencia = na_if(motivacao_violencia, 99),
      across(all_of(cols), .fns= ~gsub("^9$", NA, .x)),
      across(all_of(cols), .fns= ~gsub("^2$", "0", .x)),
      across(all_of(cols), .fns= ~as.numeric(.x))
    ) %>%
    mutate(across(starts_with("data_"), .fns= ~lubridate::ymd(.x))) %>%
    left_join(municipios, by = c("id_municipio_6_ocorrencia"="id_municipio_6")) %>%
    rename(id_municipio_ocorrencia = id_municipio) %>%
    left_join(municipios, by = c("id_municipio_6_notificacao"= "id_municipio_6")) %>%
    rename(id_municipio_notificacao = id_municipio) %>% 
    left_join(municipios, by = c("id_municipio_6_residencia"= "id_municipio_6")) %>%
    rename(id_municipio_residencia = id_municipio) %>%
    mutate(ano_notificacao = lubridate::year(data_notificacao)) %>%
    relocate(data_notificacao	,
             id_categoria_cid10	,
             id_subcategoria_cid10	,
             tipo_notificacao	,
             id_uf_notificacao	,
             id_municipio_notificacao	,
             id_municipio_6_notificacao	,
             id_unidade_notificacao	,
             id_regional_saude_notificacao	,
             data_ocorrencia	,
             id_uf_ocorrencia	,
             id_municipio_ocorrencia	,
             id_municipio_6_ocorrencia	,
             hora_ocorrencia	,
             local_ocorrencia	,
             outro_local_ocorrencia	,
             outras_vezes_ocorrencia	,
             id_uf_residencia	,
             id_municipio_6_residencia	,
             id_municipio_residencia	,
             id_regional_saude_residencia	,
             idade_paciente	,
             sexo_paciente	,
             gestante_paciente	,
             raca_paciente	,
             escolaridade_paciente	,
             ocupacao_paciente	,
             situacao_conjugal_paciente	,
             orientacao_sexual_paciente	,
             identidade_genero_paciente	,
             motivacao_violencia	,
             violencia_relacionada_trabalho	,
             emitiu_cat	,
             deficiencia_transtorno_paciente	,
             deficiencia_fisica_paciente	,
             deficiencia_mental_paciente	,
             deficiencia_visual_paciente	,
             deficiencia_auditiva_paciente	,
             transtorno_mental_paciente	,
             transtorno_comportamental_paciente	,
             outras_deficiencias_paciente	,
             quais_outras_deficiencias_paciente	,
             lesao_autoprovocada	,
             ocorreu_violencia_fisica	,
             ocorreu_violencia_psicologica	,
             ocorreu_tortura	,
             ocorreu_violencia_sexual	,
             ocorreu_trafico_ser_humano	,
             ocorreu_violencia_financeira	,
             ocorreu_negligencia_abandono	,
             ocorreu_trabalho_infantil	,
             ocorreu_intervencao_legal	,
             ocorreu_outra_violencia	,
             ocorreu_qual_outra	,
             meio_forca	,
             meio_enforcamento	,
             meio_objeto_contundente	,
             meio_objeto_perfurante	,
             meio_objeto_quente	,
             meio_envenenamento	,
             meio_arma_fogo	,
             meio_ameaca	,
             meio_outros	,
             meio_qual_outro	,
             houve_assedio	,
             houve_estupro	,
             houve_pornografia_infantil	,
             houve_exploracao_sexual	,
             houve_outra_violencia_sexual	,
             houve_qual_outra_violencia_sexual	,
             profilaxia_dst	,
             profilaxia_hiv	,
             profilaxia_hepatite_b	,
             coleta_sangue	,
             coleta_semen	,
             coleta_secrecao_vaginal	,
             profilaxia_contraceptivo	,
             aborto	,
             numero_envolvidos_violencia	,
             autor_pai	,
             autor_mae	,
             autor_padrasto	,
             autor_madrasta	,
             autor_conjugue	,
             autor_ex_conjugue	,
             autor_namorado_a	,
             autor_ex_namorado_a	,
             autor_filho_a	,
             autor_desconhecido	,
             autor_irmao	,
             autor_conhecido	,
             autor_cuidador	,
             autor_patrao_chefe	,
             autor_institucional	,
             autor_policial	,
             autor_propria_pessoa	,
             autor_outros	,
             autor_relacao_outros	,
             autor_sexo	,
             autor_usou_alcool	,
             encaminhamento_saude	,
             encaminhamento_assistencia_social	,
             encaminhamento_educacao	,
             encaminhamento_atendimento_mulher	,
             encaminhamento_conselho_tutelar	,
             encaminhamento_conselho_idoso	,
             encaminhamento_delegacia_idoso	,
             encaminhamento_direitos_humanos	,
             encaminhamento_mpu	,
             encaminhamento_delegacia_crianca	,
             encaminhamento_delegacia_mulher	,
             encaminhamento_delegacia	,
             encaminhamento_justica_infancia_juventude	,
             encaminhamento_defensoria_publica	,
             data_encerramento	
    )
  
  return(base_parsed)
  
}

files_por_ano %>% purrr::walk(function(files){ 
  df = purrr::map_dfr(files, parse_sinan)
  ano = distinct(df, ano_notificacao) %>% pull()
  df = dplyr::select(df, -ano_notificacao)
  fs::dir_create(glue::glue("output/microdados-violencia/ano={ano}/"))
  data.table::fwrite(df, glue::glue("output/microdados-violencia/ano={ano}/sinan-violencia-{ano}.csv"))               
})

