name: "Setup Environment"
description: "Create config files and credentials needed to run basedosdados client"
author: "Base dos Dados"

runs: 
  using: composite
  steps:
    - run: python ${{ github.action_path }}\main.py
      shell: cmd
