
# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: br-abrinq-oca

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Dados do Observatório da Criança e do Adolescente

# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Exemplos: br-ibge, br-tse, br-rj-gov
organization:
    - br-abrinq

# Descrição do conjunto
notes: O Observatório da Criança e do Adolescente é um espaço virtual que possibilita
    a consulta, em um mesmo lugar, dos principais indicadores sociais relacionados
    direta e indiretamente à infância e adolescência no Brasil. Seu objetivo é organizar
    as informações e facilitar o acesso a bases de dados de diversas fontes púbicas
    e privadas sobre população, qualidade de vida e bem-estar de crianças e adolescentes
    com idades ente zero e 18 anos, permitindo uma análise da evolução das principais
    políticas, dos desafios e das desigualdades regionais. Destina-se a formadores
    de opinião, representantes da sociedade civil, pesquisadores, gestores públicos
    e quaisquer pessoas que queiram, a partir de um simples mecanismo de busca online,
    conhecer a realidade e os problemas sociais que mais afetam as crianças e os adolescentes
    no país.

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
    - educacao
    - gov-fin-pub
    - populacao
    - saude
    - seguranca

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos: fertilidade, preco, desmatamento.
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
    - adolescente
    - congresso
    - crianca
    - desigualdade
    - educacao
    - legislacao
    - lei
    - proposicao
    - regulacao
    - saude

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified: '2022-02-14T01:23:42.267594'
