#!/bin/bash

echo ------------------------------------------------------
echo Sort
echo ------------------------------------------------------

python -m isort --profile black .github
python -m isort --profile black python-package

echo ------------------------------------------------------
echo Format
echo ------------------------------------------------------

python -m black .github
python -m black python-package

echo ------------------------------------------------------
echo Lint
echo ------------------------------------------------------

python -m pylint --exit-zero .github
python -m pylint --exit-zero python-package

echo ------------------------------------------------------
echo Commit
echo ------------------------------------------------------
