FROM lycheeverse/lychee:latest
COPY gen_report.sh /gen_report.sh
ENTRYPOINT ["/gen_report.sh"]

# Reference
# Lychee Action
# https://github.com/lycheeverse/lychee-action
# https://github.com/lycheeverse/lychee-action/blob/master/entrypoint.sh  
