FROM lycheeverse/lychee:latest
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

# Reference
# Lychee Action
# https://github.com/lycheeverse/lychee-action
# https://github.com/lycheeverse/lychee-action/blob/master/entrypoint.sh