# -*- coding: utf-8 -*-
"""microrregioes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KAqYxd3jFK6JHPevPh9I_SeHajNqtpij
"""

pip install geobr

"""# Nova seção"""

import geobr
import pandas as pd
import numpy as np

micro = geobr.read_micro_region(year=2020)

micro

micro['code_state'] = micro['code_state'].astype(np.int64)
micro['code_micro'] = micro['code_micro'].astype(np.int64)

micro

micro=micro.rename({'code_state':'id_uf', 'abbrev_state':'sigla_uf', 'code_micro':'id_microrregiao','geometry':'geometria', 'name_micro': 'nome_microrregiao'},axis='columns')

micro=micro.filter(items=['id_uf', 'sigla_uf', 'id_microrregiao', 'geometria'])

micro

from posixpath import sep

micro.to_csv('microrregiao.csv', sep=',', index=False, header=True)

vars(micro)