# -*- coding: utf-8 -*-
"""regiao_imediata.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WXqfH0NzbvIrjVLQQF5fg3AGI3FtzKA4
"""

pip install geobr

import geobr
import pandas as pd
import numpy as np
from posixpath import sep

regiao_imediata = geobr.read_immediate_region()

regiao_imediata['code_state'] = regiao_imediata['code_state'].astype(np.int64)
regiao_imediata['code_immediate'] = regiao_imediata['code_immediate'].astype(np.int64)

regiao_imediata=regiao_imediata.rename({'code_state':'id_uf', 'abbrev_state':'sigla_uf', 'code_immediate':'id_regiao_imediata','geometry':'geometria'},axis='columns')

regiao_imediata=regiao_imediata.filter(items=['id_uf', 'sigla_uf', 'id_regiao_imediata', 'geometria'])

regiao_imediata.to_csv('regiao_imediata.csv', sep=',', index=False, header=True)