# -*- coding: utf-8 -*-
"""regiao_intermediaria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bG54ZQ6Wa08L-PL9oIMybLyYU05gRvDj
"""

pip install geobr

import geobr
import pandas as pd
import numpy as np
from posixpath import sep

x = geobr.read_intermediate_region()

x['code_state'] = x['code_state'].astype(np.int64)
x['code_intermediate'] = x['code_intermediate'].astype(np.int64)

x=x.rename({'code_state':'id_uf', 'abbrev_state':'sigla_uf', 'code_intermediate':'id_regiao_intermediaria','geometry':'geometria'}, axis='columns')

x=x.filter(items=['id_uf', 'sigla_uf', 'id_regiao_intermediaria', 'geometria'])

x.to_csv('regiao_intermediaria.csv', sep=',', index=False, header=True)