# Igual ao dataset.name mas como lower case.
# Exemplos: br_ibge_populacao, br_inep_censo_escolar
dataset_id: br_bd_diretorios_brasil

table_id: cep

# Título da tabela.
title: Código de Endereçamento Postal (CEP)

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description: Na tabela, é possível encontrar a numeração dos CEPs juntamente com informações sobre suas localidades, tais como logradouros, bairros e cidades, além de complementos e identificação geográfica, compostos pela latitude e longitude. Os dados foram obtidos através de uma base aberta no kaggle.

# As máximas unidades espaciais que a tabela cobre.
# Exemplo:
#    - sa.br
#  
#    - sa.br.sp
#  
#    - world
spatial_coverage:
    - sa.br

# Anos cobertos pela tabela.
# Exemplos:
#     - 1995(1)2019
# Caso a cobertura não seja contínua:
#     - 2002(2)2010
#     - 2016
#     - 2020
temporal_coverage:

# A unidade temporal com qual a tabela é atualizada.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
update_frequency: uncertain 

# Nível de observação da tabela: o que representa cada linha.
# A combinação das colunas aqui deve construir uma chave única da tabelaOpções de entity em 'https://basedosdados.org/api/3/action/bd_available_options'
# Caso a entidade seja espacial incluir a informação de 'country' Exemplos:
#     - entity: year
#       columns:
#           - ano
#     - country: br
#       entity: state
#       columns:
#           - sigla_uf
observation_level:
     - country: br
       entity: zip_code
       columns:
           - cep

last_updated:
    metadata: '2023-04-11'
    data: '2023-04-11 16:50:35'
    release: '2023-04-11 16:50:35'

# Versão da tabela. Seguindo o padrão de semantic versioning.
# Exemplos: v1.0, v1.1.3
version: v1.0

# Quem está preenchendo esses metadados?
published_by:
    name: Gabrielle Carvalho
    email: gabrielle.carvalho@basedosdados.org
    github_user: gabrielle-carv
    ckan_user: gabs_carvalho
    website:

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
    name: Gabrielle Carvalho
    email: gabrielle.carvalho@basedosdados.org
    github_user: gabrielle-carv
    ckan_user: gabs_carvalho
    website:

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: Organização e modificação dos nomes das colunas para os padrões da BD.

# Url do código de limpeza dos dados do github.
data_cleaning_code_url: https://github.com/basedosdados/mais/tree/master/bases/br_bd_diretorios_brasil/code

# Organização que ajudou institucionalmente na disponibilização dos dados.
partner_organization:
    name:
    organization_id:

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions:
    - sigla_uf

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: cep
      bigquery_type: string
      description: Número do CEP
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: logradouro
      bigquery_type: string
      description: Logradouro
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: bairro
      bigquery_type: string
      description: Bairro
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: cidade
      bigquery_type: string
      description: Nome da cidade, distrito ou município
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations: É possível que dentro da variável surja o nome da cidade, do distrito
          ou do município. Caso o nome da cidade ou do distrito seja mencionado, o
          nome do município aparecerá entre parênteses logo após.
      is_in_staging: true
      is_partition: false
    - name: complemento
      bigquery_type: string
      description: Complemento do endereço
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: id_municipio
      bigquery_type: string
      description: ID Município - IBGE 7 Dígitos
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: sigla_uf
      bigquery_type: string
      description: Sigla da Unidade da Federação
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true 
      is_partition: true
    - name: latitude
      bigquery_type: float64
      description: Latitude do CEP
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: longitude
      bigquery_type: float64
      description: Longitude do CEP
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: centroide
      bigquery_type: geography
      description: Centróide do CEP
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: false
      is_partition: false

number_rows: 1108505

metadata_modified: 
