/*
Query para publicar a tabela.

Esse é o lugar para:
    - modificar nomes, ordem e tipos de colunas
    - dar join com outras tabelas
    - criar colunas extras (e.g. logs, proporções, etc.)

Qualquer coluna definida aqui deve também existir em `table_config.yaml`.

# Além disso, sinta-se à vontade para alterar alguns nomes obscuros
# para algo um pouco mais explícito.

TIPOS:
    - Para modificar tipos de colunas, basta substituir STRING por outro tipo válido.
    - Exemplo: `SAFE_CAST(column_name AS NUMERIC) column_name`
    - Mais detalhes: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types
*/

CREATE VIEW basedosdados-dev.br_ibge_pnad.microdados_compatibilizado_datazoom AS
SELECT 
SAFE_CAST(ano AS STRING) ano,
SAFE_CAST(sigla_uf AS STRING) sigla_uf,
SAFE_CAST(regiao AS STRING) regiao,
SAFE_CAST(uf AS STRING) uf,
SAFE_CAST(id_dom AS STRING) id_dom,
SAFE_CAST(urbana AS STRING) urbana,
SAFE_CAST(area_censit AS STRING) area_censit,
SAFE_CAST(tot_pess AS STRING) tot_pess,
SAFE_CAST(tot_pess_10_mais AS STRING) tot_pess_10_mais,
SAFE_CAST(especie_dom AS STRING) especie_dom,
SAFE_CAST(tipo_dom AS STRING) tipo_dom,
SAFE_CAST(parede AS STRING) parede,
SAFE_CAST(cobertura AS STRING) cobertura,
SAFE_CAST(agua_rede AS STRING) agua_rede,
SAFE_CAST(esgoto AS STRING) esgoto,
SAFE_CAST(sanit_excl AS STRING) sanit_excl,
SAFE_CAST(lixo AS STRING) lixo,
SAFE_CAST(ilum_eletr AS STRING) ilum_eletr,
SAFE_CAST(comodos AS STRING) comodos,
SAFE_CAST(dormit AS STRING) dormit,
SAFE_CAST(sanit AS STRING) sanit,
SAFE_CAST(posse_dom AS STRING) posse_dom,
SAFE_CAST(filtro AS STRING) filtro,
SAFE_CAST(fogao AS STRING) fogao,
SAFE_CAST(geladeira AS STRING) geladeira,
SAFE_CAST(radio AS STRING) radio,
SAFE_CAST(tv AS STRING) tv,
SAFE_CAST(renda_dom AS STRING) renda_dom,
SAFE_CAST(renda_domB AS STRING) renda_domB,
SAFE_CAST(peso AS STRING) peso,
SAFE_CAST(aluguel AS STRING) aluguel,
SAFE_CAST(prestacao AS STRING) prestacao,
SAFE_CAST(deflator AS STRING) deflator,
SAFE_CAST(conversor AS STRING) conversor,
SAFE_CAST(renda_dom_def AS STRING) renda_dom_def,
SAFE_CAST(renda_domB_def AS STRING) renda_domB_def,
SAFE_CAST(aluguel_def AS STRING) aluguel_def,
SAFE_CAST(prestacao_def AS STRING) prestacao_def,
SAFE_CAST(num_fam AS STRING) num_fam,
SAFE_CAST(metropol AS STRING) metropol,
SAFE_CAST(sexo AS STRING) sexo,
SAFE_CAST(cond_dom AS STRING) cond_dom,
SAFE_CAST(cond_fam AS STRING) cond_fam,
SAFE_CAST(dia_nasc AS STRING) dia_nasc,
SAFE_CAST(mes_nasc AS STRING) mes_nasc,
SAFE_CAST(ano_nasc AS STRING) ano_nasc,
SAFE_CAST(idade AS STRING) idade,
SAFE_CAST(ler_escrever AS STRING) ler_escrever,
SAFE_CAST(serie_freq AS STRING) serie_freq,
SAFE_CAST(grau_freq AS STRING) grau_freq,
SAFE_CAST(serie_nao_freq AS STRING) serie_nao_freq,
SAFE_CAST(grau_nao_freq AS STRING) grau_nao_freq,
SAFE_CAST(tinha_outro_trab AS STRING) tinha_outro_trab,
SAFE_CAST(ocup_sem AS STRING) ocup_sem,
SAFE_CAST(ramo_negocio_sem AS STRING) ramo_negocio_sem,
SAFE_CAST(tem_carteira_assinada AS STRING) tem_carteira_assinada,
SAFE_CAST(renda_mensal_din AS STRING) renda_mensal_din,
SAFE_CAST(renda_mensal_prod AS STRING) renda_mensal_prod,
SAFE_CAST(horas_trab_sem AS STRING) horas_trab_sem,
SAFE_CAST(renda_mensal_din_outra AS STRING) renda_mensal_din_outra,
SAFE_CAST(renda_mensal_prod_outra AS STRING) renda_mensal_prod_outra,
SAFE_CAST(horas_trab_sem_outro AS STRING) horas_trab_sem_outro,
SAFE_CAST(contr_inst_prev AS STRING) contr_inst_prev,
SAFE_CAST(qual_inst_prev AS STRING) qual_inst_prev,
SAFE_CAST(tomou_prov_semana AS STRING) tomou_prov_semana,
SAFE_CAST(tomou_prov_2meses AS STRING) tomou_prov_2meses,
SAFE_CAST(que_prov_tomou AS STRING) que_prov_tomou,
SAFE_CAST(tinha_cart_assin_ant_ano AS STRING) tinha_cart_assin_ant_ano,
SAFE_CAST(renda_aposentadoria AS STRING) renda_aposentadoria,
SAFE_CAST(renda_pensao AS STRING) renda_pensao,
SAFE_CAST(renda_abono AS STRING) renda_abono,
SAFE_CAST(renda_aluguel AS STRING) renda_aluguel,
SAFE_CAST(renda_outras AS STRING) renda_outras,
SAFE_CAST(renda_mensal_ocup_prin AS STRING) renda_mensal_ocup_prin,
SAFE_CAST(renda_mensal_todos_trab AS STRING) renda_mensal_todos_trab,
SAFE_CAST(renda_mensal_todas_fontes AS STRING) renda_mensal_todas_fontes,
SAFE_CAST(ramo_negocio_agreg AS STRING) ramo_negocio_agreg,
SAFE_CAST(horas_trab_todos_trab AS STRING) horas_trab_todos_trab,
SAFE_CAST(pos_ocup_sem AS STRING) pos_ocup_sem,
SAFE_CAST(grupos_ocup_sem AS STRING) grupos_ocup_sem,
SAFE_CAST(num_pes_fam AS STRING) num_pes_fam,
SAFE_CAST(renda_mensal_fam AS STRING) renda_mensal_fam,
SAFE_CAST(ordem AS STRING) ordem,
SAFE_CAST(cor AS STRING) cor,
SAFE_CAST(educa AS STRING) educa,
SAFE_CAST(freq_escola AS STRING) freq_escola,
SAFE_CAST(trabalhou_semana AS STRING) trabalhou_semana,
SAFE_CAST(tinha_trab_sem AS STRING) tinha_trab_sem,
SAFE_CAST(ocup_ant_ano AS STRING) ocup_ant_ano,
SAFE_CAST(ramo_negocio_ant_ano AS STRING) ramo_negocio_ant_ano,
SAFE_CAST(renda_din_def AS STRING) renda_din_def,
SAFE_CAST(renda_prod_def AS STRING) renda_prod_def,
SAFE_CAST(renda_din_outra_def AS STRING) renda_din_outra_def,
SAFE_CAST(renda_prod_outra_def AS STRING) renda_prod_outra_def,
SAFE_CAST(renda_ocup_prin_def AS STRING) renda_ocup_prin_def,
SAFE_CAST(renda_todos_trab_def AS STRING) renda_todos_trab_def,
SAFE_CAST(renda_todas_fontes_def AS STRING) renda_todas_fontes_def,
SAFE_CAST(renda_fam_def AS STRING) renda_fam_def,
SAFE_CAST(renda_aposentadoria_def AS STRING) renda_aposentadoria_def,
SAFE_CAST(renda_pensao_def AS STRING) renda_pensao_def,
SAFE_CAST(renda_abono_def AS STRING) renda_abono_def,
SAFE_CAST(renda_aluguel_def AS STRING) renda_aluguel_def,
SAFE_CAST(renda_outras_def AS STRING) renda_outras_def
FROM basedosdados-dev.br_ibge_pnad_staging.microdados_compatibilizado_datazoom AS t