# Igual ao dataset.name mas como lower case.
# Exemplos: br_ibge_populacao, br_inep_censo_escolar
dataset_id: br_inep_saeb

table_id: aluno_ef_2ano

# Título da tabela.
title: Sistema de Avaliação da Educação Básica (Saeb)

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description: Microdados do SAEB com respostas dos alunos para as avaliações e questionário socioeconômico matriculados no 2º ano do Ensino Fundamental

# A máxima unidade espacial que a tabela cobre.
# Exemplo:
#   - continent: south_america
#     country: br
spatial_coverage:
    - sa.br

# Anos cobertos pela tabela.
# Preencher como lista de intervalos.
# Exemplos: ['1995(1)2019(2)'], ['2002(2)2010', '2016', '2020'].
temporal_coverage:
    - '2019'

# A unidade temporal com qual a tabela é atualizada.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
update_frequency: two_years

# Nível de observação da tabela: o que representa cada linha.
observation_level:
    - entity: year
      columns:
         - ano 
    - country: br
      entity: state
      columns:
         - sigla_uf
    - entity: exam
      columns: 
         - disciplina
    - entity: person
      columns:
         - id_aluno

last_updated:
    metadata: '2022-06-02'
    data: '2022-06-02 09:00:00'
    release:

# Versão da tabela. Seguindo o padrão de semantic versioning.
# Exemplo: v1.1.3
version: v1.1

# Quem está preenchendo esses metadados?
published_by:
    name: Lucas Moreira
    email: lucas.moreira@basedosdados.org
    github_user: lucasnascm
    ckan_user: lucasnascm
    website:

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
    name: Lucas Moreira
    email: lucas.moreira@basedosdados.org
    github_user: lucasnascm
    ckan_user: lucasnascm
    website:

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: Padronização sob as diretrizes da BD

# Url do código de limpeza dos dados.
data_cleaning_code_url: https://github.com/basedosdados/mais/tree/master/bases/br_inep_saeb/code

# Organização que ajudou institucionalmente na disponibilização dos dados.
partner_organization:
    name:
    organization_id:

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions:
    - ano
    - sigla_uf

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Algumas colunas existirão apenas na tabela final, você as construirá em `publish.sql`.
# Para esses, defina is_in_staging como False.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: ano
      bigquery_type: int64
      description: Ano
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: ano
          column_name: ano
      measurement_unit: year
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: true
    - name: id_regiao
      bigquery_type: string
      description: ID Região
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: sigla_uf
      bigquery_type: string
      description: Sigla da Unidade da Federação
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: uf
          column_name: sigla
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: true
    - name: id_municipio
      bigquery_type: string
      description: ID Município - IBGE 7 Dígitos
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: municipio
          column_name: id_municipio
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: area
      bigquery_type: string
      description: Área em relação ao município
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: id_escola
      bigquery_type: string
      description: ID escola - INEP
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: escola
          column_name: id_escola
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: rede
      bigquery_type: string
      description: Rede Escolar
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: escola
          column_name: dependencia_administrativa
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: localizacao
      bigquery_type: string
      description: Localização da escola
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: escola
          column_name: localizacao
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: id_turma
      bigquery_type: string
      description: ID Turma
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: turno
      bigquery_type: string
      description: Turno
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: serie
      bigquery_type: int64
      description: Série
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: id_aluno
      bigquery_type: string
      description: ID Aluno
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: situacao_censo
      bigquery_type: int64
      description: Indicador de compatibilização com o Censo Escolar 2019(2)
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: disciplina
      bigquery_type: string
      description: Disciplina
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations: Variável criada com base na disciplina indicada por LP ou MT
      is_in_staging: true
      is_partition: false
    - name: preenchimento_caderno
      bigquery_type: int64
      description: Indicador de preenchimento da prova
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: presenca
      bigquery_type: int64
      description: Indicador de presença na prova
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: caderno
      bigquery_type: string
      description: Número do caderno de prova
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: bloco_1
      bigquery_type: string
      description: Identificador do Bloco 1
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: bloco_2
      bigquery_type: string
      description: Identificador do Bloco 2
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: bloco_1_aberto
      bigquery_type: string
      description: Identificador do Bloco 1 de resposta construída
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: bloco_2_aberto
      bigquery_type: string
      description: Identificador do Bloco 2 de resposta construída
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: respostas_bloco_1
      bigquery_type: string
      description: Respostas do aluno ao Bloco 1 da prova
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: respostas_bloco_2
      bigquery_type: string
      description: Respostas do aluno ao Bloco 2 da prova
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: conceito_q1
      bigquery_type: string
      description: Conceito obtido na questão 1 de resposta construída
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: conceito_q2
      bigquery_type: string
      description: Conceito obtido na questão 2 de resposta construída
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: resposta_texto
      bigquery_type: string
      description: Análise da Produção Textual
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: conceito_proposito
      bigquery_type: string
      description: Conceito obtido para propósito na produção de texto
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: conceito_elemento
      bigquery_type: string
      description: Conceito obtido para elemento na produção de texto
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: conceito_segmentacao
      bigquery_type: string
      description: Conceito obtido para segmentação na produção de texto
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: texto_grafia
      bigquery_type: string
      description: Conceito obtido para grafia na produção de texto
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: indicador_proficiencia
      bigquery_type: string
      description: Indicador para cálculo da proficiência (no mínimo três itens respondidos
          no caderno de prova)
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: amostra
      bigquery_type: string
      description: Indicador de participação da amostra
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: estrato
      bigquery_type: string
      description: Descrição dos estratos
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: peso_aluno
      bigquery_type: float64
      description: Peso do aluno
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: proficiencia
      bigquery_type: float64
      description: Proficiência do aluno na escala única do SAEB com média = 0 e desvio
          = 1 na população de referência
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: erro_padrao
      bigquery_type: float64
      description: Erro padrão da proficiência
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: proficiencia_saeb
      bigquery_type: float64
      description: Proficiência do aluno na escala única do SAEB com média = 750 e
          desvio = 50 na população de referência
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: erro_padrao_saeb
      bigquery_type: float64
      description: Erro padrão da proficiência transformada
      temporal_coverage:
          - 2019(2)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false

metadata_modified: '2022-03-21T18:17:59.798990'
