
# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Exemplos: br-ibge, br-tse, br-rj-gov
organization: br-ana

dataset_id: br_ana_reservatorios

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Reservatórios Brasileiros

# Descrição e anotações úteis sobre os dados.
description: Dados operativos dos reservatórios do Brasil, disponibilizados pela Agência Nacional de Águas (ANA). 

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
  - energia
  - meio-ambiente

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos: fertilidade, preco, desmatamento.
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
  - agua
  - reservatorio
  - bacia
  - usina 
  

# Url completa do CKAN já contendo o dataset-id
# Exemplo: https://basedosdados.org/dataset/<dataset-id>
ckan_url:

# Url completa do Github já contendo o dataset_id
# Exemplo: https://github.com/basedosdados/mais/tree/master/bases/<dataset_id>
github_url:

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified:
