# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: br-ipea-avs

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Município

# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Se a organização não estiver na lista acima ou o nome não estiver conforme o manual de estilo
# criar ou renomear a organização em https://basedosdados.org/organization/
# Exemplos: br-ibge, br-tse, br-rj-gov
organization: br-ipea

# Descrição do conjunto
notes: A plataforma oferece um panorama da vulnerabilidade e da exclusão social dos municípios e estados. Sua relevância vem justamente da capacidade de fornecer informações sobre a unidade político-administrativa mais próxima do cotidiano dos cidadão, o município. Além disso, o AVS permite conhecer as desigualdades a nível intramunicipal das diversas espacialidades de uma mesma região metropolitana.

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
    - economia
    - educacao
    - politica
    - gov-fin-pub
    - populacao

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos:
#    - fertilidade
#    - preco
#    - desmatamento
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
    - adolescente
    - agua
    - alfabetizacao
    - ensino
    - ensino fundamental
    - ensino medio
    - escolaridade
    - escolas
    - esgoto
    - expectativa de vida
    - gravidez
    - IDH
    - longevidade
    - municipio
    - nivel socioeconomico
    - renda
    - trabalho

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified:
