# Igual ao dataset.name mas como lower case.
# Exemplos: br_ibge_populacao, br_inep_censo_escolar
dataset_id: br_cgu_servidores_executivo_federal

table_id: remuneracao_ativo

# Título da tabela.
title: Registros de Servidores Públicos do Executivo Federal

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description:

# As máximas unidades espaciais que a tabela cobre.
# Exemplo:
#   - sa.br
spatial_coverage:

# Anos cobertos pela tabela.
# Preencher como lista de intervalos.
# Exemplos: ['1995(1)2019'], ['2002(2)2010', '2016', '2020'].
temporal_coverage:

# A unidade temporal com qual a tabela é atualizada.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
update_frequency:

# Nível de observação da tabela: o que representa cada linha.
observation_level:

last_updated:
    metadata:
    data:
    release:

# Versão da tabela. Seguindo o padrão de semantic versioning.
# Exemplo: v1.1.3
version: ''

# Quem está preenchendo esses metadados?
published_by:
    name:
    email:
    github_user:
    ckan_user:
    website:

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
    name:
    email:
    github_user:
    ckan_user:
    website:

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description:

# Url do código de limpeza dos dados.
data_cleaning_code_url:

# Organização que ajudou institucionalmente na disponibilização dos dados.
partner_organization:
    name:
    organization_id:

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions:
    - carreira
    - ano
    - mes

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Algumas colunas existirão apenas na tabela final, você as construirá em `publish.sql`.
# Para esses, defina is_in_staging como False.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: carreira
      bigquery_type:
      description:
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      observations:
      is_in_staging:
      is_partition: true
    - name: ano
      bigquery_type: int64
      description: Ano
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: ano
          column_name: ano
      measurement_unit: year
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition: true
    - name: mes
      bigquery_type: int64
      description: Mês
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: mes
          column_name: mes
      measurement_unit: month
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition: true
    - name: id_servidor_portal
      bigquery_type: string
      description: 'ID do servidor no Portal da Transparência '
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: cpf
      bigquery_type: string
      description: 'CPF do servidor anonimizado '
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: yes
      observations:
      is_in_staging:
      is_partition:
    - name: nome
      bigquery_type: string
      description: 'Nome '
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: yes
      observations:
      is_in_staging:
      is_partition:
    - name: remuneracao_bruta_brl
      bigquery_type: float64
      description: Remuneração bruta gasta em Real
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: brl
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: remuneracao_bruta_usd
      bigquery_type: float64
      description: 'Remuneração bruta gasta em Dólar '
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: abate_teto_brl
      bigquery_type: float64
      description: Abate em relação ao valor do teto em Real
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: brl
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: abate_teto_usd
      bigquery_type: float64
      description: Abate em relação ao valor do teto em Dólar
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: gratificao_natalina_brl
      bigquery_type: float64
      description: Gratificação Natalina em Real
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: brl
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: gratificao_natalina_usd
      bigquery_type: float64
      description: Gratificação Natalina em Dólar
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: abate_teto_gratificacao_natalina_brl
      bigquery_type: float64
      description: Abate do teto na Gratificação Natalina em Real
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: brl
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: abate_teto_gratificacao_natalina_usd
      bigquery_type: float64
      description: Abate do teto na Gratificação Natalina em Dólar
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: ferias_brl
      bigquery_type: float64
      description: Remuneração de férias em Real
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: brl
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: ferias_usd
      bigquery_type: float64
      description: Remuneração de férias em Dólar
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: outras_remuneracoes_brl
      bigquery_type: float64
      description: Outras remunerações eventuais em Real
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: brl
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: outras_remuneracoes_usd
      bigquery_type: float64
      description: Outras remunerações eventuais em Dólar
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: irrf_brl
      bigquery_type: float64
      description: Imposto de Renda Retido na Fonte (IRRF) em Real
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: brl
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: irrf_usd
      bigquery_type: float64
      description: Imposto de Renda Retido na Fonte (IRRF) em Dólar
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: pss_rgps_brl
      bigquery_type: float64
      description: Plano de Seguridade Social (PSS) ou Regime Geral de Previdência
          Social  (RGPS) em Real
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: brl
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: pss_rgps_usd
      bigquery_type: float64
      description: Plano de Seguridade Social (PSS) ou Regime Geral de Previdência
          Social  (RGPS) em Dólar
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: demais_deducoes_brl
      bigquery_type: float64
      description: Demais deduções em Real
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: brl
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: demais_deducoes_usd
      bigquery_type: float64
      description: Demais deduções em Dólar
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: pensao_militar_brl
      bigquery_type: float64
      description: Pensão militar em Real
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: brl
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: pensao_militar_usd
      bigquery_type: float64
      description: Pensão militar em Dólar
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: fundo_saude_brl
      bigquery_type: float64
      description: Fundo de Saúde Militar em Real
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: brl
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: fundo_saude_usd
      bigquery_type: float64
      description: Fundo de Saúde Militar em Dólar
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: taxa_ocupacao_imovel_funcional_brl
      bigquery_type: float64
      description: Taxa de ocupação imóvel funcional em Real
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: brl
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: taxa_ocupacao_imovel_funcional_usd
      bigquery_type: float64
      description: Taxa de ocupação imóvel funcional em Dólar
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: remuneracao_liquida_militar_brl
      bigquery_type: float64
      description: Remuneração após deduções obrigatória em Real
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: brl
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: remuneracao_liquida_militar_usd
      bigquery_type: float64
      description: Remuneração após deduções obrigatória em Dólar
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: verba_indenizatoria_civil_brl
      bigquery_type: float64
      description: 'Verba indenizatória registradas em sistemas de pessoal - civil
          em Real '
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: brl
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: verba_indenizatoria_civil_usd
      bigquery_type: float64
      description: 'Verba indenizatória registradas em sistemas de pessoal - civil
          em Dólar '
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: verba_indenizatoria_militar_brl
      bigquery_type: float64
      description: 'Verba indenizatória registradas em sistemas de pessoal - militar
          em Real '
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: brl
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: verba_indenizatoria_militar_usd
      bigquery_type: float64
      description: 'Verba indenizatória registradas em sistemas de pessoal - militar
          em Dólar '
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: verba_indenizatoria_deslig_voluntario_brl
      bigquery_type: float64
      description: Verba indenizatória programa desligamento voluntário em Real
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: brl
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: verba_indenizatoria_deslig_voluntario_usd
      bigquery_type: float64
      description: 'Verba indenizatória programa desligamento voluntário em Dólar '
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: total_verba_indenizatoria_brl
      bigquery_type: float64
      description: Total da verba indenizatória em Real
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: brl
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:
    - name: total_verba_indenizatoria_usd
      bigquery_type: float64
      description: Total da verba indenizatória em Dólar
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      observations:
      is_in_staging:
      is_partition:

number_rows:

metadata_modified: '2022-10-23T22:50:23.226783'
