
# Igual ao dataset.name mas como lower case.
# Exemplos: br_ibge_populacao, br_inep_censo_escolar
dataset_id: br_fgv_igp

table_id: igp_m_mes

# Título da tabela.
title: IGP-M mensal

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description: |
  - O Índice Geral de Preços do Mercado (IGP-M) é um indicador do movimento de preços que cobre todo o processo produtivo, desde preços de matérias-primas agrícolas e industriais, passando pelos preços de produtos intermediários até os de bens e serviços finais. É composto pela média ponderada do Índice de Preços ao Produtor Amplo do Mercado (IPA-M) (60%), do Índice de Preços ao Consumidor do Mercado (IPC-M) (30%) e do Índice Nacional de Custo da Construção do Mercado (INCC-M) (10%). Para efeito de coleta de preços, o IGP-M mede a evolução de preços no período compreendido entre os dias 21 do mês anterior e o dia 20 do mês de referência. Nota: Na época de transição para o Real (R$) - Julho e Agosto de 1994 - a FGV calculou o IGP-2, uma variante do IGP-M mas calculado com valores na nova moeda. O IGP-M reflete a comparação dos preços praticados na nova moeda (R$) com os preços praticados ainda em CR$ convertidos para Reais pela paridade R$ = 2750 CR$. O IGP-2 reflete a comparação dos preços praticados em R$ com os preços praticados ainda em CR$ porém convertidos para Reais pela cotação diária da URV. As 2 formas apresentam resultados distintos.

# As máximas unidades espaciais que a tabela cobre.
# Exemplo:
#   - sa.br
spatial_coverage:
  - sa.br

# Anos cobertos pela tabela.
# Preencher como lista de intervalos.
# Exemplos: ['1995(1)2019'], ['2002(2)2010', '2016', '2020'].
temporal_coverage:
  - 1989-06(1)2022-08

# A unidade temporal com qual a tabela é atualizada.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
update_frequency: month

# Nível de observação da tabela: o que representa cada linha.
observation_level:
  - entity: year
    columns:
      - ano
  - entity: month
    columns:
      - mes

last_updated:
    metadata: '2022-09-12T00:00:00.000000'
    data: '2022-09-12T00:00:00.000000'
    release: '2022-09-12T00:00:00.000000'

# Versão da tabela. Seguindo o padrão de semantic versioning.
# Exemplo: v1.1.3
version: v1.0

# Quem está preenchendo esses metadados?
published_by:
    name: Maurício Fagundes
    email: mauricio.fagundes@basedosdados.org
    github_user: mfagundes
    ckan_user: mfagundes
    website:

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
    name: Maurício Fagundes
    email: mauricio.fagundes@basedosdados.org
    github_user: mfagundes
    ckan_user: mfagundes
    website:

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: |
  - Coleta dos dados a partir da API ipeadatapy;
  - Renomeação das variáveis segundo as diretrizes da BD;
  - Cálculo de valores acumulados e variações, quando couber
  - Junção de dataframes com períodos distintos de coleta

# Url do código de limpeza dos dados.
data_cleaning_code_url: https://github.com/basedosdados/pipelines/blob/master/pipelines/datasets/br_fgv_igp/utils.py

# Organização que ajudou institucionalmente na disponibilização dos dados.
partner_organization:
    name:
    organization_id:

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados

project_id_staging: basedosdados-staging

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions:

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Algumas colunas existirão apenas na tabela final, você as construirá em `publish.sql`.
# Para esses, defina is_in_staging como False.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: ano
      bigquery_type: int64
      description: Ano
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: ano
          column_name: ano
      measurement_unit: year
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: mes
      bigquery_type: int64
      description: Mês
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: mes
          column_name: mes
      measurement_unit: month
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: indice
      bigquery_type: float64
      description: IGP-M no mês (base ago/1994=100)
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: variacao_mensal
      bigquery_type: float64
      description: Variação do índice no mês em relação ao mês anterior
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: variacao_12_meses
      bigquery_type: float64
      description: Variação do índice nos últimos 12 meses
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: variacao_primeiro_decendio
      bigquery_type: float64
      description: Variação nos primeiros 10 dias do mês
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: variacao_segundo_decendio
      bigquery_type: float64
      description: Variação entre o 11° e o 20° dias do mês
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: variacao_acumulada_ano
      bigquery_type: float64
      description: Variação acumulada no ano (a partir de janeiro do ano corrente)
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: indice_fechamento_mensal
      bigquery_type: float64
      description: Índice de fechamento mensal. Elaboração Ipeadata - calculado a partir da média geométrica dos valores dos meses corrente e seguinte da série original do IGP-M
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false

number_rows: 400

metadata_modified:
