# Igual ao dataset.name mas como lower case.
# Exemplos: br_ibge_populacao, br_inep_censo_escolar
dataset_id: br_ibge_pof

table_id: domicilio_2017

# Título da tabela.
title: Domicilio

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description: Microdados do Registro de Domicilio da Pesquisa de Orçamentos Familiares.

# As máximas unidades espaciais que a tabela cobre.
# Exemplo:
#   - sa.br
spatial_coverage:
    - sa.br

# Anos cobertos pela tabela.
# Preencher como lista de intervalos.
# Exemplos: ['1995(1)2019'], ['2002(2)2010', '2016', '2020'].
temporal_coverage:
    - 2017(1)2018

# A unidade temporal com qual a tabela é atualizada.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
update_frequency:
    - ten_years

# Nível de observação da tabela: o que representa cada linha.
observation_level:
    - entity: household
      columns:
        - id_domicilio 

last_updated:
    metadata: '2022-10-19'
    data: '2022-05-19 12:00:00'
    release: '2022-05-19 13:00:00'

# Versão da tabela. Seguindo o padrão de semantic versioning.
# Exemplo: v1.1.3
version: v1.0

# Quem está preenchendo esses metadados?
published_by: 
    name: Arthur de Figueiredo Gusmão
    email: arthur.gusmao@basedosdados.org
    github_user: arthurfg
    ckan_user: arthurfg
    website: 

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by: 
    name: Arthur de Figueiredo Gusmão
    email: arthur.gusmao@basedosdados.org
    github_user: arthurfg
    ckan_user: arthurfg
    website:

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: Renomeação e ordenamento das variáveis, criação de identificadores de Unidade de Consumo, Domicilio e Informante, padronização do código dos produtos para os 5 dígitos.

# Url do código de limpeza dos dados.
data_cleaning_code_url: https://github.com/basedosdados/mais/tree/master/bases/br_ibge_pof/code

# Organização que ajudou institucionalmente na disponibilização dos dados.
partner_organization:
    name:
    organization_id:

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions:
    - sigla_uf

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Algumas colunas existirão apenas na tabela final, você as construirá em `publish.sql`.
# Para esses, defina is_in_staging como False.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: sigla_uf
      bigquery_type: string
      description: Sigla da Unidade da Federação
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: uf
          column_name: sigla
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: true
    - name: situacao
      bigquery_type: string
      description: Situação do Domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: id_estrato
      bigquery_type: string
      description: Identificador dos estratos do plano amostral da pesquisa
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: id_unidade_primaria_amostragem
      bigquery_type: string
      description: Código da Unidade Primária de Amostragem
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: id_domicilio
      bigquery_type: string
      description: Identificador do domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V0201
      bigquery_type: string
      description: Tipo do domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V0202
      bigquery_type: string
      description: Material predominante na construção das paredes externas do domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V0203
      bigquery_type: string
      description: Material predominante na cobertura (telhado) do domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V0204
      bigquery_type: string
      description: Material predominante no piso do domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V0205
      bigquery_type: int64
      description: Número de cômodos
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V0206
      bigquery_type: int64
      description: Número de cômodos servindo permanentemente de dormitórios para
          os moradores do domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V0207
      bigquery_type: string
      description: Forma principal de abastecimento de água no domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V0208
      bigquery_type: string
      description: Frequência de disponibilidade de água da rede geral no últimos
          30 dias
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V0209
      bigquery_type: string
      description: Forma de chegada da água no domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V02101
      bigquery_type: string
      description: Presença de água canalizada aquecida por energia elétrica no domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V02102
      bigquery_type: string
      description: Presença de água canalizada aquecida por gás no domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V02103
      bigquery_type: string
      description: Presença de água canalizada aquecida por energia solar no domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V02104
      bigquery_type: string
      description: Presença de água canalizada aquecida por lenha ou carvão no domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V02105
      bigquery_type: string
      description: Presença de água canalizada aquecida por outra forma no domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V02111
      bigquery_type: int64
      description: Quantidade de banheiros (com chuveiro e vaso sanitário) de uso
          exclusivo dos moradores, incluindo os localizados no terreno ou na propriedade
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V02112
      bigquery_type: int64
      description: Quantidade de banheiros de uso comum a mais de um domicílio no
          terreno ou na propriedade
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V02113
      bigquery_type: string
      description: Presença de sanitário ou buraco para dejeções, inclusive os localizados
          no terreno ou na propriedade
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V0212
      bigquery_type: string
      description: Forma de escoamento dos banheiros, sanitários ou buracos para dejeções
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V0213
      bigquery_type: string
      description: Principal destino dado ao lixo
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V02141
      bigquery_type: string
      description: Presença de energia elétrica proveniente da rede geral
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V02142
      bigquery_type: string
      description: Presença de energia elétrica proveniente de outra origem (gerador,
          placa solar, eólica e etc)
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V0215
      bigquery_type: string
      description: Frequência de disponibilidade de água da rede geral no últimos
          30 dias
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V02161
      bigquery_type: string
      description: Utilização de gás de botijão ou encanado para a preparação de alimentos
          no domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V02162
      bigquery_type: string
      description: Utilização de lenha ou carvão para a preparação de alimentos no
          domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V02163
      bigquery_type: string
      description: Utilização de energia elétrica para a preparação de alimentos no
          domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V02164
      bigquery_type: string
      description: Utilização de outro combustível (óleo, querosene, etc) para a preparação
          de alimentos no domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V0217
      bigquery_type: string
      description: Tipo de condição do domicílio (alugado, próprio, etc)
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V0219
      bigquery_type: string
      description: Tipo do contrato de aluguel
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V0220
      bigquery_type: string
      description: Presença de pavimentação na rua do domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V0221
      bigquery_type: string
      description: Tipo de serviço de distribuição dos correios para o domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: V6199
      bigquery_type: string
      description: Situação de segurança alimentar do domicílio
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: peso
      bigquery_type: float64
      description: Fator de expansão atribuído ao domicílio pertencente a uma UPA
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: peso_final
      bigquery_type: float64
      description: Fator de expansão (peso) ajustado às estimativas populacionais
          de 15 de janeiro de 2018, segundo cada UF e pós estratos definidos
      temporal_coverage:
          - 2017(1)2018
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false

number_rows: 57920

metadata_modified:
