
# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: br-inep-censo-escolar

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Censo Escolar

# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Exemplos: br-ibge, br-tse, br-rj-gov
organization:
    - br-inep

# Descrição do conjunto
notes: "O Censo Escolar é o principal instrumento de coleta de informações da educação\
    \ básica e a mais importante pesquisa estatística educacional brasileira. É coordenado\
    \ pelo Inep e realizado em regime de colaboração entre as secretarias estaduais\
    \ e municipais de educação e com a participação de todas as escolas públicas e\
    \ privadas do país.\r\n\r\nEle abrange as diferentes etapas e modalidades da educação\
    \ básica e profissional:\r\n- Ensino regular (educação infantil, ensino fundamental\
    \ e médio);\r\n- Educação especial – modalidade substitutiva;\r\n- Educação de\
    \ Jovens e Adultos (EJA);\r\n- Educação profissional (cursos técnicos e cursos\
    \ de formação inicial continuada ou qualificação profissional).\r\n\r\nA coleta\
    \ de dados das escolas tem caráter declaratório e é dividida em duas etapas. A\
    \ primeira etapa consiste no preenchimento da Matrícula Inicial, quando ocorre\
    \ a coleta de informações sobre os estabelecimentos de ensino, gestores, turmas,\
    \ alunos e profissionais escolares em sala de aula. A segunda etapa ocorre com\
    \ o preenchimento de informações sobre a Situação do Aluno, e considera os dados\
    \ sobre o movimento e rendimento escolar dos alunos, ao final do ano letivo."

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
    - ciencia-tec-inov
    - cultura-arte
    - economia
    - educacao

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos: fertilidade, preco, desmatamento.
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
    - desigualdade
    - escola
    - escolas
    - indicadores educacionais
    - indicadores socioeconomicos

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified: '2022-02-22T12:02:09.386344'
