
# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list=
organization:
    - br-inep

dataset_id: br_inep_saeb

title: Sistema de Avaliação da Educação Básica (Saeb)

# exemplo: descrição e anotações úteis sobre os dados.
description: Dados referente ao total de acessos a Banda Larga Fixa (também denominado por Serviço Comunicação Multimídia - SCM) provenientes da Anatel. A base inclui ainda, dados de entrada de banda larga nas escolas segundo o Programa Banda Larga nas Escolas e a instalação de backhauls segundo o Plano Nacional de Universalização da Banda Larga. 

# Quais grupos caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
groups: [educacao]

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags: ['alfabetizacao', 'ensino fundamental']

ckan_url:

github_url: https://github.com/basedosdados/mais/tree/master/bases/br_inep_saeb

metadata_modified: