
# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: br-cgu-ebt

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Escala Brasil Transparente

# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Exemplos: br-ibge, br-tse, br-rj-gov
organization: br-cgu

# Descrição do conjunto
notes: A Escala Brasil Transparente(EBT) - Avaliação 360° é uma metodologia para medir a transparência pública em estados e municípios brasileiros. A EBT foi desenvolvida para fornecer os subsídios necessários à Controladoria-Geral da União (CGU) para o exercício das competências que lhe atribuem os artigos 59 da Lei Complementar nº 101/2000 e 41 (I) da Lei de Acesso à Informação, assim como os artigos 68 (II) do Decreto nº 7.724/2012 e 18 (III), do Decreto nº 8.910/2016.

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
  - politica

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos: fertilidade, preco, desmatamento.
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
  - transparencia
  - ranking
  - avaliacao

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified:
