
# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: br-ana-atlas-esgotos

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Atlas Esgotos

# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Exemplos: br-ibge, br-tse, br-rj-gov
organization:
    - br-ana

# Descrição do conjunto
notes: O Atlas Esgotos é o resultado de um trabalho conjunto, desenvolvido sob a coordenação
    da Agência Nacional de Águas (ANA) em parceria com a Secretaria Nacional de Saneamento
    Ambiental do Ministério das Cidades (SNSA/MCidades) e com a colaboração de instituições
    federais, estaduais e municipais de todo o Brasil. Trazendo o olhar da gestão
    dos recursos hídricos, reúne e apresenta informações, diagnósticos e propostas
    de soluções para todas as 5.570 sedes municipais do País, amparados na avaliação
    da situação da coleta e tratamento dos esgotos e do impacto do lançamento desses
    efluentes nos corpos hídricos, com uma visão sistêmica por bacia hidrográfica.
    As propostas de soluções foram elaboradas para o horizonte de 2035, com foco na
    proteção dos recursos hídricos, no seu uso sustentável para depuração de efluentes
    urbanos e na racionalização dos investimentos.

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
    - infra-transp

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos: fertilidade, preco, desmatamento.
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
    - esgoto
    - saneamento

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified: "2022-02-14T01:23:35.315636"
