site_name: Docs

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      # primary: light blue
      # accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      # primary: cyan
      # accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Lato
  favicon: images/bd_minilogo.png
  logo: images/bd_minilogo.png
  features:
    - header.autohide
    - navigation.sections
    - navigation.top
    - toc.integrate
    - navigation.tabs

repo_url: https://github.com/basedosdados/mais
repo_name: basedosdados/mais

extra:
  version: 2.0
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/basedosdados
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/huKWpsVYx4
    - icon: fontawesome/brands/github
      link: https://github.com/basedosdados/mais
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/basedosdados
    - icon: fontawesome/brands/whatsapp
      link: https://chat.whatsapp.com/HXWgdFc1RmwCoblly5KPBZ
    - icon: fontawesome/brands/telegram
      link: https://t.me/joinchat/OKWc3RnClXnq2hq-8o0h_w

  analytics:
    provider: google
    # property: !ENV GOOGLE_ANALYTICS_KEY

markdown_extensions:
  - admonition
  - pymdownx.details
  - mkdocs_click
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed
  - pymdownx.superfences

extra_javascript:
- js/termynal.js
- js/custom.js

nav:
  - Home: index.md
  - BigQuery: access_data_bq.md
  - Pacotes: access_data_packages.md
  - APIs:
    - Python: api_reference_python.md
    - R: api_reference_r.md
    - Stata: api_reference_stata.md
  - Contribua:
    - Dados: colab_data.md
    - Manual de estilo: style_data.md
    - Infraestrutura: colab_infrastructure.md
    - Testes: colab_checks.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            rendering_opt: "value"
          setup_commands:
            - import sys
            - sys.path.insert(0, "python-package")
  - i18n:
      default_language: pt
      docs_structure: folder
      languages:
        pt:
          name: Português
          default: true
          build: true
        en:
          name: English
          build: true
          nav_translations:
            Pacotes: Packages
            Contribua: Contribute
            Dados: Data
            Manual de estilo: Style guide
            Infraestrutura: Infrastructure
            Testes: Tests
        es:
          name: Español
          build: true
          nav_translations:
            Pacotes: Paquetes
            Contribua: Contribuir
            Dados: Datos
            Manual de estilo: Manual de estilo
            Infraestrutura: Infraestructura
            Testes: Pruebas

extra_css:
- css/termynal.css
- css/custom.css
