*DO FILE PARA OS ANOS 2009 2010 2011 2012

*diretorios

*foreach ano in 2009 2010 2011 2012 2013 2014 {
*mkdir "C:/Users/Matheus/Desktop/particionadastata/ano=`ano'"

*foreach estado in AC AL AM AP BA CE DF ES GO MA MG MS MT PA PB PE PI PR RJ RN RO RR RS SC SE SP TO {


*mkdir "C:/Users/Matheus/Desktop/particionadastata/ano=`ano'/sigla_uf=`estado'"
*}
*}

*import delimited "C:\Users\Matheus\Desktop\particionadastata\ano=2018\sigla_uf=DF\microdados_DF.CSV", delimiter(",") encoding(utf8) clear


*CENTRO OESTE - FOI

foreach t in 2009 2010 2011 2012 2013 2014 {

import delimited C:\Users\Matheus\Desktop\docente\a`t'\DOCENTES_CO.CSV, delimiter("|") encoding(utf8) clear

rename *, upper

if t < 2011{
*so dando keep sem cria as que nao existe
keep ANO_CENSO FK_COD_DOCENTE NU_DIA NU_MES NU_ANO NUM_IDADE 
TP_SEXO TP_COR_RACA TP_NACIONALIDADE FK_COD_PAIS_ORIGEM FK_COD_ESTADO_DNASC
FK_COD_MUNICIPIO_DNASC FK_COD_ESTADO_DEND FK_COD_MUNICIPIO_DEND 
FK_COD_AREA_OCDE_1 FK_CLASSE_CURSO_1 
ID_LICENCIATURA_1 ID_COM_PEDAGOGICA_1 NU_ANO_INICIO_1 NU_ANO_CONCLUSAO_1
ID_TIPO_INSTITUICAO_1 FK_COD_IES_1 ID_SITUACAO_CURSO_2 FK_CLASSE_CURSO_2
FK_COD_AREA_OCDE_2 ID_LICENCIATURA_2 ID_COM_PEDAGOGICA_2 NU_ANO_INICIO_2
NU_ANO_CONCLUSAO_2 ID_TIPO_INSTITUICAO_2 FK_COD_IES_2 ID_SITUACAO_CURSO_3
FK_CLASSE_CURSO_3 FK_COD_AREA_OCDE_3 ID_LICENCIATURA_3 ID_COM_PEDAGOGICA_3 NU_ANO_INICIO_3
NU_ANO_CONCLUSAO_3 ID_TIPO_INSTITUICAO_3 FK_COD_IES_3 ID_QUIMICA ID_FISICA
ID_MATEMATICA ID_BIOLOGIA ID_CIENCIAS ID_LINGUA_LITERAT_PORTUGUESA
ID_LINGUA_LITERAT_INGLES ID_LINGUA_LITERAT_ESPANHOL ID_LINGUA_LITERAT_FRANCES ID_LINGUA_LITERAT_OUTRA
ID_LINGUA_LITERAT_INDIGENA ID_ARTES ID_EDUCACAO_FISICA ID_HISTORIA
ID_GEOGRAFIA ID_FILOSOFIA ID_ENSINO_RELIGIOSO ID_ESTUDOS_SOCIAIS
ID_SOCIOLOGIA ID_INFORMATICA_COMPUTACAO ID_PROFISSIONALIZANTE ID_DISC_ATENDIMENTO_ESPECIAIS
ID_DISC_DIVERSIDADE_SOCIO_CULT ID_LIBRAS ID_DISCIPLINAS_PEDAG ID_OUTRAS_DISCIPLINAS
ID_ESPECIALIZACAO ID_MESTRADO ID_DOUTORADO ID_POS_GRADUACAO_NENHUM
ID_ESPECIFICO_CRECHE ID_ESPECIFICO_PRE_ESCOLA ID_ESPECIFICO_ANOS_INICIAIS ID_ESPECIFICO_ANOS_FINAIS
ID_ESPECIFICO_ENS_MEDIO ID_ESPECIFICO_EJA ID_ESPECIFICO_NEC_ESP ID_ESPECIFICO_ED_INDIGENA
ID_ESPECIFICO_NENHUM ID_TIPO_CONTRATACAO ID_TIPO_DOCENTE PK_COD_TURMA FK_COD_TIPO_TURMA FK_COD_ETAPA_ENSINO 
FK_COD_CURSO_PROF PK_COD_ENTIDADE FK_COD_ESTADO FK_COD_MUNICIPIO FK_COD_DISTRITO 
ID_DEPENDENCIA_ADM ID_LOCALIZACAO DESC_CATEGORIA_ESCOLA_PRIVADA ID_CONVENIADA_PP 
ID_TIPO_CONVENIO_PODER_PUBLICO ID_MANT_ESCOLA_PRIVADA_EMP ID_MANT_ESCOLA_PRIVADA_ONG
ID_MANT_ESCOLA_PRIVADA_SIND ID_MANT_ESCOLA_PRIVADA_SIST_S ID_MANT_ESCOLA_PRIVADA_S_FINS
ID_DOCUMENTO_REGULAMENTACAO ID_LOCALIZACAO_DIFERENCIADA ID_EDUCACAO_INDIGENA 

*pondo as que nao existem
gen TP_MEDIACAO_DIDATICO_PEDAGO = ""
gen IN_ESPECIAL_EXCLUSIVA = ""
gen IN_REGULAR = ""
gen IN_EJA = ""
gen IN_PROFISSIONALIZANTE = ""
gen NUM_IDADE_REF_DOCENTE = ""
gen ID_ZONA_RESIDENCIAL = ""
gen ID_POSSUI_NEC_ESPECIAL = ""
gen ID_CEGUEIRA = ""
gen ID_BAIXA_VISAO = ""
gen ID_SURDEZ = ""
gen ID_DEF_AUDITIVA = ""
gen ID_SURDOCEGUEIRA = ""
gen ID_DEF_FISICA = ""
gen ID_DEF_INTELECTUAL = "" 
gen ID_DEF_MULTIPLA = ""
gen FK_COD_ESCOLARIDADE = ""
gen ID_SITUACAO_CURSO_1 = ""
gen ID_SITUACAO_CURSO_2 = ""
gen ID_SITUACAO_CURSO_3 = ""
gen ID_COM_PEDAGOGICA_1 = ""
gen ID_COM_PEDAGOGICA_2 = ""
gen ID_COM_PEDAGOGICA_3 = ""
gen ID_ESPECIFICO_CAMPO = ""
gen ID_ESPECIFICO_AMBIENTAL = ""
gen ID_ESPECIFICO_DIR_HUMANOS = ""
gen ID_ESPECIFICO_DIV_SEXUAL = ""
gen ID_ESPECIFICO_DIR_ADOLESC = ""
gen ID_ESPECIFICO_AFRO = ""
gen ID_ESPECIFICO_OUTROS = ""

}

if `t' == 2011 {

keep ANO_CENSO FK_COD_DOCENTE NU_DIA NU_MES NU_ANO NUM_IDADE 
TP_SEXO TP_COR_RACA TP_NACIONALIDADE FK_COD_PAIS_ORIGEM FK_COD_ESTADO_DNASC
FK_COD_MUNICIPIO_DNASC FK_COD_ESTADO_DEND FK_COD_MUNICIPIO_DEND 
FK_COD_AREA_OCDE_1 FK_CLASSE_CURSO_1 
ID_LICENCIATURA_1 ID_COM_PEDAGOGICA_1 NU_ANO_INICIO_1 NU_ANO_CONCLUSAO_1
ID_TIPO_INSTITUICAO_1 FK_COD_IES_1 ID_SITUACAO_CURSO_2 FK_CLASSE_CURSO_2
FK_COD_AREA_OCDE_2 ID_LICENCIATURA_2 ID_COM_PEDAGOGICA_2 NU_ANO_INICIO_2
NU_ANO_CONCLUSAO_2 ID_TIPO_INSTITUICAO_2 FK_COD_IES_2 ID_SITUACAO_CURSO_3
FK_CLASSE_CURSO_3 FK_COD_AREA_OCDE_3 ID_LICENCIATURA_3 ID_COM_PEDAGOGICA_3 NU_ANO_INICIO_3
NU_ANO_CONCLUSAO_3 ID_TIPO_INSTITUICAO_3 FK_COD_IES_3 ID_QUIMICA ID_FISICA
ID_MATEMATICA ID_BIOLOGIA ID_CIENCIAS ID_LINGUA_LITERAT_PORTUGUESA
ID_LINGUA_LITERAT_INGLES ID_LINGUA_LITERAT_ESPANHOL ID_LINGUA_LITERAT_FRANCES ID_LINGUA_LITERAT_OUTRA
ID_LINGUA_LITERAT_INDIGENA ID_ARTES ID_EDUCACAO_FISICA ID_HISTORIA
ID_GEOGRAFIA ID_FILOSOFIA ID_ENSINO_RELIGIOSO ID_ESTUDOS_SOCIAIS
ID_SOCIOLOGIA ID_INFORMATICA_COMPUTACAO ID_PROFISSIONALIZANTE ID_DISC_ATENDIMENTO_ESPECIAIS
ID_DISC_DIVERSIDADE_SOCIO_CULT ID_LIBRAS ID_DISCIPLINAS_PEDAG ID_OUTRAS_DISCIPLINAS
ID_COM_PEDAGOGICA_1 ID_COM_PEDAGOGICA_2 ID_COM_PEDAGOGICA_3 ID_ESPECIFICO_OUTROS
ID_ESPECIALIZACAO ID_MESTRADO ID_DOUTORADO ID_POS_GRADUACAO_NENHUM
ID_ESPECIFICO_CRECHE ID_ESPECIFICO_PRE_ESCOLA ID_ESPECIFICO_ANOS_INICIAIS ID_ESPECIFICO_ANOS_FINAIS
ID_ESPECIFICO_ENS_MEDIO ID_ESPECIFICO_EJA ID_ESPECIFICO_NEC_ESP ID_ESPECIFICO_ED_INDIGENA
ID_ESPECIFICO_NENHUM ID_TIPO_CONTRATACAO ID_TIPO_DOCENTE PK_COD_TURMA FK_COD_TIPO_TURMA FK_COD_ETAPA_ENSINO 
FK_COD_CURSO_PROF PK_COD_ENTIDADE FK_COD_ESTADO FK_COD_MUNICIPIO FK_COD_DISTRITO 
ID_DEPENDENCIA_ADM ID_LOCALIZACAO DESC_CATEGORIA_ESCOLA_PRIVADA ID_CONVENIADA_PP 
ID_TIPO_CONVENIO_PODER_PUBLICO ID_MANT_ESCOLA_PRIVADA_EMP ID_MANT_ESCOLA_PRIVADA_ONG
ID_MANT_ESCOLA_PRIVADA_SIND ID_MANT_ESCOLA_PRIVADA_SIST_S ID_MANT_ESCOLA_PRIVADA_S_FINS
ID_DOCUMENTO_REGULAMENTACAO ID_LOCALIZACAO_DIFERENCIADA ID_EDUCACAO_INDIGENA 

gen TP_MEDIACAO_DIDATICO_PEDAGO = ""
gen IN_ESPECIAL_EXCLUSIVA = ""
gen IN_REGULAR = ""
gen IN_EJA = ""
gen IN_PROFISSIONALIZANTE = ""
gen NUM_IDADE_REF_DOCENTE = ""
gen ID_ZONA_RESIDENCIAL = ""
gen ID_POSSUI_NEC_ESPECIAL = ""
gen ID_CEGUEIRA = ""
gen ID_BAIXA_VISAO = ""
gen ID_SURDEZ = ""
gen ID_DEF_AUDITIVA = ""
gen ID_SURDOCEGUEIRA = ""
gen ID_DEF_FISICA = ""
gen ID_DEF_INTELECTUAL = "" 
gen ID_DEF_MULTIPLA = ""
gen FK_COD_ESCOLARIDADE = ""
gen ID_SITUACAO_CURSO_1 = ""
gen ID_SITUACAO_CURSO_2 = ""
gen ID_SITUACAO_CURSO_3 = ""
gen ID_ESPECIFICO_CAMPO = ""
gen ID_ESPECIFICO_AMBIENTAL = ""
gen ID_ESPECIFICO_DIR_HUMANOS = ""
gen ID_ESPECIFICO_DIV_SEXUAL = ""
gen ID_ESPECIFICO_DIR_ADOLESC = ""
gen ID_ESPECIFICO_AFRO = ""
gen ID_ESPECIFICO_OUTROS = ""
}



if `t' > 2011 & `t' < 2014{

keep ANO_CENSO FK_COD_DOCENTE NU_DIA NU_MES NU_ANO NUM_IDADE TP_SEXO 
TP_COR_RACA TP_NACIONALIDADE FK_COD_PAIS_ORIGEM FK_COD_ESTADO_DNASC FK_COD_MUNICIPIO_DNASC
FK_COD_ESTADO_DEND FK_COD_MUNICIPIO_DEND ID_ZONA_RESIDENCIAL ID_POSSUI_NEC_ESPECIAL
ID_CEGUEIRA ID_BAIXA_VISAO ID_SURDEZ ID_DEF_AUDITIVA ID_SURDOCEGUEIRA ID_DEF_FISICA
ID_DEF_INTELECTUAL ID_DEF_MULTIPLA FK_COD_ESCOLARIDADE ID_SITUACAO_CURSO_1 FK_CLASSE_CURSO_1
FK_COD_AREA_OCDE_1 ID_LICENCIATURA_1 ID_COM_PEDAGOGICA_1 NU_ANO_INICIO_1 NU_ANO_CONCLUSAO_1
ID_TIPO_INSTITUICAO_1 FK_COD_IES_1 ID_SITUACAO_CURSO_2 FK_CLASSE_CURSO_2 FK_COD_AREA_OCDE_2
ID_LICENCIATURA_2 ID_COM_PEDAGOGICA_2 NU_ANO_INICIO_2 NU_ANO_CONCLUSAO_2 ID_TIPO_INSTITUICAO_2
FK_COD_IES_2 ID_SITUACAO_CURSO_3 FK_CLASSE_CURSO_3 FK_COD_AREA_OCDE_3 ID_LICENCIATURA_3 ID_COM_PEDAGOGICA_3
NU_ANO_INICIO_3 NU_ANO_CONCLUSAO_3 ID_TIPO_INSTITUICAO_3 FK_COD_IES_3 ID_QUIMICA
ID_FISICA ID_MATEMATICA ID_BIOLOGIA ID_CIENCIAS ID_LINGUA_LITERAT_PORTUGUESA ID_LINGUA_LITERAT_INGLES
ID_LINGUA_LITERAT_ESPANHOL ID_LINGUA_LITERAT_FRANCES ID_LINGUA_LITERAT_OUTRA ID_LINGUA_LITERAT_INDIGENA
ID_ARTES ID_EDUCACAO_FISICA ID_HISTORIA ID_GEOGRAFIA ID_FILOSOFIA ID_ENSINO_RELIGIOSO ID_ESTUDOS_SOCIAIS ID_SOCIOLOGIA
ID_INFORMATICA_COMPUTACAO ID_PROFISSIONALIZANTE ID_DISC_ATENDIMENTO_ESPECIAIS ID_DISC_DIVERSIDADE_SOCIO_CULT
ID_LIBRAS ID_DISCIPLINAS_PEDAG ID_OUTRAS_DISCIPLINAS ID_ESPECIALIZACAO ID_MESTRADO ID_DOUTORADO ID_POS_GRADUACAO_NENHUM
ID_ESPECIFICO_CRECHE ID_ESPECIFICO_PRE_ESCOLA ID_ESPECIFICO_ANOS_INICIAIS ID_ESPECIFICO_ANOS_FINAIS
ID_ESPECIFICO_ENS_MEDIO ID_ESPECIFICO_EJA ID_ESPECIFICO_NEC_ESP ID_ESPECIFICO_ED_INDIGENA ID_ESPECIFICO_CAMPO
ID_ESPECIFICO_AMBIENTAL ID_ESPECIFICO_DIR_HUMANOS ID_ESPECIFICO_DIV_SEXUAL ID_ESPECIFICO_DIR_ADOLESC ID_ESPECIFICO_AFRO
ID_ESPECIFICO_OUTROS ID_ESPECIFICO_NENHUM ID_TIPO_DOCENTE ID_TIPO_CONTRATACAO PK_COD_TURMA FK_COD_TIPO_TURMA

gen NUM_IDADE_REF_DOCENTE = ""
gen TP_MEDIACAO_DIDATICO_PEDAGO = ""
gen IN_ESPECIAL_EXCLUSIVA = ""
gen IN_REGULAR = ""
gen IN_EJA = ""
gen IN_PROFISSIONALIZANTE = ""



}

if `t' == 2014 {

keep ANO_CENSO FK_COD_DOCENTE NU_DIA NU_MES NU_ANO NUM_IDADE NUM_IDADE_REF_DOCENTE TP_SEXO 
TP_COR_RACA TP_NACIONALIDADE FK_COD_PAIS_ORIGEM FK_COD_ESTADO_DNASC FK_COD_MUNICIPIO_DNASC
FK_COD_ESTADO_DEND FK_COD_MUNICIPIO_DEND ID_ZONA_RESIDENCIAL ID_POSSUI_NEC_ESPECIAL
ID_CEGUEIRA ID_BAIXA_VISAO ID_SURDEZ ID_DEF_AUDITIVA ID_SURDOCEGUEIRA ID_DEF_FISICA
ID_DEF_INTELECTUAL ID_DEF_MULTIPLA FK_COD_ESCOLARIDADE ID_SITUACAO_CURSO_1 FK_CLASSE_CURSO_1
FK_COD_AREA_OCDE_1 ID_LICENCIATURA_1 ID_COM_PEDAGOGICA_1 NU_ANO_INICIO_1 NU_ANO_CONCLUSAO_1
ID_TIPO_INSTITUICAO_1 FK_COD_IES_1 ID_SITUACAO_CURSO_2 FK_CLASSE_CURSO_2 FK_COD_AREA_OCDE_2
ID_LICENCIATURA_2 ID_COM_PEDAGOGICA_2 NU_ANO_INICIO_2 NU_ANO_CONCLUSAO_2 ID_TIPO_INSTITUICAO_2
FK_COD_IES_2 ID_SITUACAO_CURSO_3 FK_CLASSE_CURSO_3 FK_COD_AREA_OCDE_3 ID_LICENCIATURA_3 ID_COM_PEDAGOGICA_3
NU_ANO_INICIO_3 NU_ANO_CONCLUSAO_3 ID_TIPO_INSTITUICAO_3 FK_COD_IES_3 ID_QUIMICA
ID_FISICA ID_MATEMATICA ID_BIOLOGIA ID_CIENCIAS ID_LINGUA_LITERAT_PORTUGUESA ID_LINGUA_LITERAT_INGLES
ID_LINGUA_LITERAT_ESPANHOL ID_LINGUA_LITERAT_FRANCES ID_LINGUA_LITERAT_OUTRA ID_LINGUA_LITERAT_INDIGENA
ID_ARTES ID_EDUCACAO_FISICA ID_HISTORIA ID_GEOGRAFIA ID_FILOSOFIA ID_ENSINO_RELIGIOSO ID_ESTUDOS_SOCIAIS ID_SOCIOLOGIA
ID_INFORMATICA_COMPUTACAO ID_PROFISSIONALIZANTE ID_DISC_ATENDIMENTO_ESPECIAIS ID_DISC_DIVERSIDADE_SOCIO_CULT
ID_LIBRAS ID_DISCIPLINAS_PEDAG ID_OUTRAS_DISCIPLINAS ID_ESPECIALIZACAO ID_MESTRADO ID_DOUTORADO ID_POS_GRADUACAO_NENHUM
ID_ESPECIFICO_CRECHE ID_ESPECIFICO_PRE_ESCOLA ID_ESPECIFICO_ANOS_INICIAIS ID_ESPECIFICO_ANOS_FINAIS
ID_ESPECIFICO_ENS_MEDIO ID_ESPECIFICO_EJA ID_ESPECIFICO_NEC_ESP ID_ESPECIFICO_ED_INDIGENA ID_ESPECIFICO_CAMPO
ID_ESPECIFICO_AMBIENTAL ID_ESPECIFICO_DIR_HUMANOS ID_ESPECIFICO_DIV_SEXUAL ID_ESPECIFICO_DIR_ADOLESC ID_ESPECIFICO_AFRO
ID_ESPECIFICO_OUTROS ID_ESPECIFICO_NENHUM ID_TIPO_DOCENTE ID_TIPO_CONTRATACAO PK_COD_TURMA FK_COD_TIPO_TURMA
gen TP_MEDIACAO_DIDATICO_PEDAGO = ""
gen IN_ESPECIAL_EXCLUSIVA = ""
gen IN_REGULAR = ""
gen IN_EJA = ""
gen IN_PROFISSIONALIZANTE = ""

}


if `t' >2014 & `t' < 2018{

keep NU_ANO_CENSO CO_PESSOA_FISICA NU_DIA NU_MES NU_ANO NU_IDADE NU_IDADE_REFERENCIA TP_SEXO
TP_COR_RACA TP_NACIONALIDADE CO_PAIS_ORIGEM CO_UF_NASC CO_MUNICIPIO_NASC CO_UF_END
CO_MUNICIPIO_END TP_ZONA_RESIDENCIAL IN_NECESSIDADE_ESPECIAL
IN_CEGUEIRA IN_BAIXA_VISAO IN_SURDEZ IN_DEF_AUDITIVA IN_SURDOCEGUEIRA IN_DEF_FISICA
IN_DEF_INTELECTUAL IN_DEF_MULTIPLA TP_ESCOLARIDADE TP_SITUACAO_CURSO_1
CO_AREA_CURSO_1 CO_CURSO_1 IN_LICENCIATURA_1 IN_COM_PEDAGOGICA_1
NU_ANO_INICIO_1 NU_ANO_CONCLUSAO_1 TP_TIPO_IES_1 CO_IES_1 TP_SITUACAO_CURSO_2
CO_AREA_CURSO_2 CO_CURSO_2 IN_LICENCIATURA_2 IN_COM_PEDAGOGICA_2 NU_ANO_INICIO_2
NU_ANO_CONCLUSAO_2 TP_TIPO_IES_2 CO_IES_2 TP_SITUACAO_CURSO_3 CO_AREA_CURSO_3
CO_CURSO_3 IN_LICENCIATURA_3 IN_COM_PEDAGOGICA_3 NU_ANO_INICIO_3 NU_ANO_CONCLUSAO_3
TP_TIPO_IES_3 CO_IES_3 IN_DISC_QUIMICA IN_DISC_FISICA IN_DISC_MATEMATICA
IN_DISC_BIOLOGIA IN_DISC_CIENCIAS IN_DISC_LINGUA_PORTUGUESA IN_DISC_LINGUA_INGLES
IN_DISC_LINGUA_ESPANHOL IN_DISC_LINGUA_FRANCES IN_DISC_LINGUA_OUTRA
IN_DISC_LINGUA_INDIGENA IN_DISC_ARTES IN_DISC_EDUCACAO_FISICA IN_DISC_HISTORIA
IN_DISC_GEOGRAFIA IN_DISC_FILOSOFIA IN_DISC_ENSINO_RELIGIOSO
IN_DISC_ESTUDOS_SOCIAIS IN_DISC_SOCIOLOGIA IN_DISC_INFORMATICA_COMPUTACAO
IN_DISC_PROFISSIONALIZANTE IN_DISC_ATENDIMENTO_ESPECIAIS IN_DISC_DIVER_SOCIO_CULTURAL
IN_DISC_LIBRAS IN_DISC_PEDAGOGICAS IN_DISC_OUTRAS IN_ESPECIALIZACAO
IN_MESTRADO IN_DOUTORADO IN_POS_NENHUM IN_ESPECIFICO_CRECHE
IN_ESPECIFICO_PRE_ESCOLA IN_ESPECIFICO_ANOS_INICIAIS IN_ESPECIFICO_ANOS_FINAIS
IN_ESPECIFICO_ENS_MEDIO IN_ESPECIFICO_EJA IN_ESPECIFICO_ED_ESPECIAL
IN_ESPECIFICO_ED_INDIGENA IN_ESPECIFICO_CAMPO IN_ESPECIFICO_AMBIENTAL
IN_ESPECIFICO_DIR_HUMANOS IN_ESPECIFICO_DIV_SEXUAL IN_ESPECIFICO_DIR_ADOLESC 
IN_ESPECIFICO_AFRO IN_ESPECIFICO_OUTROS IN_ESPECIFICO_NENHUM TP_TIPO_DOCENTE
TP_TIPO_CONTRATACAO ID_TURMA TP_TIPO_TURMA TP_MEDIACAO_DIDATICO_PEDAGO
IN_ESPECIAL_EXCLUSIVA IN_REGULAR IN_EJA IN_PROFISSIONALIZANTE TP_ETAPA_ENSINO
CO_CURSO_EDUC_PROFISSIONAL CO_ENTIDADE CO_UF CO_MUNICIPIO CO_DISTRITO
TP_DEPENDENCIA TP_LOCALIZACAO TP_CATEGORIA_ESCOLA_PRIVADA IN_CONVENIADA_PP
TP_CONVENIO_PODER_PUBLICO IN_MANT_ESCOLA_PRIVADA_EMP IN_MANT_ESCOLA_PRIVADA_ONG
IN_MANT_ESCOLA_PRIVADA_SIND IN_MANT_ESCOLA_PRIVADA_SIST_S IN_MANT_ESCOLA_PRIVADA_S_FINS
TP_REGULAMENTACAO TP_LOCALIZACAO_DIFERENCIADA IN_EDUCACAO_INDIGENA

}

if `t' > 2018 {

keep NU_ANO_CENSO ID_DOCENTE NU_DIA NU_MES NU_ANO NU_IDADE NU_IDADE_REFERENCIA TP_SEXO
TP_COR_RACA TP_NACIONALIDADE CO_PAIS_ORIGEM CO_UF_NASC CO_MUNICIPIO_NASC CO_UF_END
CO_MUNICIPIO_END TP_ZONA_RESIDENCIAL IN_NECESSIDADE_ESPECIAL
IN_CEGUEIRA IN_BAIXA_VISAO IN_SURDEZ IN_DEF_AUDITIVA IN_SURDOCEGUEIRA IN_DEF_FISICA
IN_DEF_INTELECTUAL IN_DEF_MULTIPLA TP_ESCOLARIDADE TP_SITUACAO_CURSO_1
CO_AREA_CURSO_1 CO_CURSO_1 IN_LICENCIATURA_1 IN_COM_PEDAGOGICA_1
NU_ANO_INICIO_1 NU_ANO_CONCLUSAO_1 TP_TIPO_IES_1 CO_IES_1 TP_SITUACAO_CURSO_2
CO_AREA_CURSO_2 CO_CURSO_2 IN_LICENCIATURA_2 IN_COM_PEDAGOGICA_2 NU_ANO_INICIO_2
NU_ANO_CONCLUSAO_2 TP_TIPO_IES_2 CO_IES_2 TP_SITUACAO_CURSO_3 CO_AREA_CURSO_3
CO_CURSO_3 IN_LICENCIATURA_3 IN_COM_PEDAGOGICA_3 NU_ANO_INICIO_3 NU_ANO_CONCLUSAO_3
TP_TIPO_IES_3 CO_IES_3 IN_DISC_QUIMICA IN_DISC_FISICA IN_DISC_MATEMATICA
IN_DISC_BIOLOGIA IN_DISC_CIENCIAS IN_DISC_LINGUA_PORTUGUESA IN_DISC_LINGUA_INGLES
IN_DISC_LINGUA_ESPANHOL IN_DISC_LINGUA_FRANCES IN_DISC_LINGUA_OUTRA
IN_DISC_LINGUA_INDIGENA IN_DISC_ARTES IN_DISC_EDUCACAO_FISICA IN_DISC_HISTORIA
IN_DISC_GEOGRAFIA IN_DISC_FILOSOFIA IN_DISC_ENSINO_RELIGIOSO
IN_DISC_ESTUDOS_SOCIAIS IN_DISC_SOCIOLOGIA IN_DISC_INFORMATICA_COMPUTACAO
IN_DISC_PROFISSIONALIZANTE IN_DISC_ATENDIMENTO_ESPECIAIS IN_DISC_DIVER_SOCIO_CULTURAL
IN_DISC_LIBRAS IN_DISC_PEDAGOGICAS IN_DISC_OUTRAS IN_ESPECIALIZACAO
IN_MESTRADO IN_DOUTORADO IN_POS_NENHUM IN_ESPECIFICO_CRECHE
IN_ESPECIFICO_PRE_ESCOLA IN_ESPECIFICO_ANOS_INICIAIS IN_ESPECIFICO_ANOS_FINAIS
IN_ESPECIFICO_ENS_MEDIO IN_ESPECIFICO_EJA IN_ESPECIFICO_ED_ESPECIAL
IN_ESPECIFICO_ED_INDIGENA IN_ESPECIFICO_CAMPO IN_ESPECIFICO_AMBIENTAL
IN_ESPECIFICO_DIR_HUMANOS IN_ESPECIFICO_DIV_SEXUAL IN_ESPECIFICO_DIR_ADOLESC 
IN_ESPECIFICO_AFRO IN_ESPECIFICO_OUTROS IN_ESPECIFICO_NENHUM TP_TIPO_DOCENTE
TP_TIPO_CONTRATACAO ID_TURMA TP_TIPO_TURMA TP_MEDIACAO_DIDATICO_PEDAGO
IN_ESPECIAL_EXCLUSIVA IN_REGULAR IN_EJA IN_PROFISSIONALIZANTE TP_ETAPA_ENSINO
CO_CURSO_EDUC_PROFISSIONAL CO_ENTIDADE CO_UF CO_MUNICIPIO CO_DISTRITO
TP_DEPENDENCIA TP_LOCALIZACAO TP_CATEGORIA_ESCOLA_PRIVADA IN_CONVENIADA_PP
TP_CONVENIO_PODER_PUBLICO IN_MANT_ESCOLA_PRIVADA_EMP IN_MANT_ESCOLA_PRIVADA_ONG
IN_MANT_ESCOLA_PRIVADA_SIND IN_MANT_ESCOLA_PRIVADA_SIST_S IN_MANT_ESCOLA_PRIVADA_S_FINS
TP_REGULAMENTACAO TP_LOCALIZACAO_DIFERENCIADA IN_EDUCACAO_INDIGENA

}






}

foreach estado in DF GO MS MT {
	preserve
keep if sigla_uf == "`estado'"
drop ano sigla_uf id_uf
export delimited "C:/Users/Matheus/Desktop/particionadastata/ano=`t'/sigla_uf=`estado'/microdados_`estado'.csv" , replace
	restore
	
	}
}

*NORTE

foreach t in 2014 {

import delimited C:\Users\Matheus\Desktop\docente\a`t'\DOCENTES_NORTE.CSV, delimiter("|") encoding(utf8) clear

rename *, upper

if `t' < 2011{
gen NU_DUR_ATIV_COMP_MESMA_REDE = ""
gen NU_DUR_ATIV_COMP_OUTRAS_REDES = ""
}


if `t'<2012{
gen ID_TRANSP_VANS_KOMBI = ""
gen ID_TRANSP_MICRO_ONIBUS = ""
gen ID_TRANSP_ONIBUS = ""
gen ID_TRANSP_BICICLETA = ""
gen ID_TRANSP_TR_ANIMAL = ""
gen ID_TRANSP_OUTRO_VEICULO = ""
gen ID_TRANSP_EMBAR_ATE5 = ""
gen ID_TRANSP_EMBAR_5A15 = ""
gen ID_TRANSP_EMBAR_15A35 = ""
gen ID_TRANSP_EMBAR_35 = ""
gen ID_TRANSP_TREM_METRO = ""
}

if `t' <2013 {
gen NUM_IDADE_REFERENCIA = ""
gen ID_TIPO_REC_ESP_LEDOR = ""
gen ID_TIPO_REC_ESP_TRANSCRICAO = ""
gen ID_TIPO_REC_ESP_INTERPRETE = ""
gen ID_TIPO_REC_ESP_LIBRAS = ""
gen ID_TIPO_REC_ESP_LABIAL = ""
gen ID_TIPO_REC_ESP_BRAILLE = ""
gen ID_TIPO_REC_ESP_AMPLIADA_16 = ""
gen ID_TIPO_REC_ESP_AMPLIADA_20 = ""
gen ID_TIPO_REC_ESP_AMPLIADA_24  = ""
gen ID_TIPO_REC_ESP_NENHUM = ""
gen ID_INGRESSO_FEDERAIS = ""
}

if `t' <2014 {
replace TP_SEXO = "1" if TP_SEXO == "M"
replace TP_SEXO = "2" if TP_SEXO == "F"
}

keep ANO_CENSO PK_COD_MATRICULA FK_COD_ALUNO NU_DIA NU_MES ///
NU_ANO NUM_IDADE_REFERENCIA NUM_IDADE NU_DUR_ATIV_COMP_MESMA_REDE NU_DUR_ATIV_COMP_OUTRAS_REDES ///
TP_SEXO TP_COR_RACA TP_NACIONALIDADE FK_COD_PAIS_ORIGEM FK_COD_ESTADO_NASC FK_COD_MUNICIPIO_DNASC ///
FK_COD_ESTADO_END FK_COD_MUNICIPIO_END ID_ZONA_RESIDENCIAL ID_TIPO_ATENDIMENTO ID_N_T_E_P ///
ID_RESPONSAVEL_TRANSPORTE ID_TRANSP_VANS_KOMBI ID_TRANSP_MICRO_ONIBUS ID_TRANSP_ONIBUS ///
ID_TRANSP_BICICLETA ID_TRANSP_TR_ANIMAL ID_TRANSP_OUTRO_VEICULO ID_TRANSP_EMBAR_ATE5 ID_TRANSP_EMBAR_5A15 ID_TRANSP_EMBAR_15A35 ///
ID_TRANSP_EMBAR_35 ID_TRANSP_TREM_METRO ID_POSSUI_NEC_ESPECIAL ID_TIPO_NEC_ESP_CEGUEIRA ID_TIPO_NEC_ESP_BAIXA_VISAO ///
ID_TIPO_NEC_ESP_SURDEZ ID_TIPO_NEC_ESP_DEF_AUDITIVA ID_TIPO_NEC_ESP_SURDO_CEGUEIRA ID_TIPO_NEC_ESP_DEF_FISICA ///
ID_TIPO_NEC_ESP_DEF_MENTAL ID_TIPO_NEC_ESP_DEF_MULTIPLAS ID_TIPO_NEC_ESP_AUTISMO ID_TIPO_NEC_ESP_ASPERGER ID_TIPO_NEC_ESP_RETT ///
ID_TIPO_NEC_ESP_TDI ID_TIPO_NEC_ESP_SUPERDOTACAO ID_TIPO_REC_ESP_LEDOR ID_TIPO_REC_ESP_TRANSCRICAO ///
ID_TIPO_REC_ESP_INTERPRETE ID_TIPO_REC_ESP_LIBRAS ID_TIPO_REC_ESP_LABIAL ID_TIPO_REC_ESP_BRAILLE ///
ID_TIPO_REC_ESP_AMPLIADA_16 ID_TIPO_REC_ESP_AMPLIADA_20 ID_TIPO_REC_ESP_AMPLIADA_24 ID_TIPO_REC_ESP_NENHUM ///
ID_INGRESSO_FEDERAIS FK_COD_ETAPA_ENSINO PK_COD_TURMA FK_COD_CURSO_PROF ///
COD_UNIFICADA FK_COD_TIPO_TURMA PK_COD_ENTIDADE COD_MUNICIPIO_ESCOLA FK_COD_ESTADO_ESCOLA ID_DEPENDENCIA_ADM_ESC


rename (ANO_CENSO PK_COD_MATRICULA FK_COD_ALUNO NU_DIA NU_MES ///
NU_ANO NUM_IDADE_REFERENCIA NUM_IDADE NU_DUR_ATIV_COMP_MESMA_REDE NU_DUR_ATIV_COMP_OUTRAS_REDES ///
TP_SEXO TP_COR_RACA TP_NACIONALIDADE FK_COD_PAIS_ORIGEM FK_COD_ESTADO_NASC FK_COD_MUNICIPIO_DNASC ///
FK_COD_ESTADO_END FK_COD_MUNICIPIO_END ID_ZONA_RESIDENCIAL ID_TIPO_ATENDIMENTO ID_N_T_E_P ///
ID_RESPONSAVEL_TRANSPORTE ID_TRANSP_VANS_KOMBI ID_TRANSP_MICRO_ONIBUS ID_TRANSP_ONIBUS ///
ID_TRANSP_BICICLETA ID_TRANSP_TR_ANIMAL ID_TRANSP_OUTRO_VEICULO ID_TRANSP_EMBAR_ATE5 ID_TRANSP_EMBAR_5A15 ID_TRANSP_EMBAR_15A35 ///
ID_TRANSP_EMBAR_35 ID_TRANSP_TREM_METRO ID_POSSUI_NEC_ESPECIAL ID_TIPO_NEC_ESP_CEGUEIRA ID_TIPO_NEC_ESP_BAIXA_VISAO ///
ID_TIPO_NEC_ESP_SURDEZ ID_TIPO_NEC_ESP_DEF_AUDITIVA ID_TIPO_NEC_ESP_SURDO_CEGUEIRA ID_TIPO_NEC_ESP_DEF_FISICA ///
ID_TIPO_NEC_ESP_DEF_MENTAL ID_TIPO_NEC_ESP_DEF_MULTIPLAS ID_TIPO_NEC_ESP_AUTISMO ID_TIPO_NEC_ESP_ASPERGER ID_TIPO_NEC_ESP_RETT ///
ID_TIPO_NEC_ESP_TDI ID_TIPO_NEC_ESP_SUPERDOTACAO ID_TIPO_REC_ESP_LEDOR ID_TIPO_REC_ESP_TRANSCRICAO ///
ID_TIPO_REC_ESP_INTERPRETE ID_TIPO_REC_ESP_LIBRAS ID_TIPO_REC_ESP_LABIAL ID_TIPO_REC_ESP_BRAILLE ///
ID_TIPO_REC_ESP_AMPLIADA_16 ID_TIPO_REC_ESP_AMPLIADA_20 ID_TIPO_REC_ESP_AMPLIADA_24 ID_TIPO_REC_ESP_NENHUM ///
ID_INGRESSO_FEDERAIS FK_COD_ETAPA_ENSINO PK_COD_TURMA FK_COD_CURSO_PROF ///
COD_UNIFICADA FK_COD_TIPO_TURMA PK_COD_ENTIDADE COD_MUNICIPIO_ESCOLA FK_COD_ESTADO_ESCOLA ID_DEPENDENCIA_ADM_ESC) (ano id_matricula id_pessoa_fisica dia_nascimento ///
mes_nascimento ano_nascimento idade_referencia idade ///
duracao_ativ_comp_mesma_rede duracao_ativ_comp_outras_redes ///
sexo cor_raca nacionalidade id_pais_origem ///
id_uf_nascimento id_municipio_nascimento id_uf_endereco ///
id_municipio_endereco zona_residencial outro_local_aula ///
transporte_publico responsavel_transporte ///
transporte_vans_kombi transporte_micro_onibus ///
transporte_onibus transporte_bicicleta ///
transporte_tr_animal transporte_outro_veiculo ///
transporte_embarcacao_ate5 transporte_embarcacao_5a15 ///
transporte_embarcacao_15a35 transporte_embarcacao_35 ///
transporte_trem_metro necessidade_especial cegueira ///
baixa_visao surdez deficiencia_auditiva surdocegueira ///
deficiencia_fisica deficiencia_intelectual ///
deficiencia_multipla autismo sindrome_asperger ///
sindrome_rett transtorno_di superdotacao recurso_ledor /// 
recurso_transcricao recurso_interprete recurso_libras ///
recurso_labial recurso_braille recurso_ampliada_16 ///
recurso_ampliada_20 recurso_ampliada_24 recurso_nenhum ///
ingresso_federais etapa_ensino id_turma ///
id_curso_educ_profissional unificada tipo_turma ///
id_escola id_municipio id_uf rede)

tostring id_uf, replace
gen sigla_uf = "RO" if id_uf == "11"
replace sigla_uf = "RR" if id_uf == "14"
replace sigla_uf = "AM" if id_uf == "13"
replace sigla_uf = "AP" if id_uf == "16"
replace sigla_uf = "AC" if id_uf == "12"
replace sigla_uf = "TO" if id_uf == "17"
replace sigla_uf = "PA" if id_uf == "15"

tostring rede, replace
replace rede = "federal" if rede == "1"
replace rede = "estadual" if rede == "2" 
replace rede = "municipal" if rede == "3"
replace rede = "privada" if rede == "4"

order id_matricula id_pessoa_fisica dia_nascimento mes_nascimento ano_nascimento idade_referencia idade duracao_ativ_comp_mesma_rede duracao_ativ_comp_outras_redes sexo cor_raca nacionalidade id_pais_origem id_uf_nascimento id_municipio_nascimento id_uf_endereco id_municipio_endereco zona_residencial outro_local_aula transporte_publico responsavel_transporte transporte_vans_kombi transporte_micro_onibus transporte_onibus transporte_bicicleta transporte_tr_animal transporte_outro_veiculo transporte_embarcacao_ate5 transporte_embarcacao_5a15 transporte_embarcacao_15a35 transporte_embarcacao_35 transporte_trem_metro necessidade_especial cegueira baixa_visao surdez deficiencia_auditiva surdocegueira deficiencia_fisica deficiencia_intelectual deficiencia_multipla autismo sindrome_asperger sindrome_rett transtorno_di superdotacao recurso_ledor recurso_transcricao recurso_interprete recurso_libras recurso_labial recurso_braille recurso_ampliada_16 recurso_ampliada_20 recurso_ampliada_24 recurso_nenhum ingresso_federais etapa_ensino id_turma id_curso_educ_profissional unificada tipo_turma id_escola id_municipio rede


foreach estado in RO RR AM AC AP TO PA {
	preserve
keep if sigla_uf == "`estado'"
drop ano sigla_uf id_uf
export delimited "C:/Users/Matheus/Desktop/particionadastata/ano=`t'/sigla_uf=`estado'/microdados_`estado'.csv" , replace
	restore
	
	}
}

*SUDESTE --------------------------------------------------

foreach t in 2014 {

import delimited C:\Users\Matheus\Desktop\docente\a`t'\DOCENTES_SUDESTE.CSV, delimiter("|") encoding(utf8) clear

rename *, upper

if `t' < 2011{
gen NU_DUR_ATIV_COMP_MESMA_REDE = ""
gen NU_DUR_ATIV_COMP_OUTRAS_REDES = ""
}


if `t'<2012{
gen ID_TRANSP_VANS_KOMBI = ""
gen ID_TRANSP_MICRO_ONIBUS = ""
gen ID_TRANSP_ONIBUS = ""
gen ID_TRANSP_BICICLETA = ""
gen ID_TRANSP_TR_ANIMAL = ""
gen ID_TRANSP_OUTRO_VEICULO = ""
gen ID_TRANSP_EMBAR_ATE5 = ""
gen ID_TRANSP_EMBAR_5A15 = ""
gen ID_TRANSP_EMBAR_15A35 = ""
gen ID_TRANSP_EMBAR_35 = ""
gen ID_TRANSP_TREM_METRO = ""
}

if `t' <2013 {
gen NUM_IDADE_REFERENCIA = ""
gen ID_TIPO_REC_ESP_LEDOR = ""
gen ID_TIPO_REC_ESP_TRANSCRICAO = ""
gen ID_TIPO_REC_ESP_INTERPRETE = ""
gen ID_TIPO_REC_ESP_LIBRAS = ""
gen ID_TIPO_REC_ESP_LABIAL = ""
gen ID_TIPO_REC_ESP_BRAILLE = ""
gen ID_TIPO_REC_ESP_AMPLIADA_16 = ""
gen ID_TIPO_REC_ESP_AMPLIADA_20 = ""
gen ID_TIPO_REC_ESP_AMPLIADA_24  = ""
gen ID_TIPO_REC_ESP_NENHUM = ""
gen ID_INGRESSO_FEDERAIS = ""
}

if `t' <2014 {
replace TP_SEXO = "1" if TP_SEXO == "M"
replace TP_SEXO = "2" if TP_SEXO == "F"
}

keep ANO_CENSO PK_COD_MATRICULA FK_COD_ALUNO NU_DIA NU_MES ///
NU_ANO NUM_IDADE_REFERENCIA NUM_IDADE NU_DUR_ATIV_COMP_MESMA_REDE NU_DUR_ATIV_COMP_OUTRAS_REDES ///
TP_SEXO TP_COR_RACA TP_NACIONALIDADE FK_COD_PAIS_ORIGEM FK_COD_ESTADO_NASC FK_COD_MUNICIPIO_DNASC ///
FK_COD_ESTADO_END FK_COD_MUNICIPIO_END ID_ZONA_RESIDENCIAL ID_TIPO_ATENDIMENTO ID_N_T_E_P ///
ID_RESPONSAVEL_TRANSPORTE ID_TRANSP_VANS_KOMBI ID_TRANSP_MICRO_ONIBUS ID_TRANSP_ONIBUS ///
ID_TRANSP_BICICLETA ID_TRANSP_TR_ANIMAL ID_TRANSP_OUTRO_VEICULO ID_TRANSP_EMBAR_ATE5 ID_TRANSP_EMBAR_5A15 ID_TRANSP_EMBAR_15A35 ///
ID_TRANSP_EMBAR_35 ID_TRANSP_TREM_METRO ID_POSSUI_NEC_ESPECIAL ID_TIPO_NEC_ESP_CEGUEIRA ID_TIPO_NEC_ESP_BAIXA_VISAO ///
ID_TIPO_NEC_ESP_SURDEZ ID_TIPO_NEC_ESP_DEF_AUDITIVA ID_TIPO_NEC_ESP_SURDO_CEGUEIRA ID_TIPO_NEC_ESP_DEF_FISICA ///
ID_TIPO_NEC_ESP_DEF_MENTAL ID_TIPO_NEC_ESP_DEF_MULTIPLAS ID_TIPO_NEC_ESP_AUTISMO ID_TIPO_NEC_ESP_ASPERGER ID_TIPO_NEC_ESP_RETT ///
ID_TIPO_NEC_ESP_TDI ID_TIPO_NEC_ESP_SUPERDOTACAO ID_TIPO_REC_ESP_LEDOR ID_TIPO_REC_ESP_TRANSCRICAO ///
ID_TIPO_REC_ESP_INTERPRETE ID_TIPO_REC_ESP_LIBRAS ID_TIPO_REC_ESP_LABIAL ID_TIPO_REC_ESP_BRAILLE ///
ID_TIPO_REC_ESP_AMPLIADA_16 ID_TIPO_REC_ESP_AMPLIADA_20 ID_TIPO_REC_ESP_AMPLIADA_24 ID_TIPO_REC_ESP_NENHUM ///
ID_INGRESSO_FEDERAIS FK_COD_ETAPA_ENSINO PK_COD_TURMA FK_COD_CURSO_PROF ///
COD_UNIFICADA FK_COD_TIPO_TURMA PK_COD_ENTIDADE COD_MUNICIPIO_ESCOLA FK_COD_ESTADO_ESCOLA ID_DEPENDENCIA_ADM_ESC


rename (ANO_CENSO PK_COD_MATRICULA FK_COD_ALUNO NU_DIA NU_MES ///
NU_ANO NUM_IDADE_REFERENCIA NUM_IDADE NU_DUR_ATIV_COMP_MESMA_REDE NU_DUR_ATIV_COMP_OUTRAS_REDES ///
TP_SEXO TP_COR_RACA TP_NACIONALIDADE FK_COD_PAIS_ORIGEM FK_COD_ESTADO_NASC FK_COD_MUNICIPIO_DNASC ///
FK_COD_ESTADO_END FK_COD_MUNICIPIO_END ID_ZONA_RESIDENCIAL ID_TIPO_ATENDIMENTO ID_N_T_E_P ///
ID_RESPONSAVEL_TRANSPORTE ID_TRANSP_VANS_KOMBI ID_TRANSP_MICRO_ONIBUS ID_TRANSP_ONIBUS ///
ID_TRANSP_BICICLETA ID_TRANSP_TR_ANIMAL ID_TRANSP_OUTRO_VEICULO ID_TRANSP_EMBAR_ATE5 ID_TRANSP_EMBAR_5A15 ID_TRANSP_EMBAR_15A35 ///
ID_TRANSP_EMBAR_35 ID_TRANSP_TREM_METRO ID_POSSUI_NEC_ESPECIAL ID_TIPO_NEC_ESP_CEGUEIRA ID_TIPO_NEC_ESP_BAIXA_VISAO ///
ID_TIPO_NEC_ESP_SURDEZ ID_TIPO_NEC_ESP_DEF_AUDITIVA ID_TIPO_NEC_ESP_SURDO_CEGUEIRA ID_TIPO_NEC_ESP_DEF_FISICA ///
ID_TIPO_NEC_ESP_DEF_MENTAL ID_TIPO_NEC_ESP_DEF_MULTIPLAS ID_TIPO_NEC_ESP_AUTISMO ID_TIPO_NEC_ESP_ASPERGER ID_TIPO_NEC_ESP_RETT ///
ID_TIPO_NEC_ESP_TDI ID_TIPO_NEC_ESP_SUPERDOTACAO ID_TIPO_REC_ESP_LEDOR ID_TIPO_REC_ESP_TRANSCRICAO ///
ID_TIPO_REC_ESP_INTERPRETE ID_TIPO_REC_ESP_LIBRAS ID_TIPO_REC_ESP_LABIAL ID_TIPO_REC_ESP_BRAILLE ///
ID_TIPO_REC_ESP_AMPLIADA_16 ID_TIPO_REC_ESP_AMPLIADA_20 ID_TIPO_REC_ESP_AMPLIADA_24 ID_TIPO_REC_ESP_NENHUM ///
ID_INGRESSO_FEDERAIS FK_COD_ETAPA_ENSINO PK_COD_TURMA FK_COD_CURSO_PROF ///
COD_UNIFICADA FK_COD_TIPO_TURMA PK_COD_ENTIDADE COD_MUNICIPIO_ESCOLA FK_COD_ESTADO_ESCOLA ID_DEPENDENCIA_ADM_ESC) (ano id_matricula id_pessoa_fisica dia_nascimento ///
mes_nascimento ano_nascimento idade_referencia idade ///
duracao_ativ_comp_mesma_rede duracao_ativ_comp_outras_redes ///
sexo cor_raca nacionalidade id_pais_origem ///
id_uf_nascimento id_municipio_nascimento id_uf_endereco ///
id_municipio_endereco zona_residencial outro_local_aula ///
transporte_publico responsavel_transporte ///
transporte_vans_kombi transporte_micro_onibus ///
transporte_onibus transporte_bicicleta ///
transporte_tr_animal transporte_outro_veiculo ///
transporte_embarcacao_ate5 transporte_embarcacao_5a15 ///
transporte_embarcacao_15a35 transporte_embarcacao_35 ///
transporte_trem_metro necessidade_especial cegueira ///
baixa_visao surdez deficiencia_auditiva surdocegueira ///
deficiencia_fisica deficiencia_intelectual ///
deficiencia_multipla autismo sindrome_asperger ///
sindrome_rett transtorno_di superdotacao recurso_ledor /// 
recurso_transcricao recurso_interprete recurso_libras ///
recurso_labial recurso_braille recurso_ampliada_16 ///
recurso_ampliada_20 recurso_ampliada_24 recurso_nenhum ///
ingresso_federais etapa_ensino id_turma ///
id_curso_educ_profissional unificada tipo_turma ///
id_escola id_municipio id_uf rede)

tostring id_uf, replace
gen sigla_uf = "SP" if id_uf == "31"
replace sigla_uf = "MG" if id_uf == "33"
replace sigla_uf = "ES" if id_uf == "34"
replace sigla_uf = "RJ" if id_uf == "35"

tostring rede, replace
replace rede = "federal" if rede == "1"
replace rede = "estadual" if rede == "2" 
replace rede = "municipal" if rede == "3"
replace rede = "privada" if rede == "4"

order id_matricula id_pessoa_fisica dia_nascimento mes_nascimento ano_nascimento idade_referencia idade duracao_ativ_comp_mesma_rede duracao_ativ_comp_outras_redes sexo cor_raca nacionalidade id_pais_origem id_uf_nascimento id_municipio_nascimento id_uf_endereco id_municipio_endereco zona_residencial outro_local_aula transporte_publico responsavel_transporte transporte_vans_kombi transporte_micro_onibus transporte_onibus transporte_bicicleta transporte_tr_animal transporte_outro_veiculo transporte_embarcacao_ate5 transporte_embarcacao_5a15 transporte_embarcacao_15a35 transporte_embarcacao_35 transporte_trem_metro necessidade_especial cegueira baixa_visao surdez deficiencia_auditiva surdocegueira deficiencia_fisica deficiencia_intelectual deficiencia_multipla autismo sindrome_asperger sindrome_rett transtorno_di superdotacao recurso_ledor recurso_transcricao recurso_interprete recurso_libras recurso_labial recurso_braille recurso_ampliada_16 recurso_ampliada_20 recurso_ampliada_24 recurso_nenhum ingresso_federais etapa_ensino id_turma id_curso_educ_profissional unificada tipo_turma id_escola id_municipio rede


foreach estado in SP MG RJ ES {
	preserve
keep if sigla_uf == "`estado'"
drop ano sigla_uf id_uf
export delimited "C:/Users/Matheus/Desktop/particionadastata/ano=`t'/sigla_uf=`estado'/microdados_`estado'.csv" , replace
	restore
	
	}
}
*-------------------------------------------------------

*SUL
foreach t in 2014 {

import delimited C:\Users\Matheus\Desktop\docente\a`t'\DOCENTES_SUL.CSV, delimiter("|") encoding(utf8) clear

rename *, upper

if `t' < 2011{
gen NU_DUR_ATIV_COMP_MESMA_REDE = ""
gen NU_DUR_ATIV_COMP_OUTRAS_REDES = ""
}


if `t'<2012{
gen ID_TRANSP_VANS_KOMBI = ""
gen ID_TRANSP_MICRO_ONIBUS = ""
gen ID_TRANSP_ONIBUS = ""
gen ID_TRANSP_BICICLETA = ""
gen ID_TRANSP_TR_ANIMAL = ""
gen ID_TRANSP_OUTRO_VEICULO = ""
gen ID_TRANSP_EMBAR_ATE5 = ""
gen ID_TRANSP_EMBAR_5A15 = ""
gen ID_TRANSP_EMBAR_15A35 = ""
gen ID_TRANSP_EMBAR_35 = ""
gen ID_TRANSP_TREM_METRO = ""
}

if `t' <2013 {
gen NUM_IDADE_REFERENCIA = ""
gen ID_TIPO_REC_ESP_LEDOR = ""
gen ID_TIPO_REC_ESP_TRANSCRICAO = ""
gen ID_TIPO_REC_ESP_INTERPRETE = ""
gen ID_TIPO_REC_ESP_LIBRAS = ""
gen ID_TIPO_REC_ESP_LABIAL = ""
gen ID_TIPO_REC_ESP_BRAILLE = ""
gen ID_TIPO_REC_ESP_AMPLIADA_16 = ""
gen ID_TIPO_REC_ESP_AMPLIADA_20 = ""
gen ID_TIPO_REC_ESP_AMPLIADA_24  = ""
gen ID_TIPO_REC_ESP_NENHUM = ""
gen ID_INGRESSO_FEDERAIS = ""
}

if `t' <2014 {
replace TP_SEXO = "1" if TP_SEXO == "M"
replace TP_SEXO = "2" if TP_SEXO == "F"
}

keep ANO_CENSO PK_COD_MATRICULA FK_COD_ALUNO NU_DIA NU_MES ///
NU_ANO NUM_IDADE_REFERENCIA NUM_IDADE NU_DUR_ATIV_COMP_MESMA_REDE NU_DUR_ATIV_COMP_OUTRAS_REDES ///
TP_SEXO TP_COR_RACA TP_NACIONALIDADE FK_COD_PAIS_ORIGEM FK_COD_ESTADO_NASC FK_COD_MUNICIPIO_DNASC ///
FK_COD_ESTADO_END FK_COD_MUNICIPIO_END ID_ZONA_RESIDENCIAL ID_TIPO_ATENDIMENTO ID_N_T_E_P ///
ID_RESPONSAVEL_TRANSPORTE ID_TRANSP_VANS_KOMBI ID_TRANSP_MICRO_ONIBUS ID_TRANSP_ONIBUS ///
ID_TRANSP_BICICLETA ID_TRANSP_TR_ANIMAL ID_TRANSP_OUTRO_VEICULO ID_TRANSP_EMBAR_ATE5 ID_TRANSP_EMBAR_5A15 ID_TRANSP_EMBAR_15A35 ///
ID_TRANSP_EMBAR_35 ID_TRANSP_TREM_METRO ID_POSSUI_NEC_ESPECIAL ID_TIPO_NEC_ESP_CEGUEIRA ID_TIPO_NEC_ESP_BAIXA_VISAO ///
ID_TIPO_NEC_ESP_SURDEZ ID_TIPO_NEC_ESP_DEF_AUDITIVA ID_TIPO_NEC_ESP_SURDO_CEGUEIRA ID_TIPO_NEC_ESP_DEF_FISICA ///
ID_TIPO_NEC_ESP_DEF_MENTAL ID_TIPO_NEC_ESP_DEF_MULTIPLAS ID_TIPO_NEC_ESP_AUTISMO ID_TIPO_NEC_ESP_ASPERGER ID_TIPO_NEC_ESP_RETT ///
ID_TIPO_NEC_ESP_TDI ID_TIPO_NEC_ESP_SUPERDOTACAO ID_TIPO_REC_ESP_LEDOR ID_TIPO_REC_ESP_TRANSCRICAO ///
ID_TIPO_REC_ESP_INTERPRETE ID_TIPO_REC_ESP_LIBRAS ID_TIPO_REC_ESP_LABIAL ID_TIPO_REC_ESP_BRAILLE ///
ID_TIPO_REC_ESP_AMPLIADA_16 ID_TIPO_REC_ESP_AMPLIADA_20 ID_TIPO_REC_ESP_AMPLIADA_24 ID_TIPO_REC_ESP_NENHUM ///
ID_INGRESSO_FEDERAIS FK_COD_ETAPA_ENSINO PK_COD_TURMA FK_COD_CURSO_PROF ///
COD_UNIFICADA FK_COD_TIPO_TURMA PK_COD_ENTIDADE COD_MUNICIPIO_ESCOLA FK_COD_ESTADO_ESCOLA ID_DEPENDENCIA_ADM_ESC


rename (ANO_CENSO PK_COD_MATRICULA FK_COD_ALUNO NU_DIA NU_MES ///
NU_ANO NUM_IDADE_REFERENCIA NUM_IDADE NU_DUR_ATIV_COMP_MESMA_REDE NU_DUR_ATIV_COMP_OUTRAS_REDES ///
TP_SEXO TP_COR_RACA TP_NACIONALIDADE FK_COD_PAIS_ORIGEM FK_COD_ESTADO_NASC FK_COD_MUNICIPIO_DNASC ///
FK_COD_ESTADO_END FK_COD_MUNICIPIO_END ID_ZONA_RESIDENCIAL ID_TIPO_ATENDIMENTO ID_N_T_E_P ///
ID_RESPONSAVEL_TRANSPORTE ID_TRANSP_VANS_KOMBI ID_TRANSP_MICRO_ONIBUS ID_TRANSP_ONIBUS ///
ID_TRANSP_BICICLETA ID_TRANSP_TR_ANIMAL ID_TRANSP_OUTRO_VEICULO ID_TRANSP_EMBAR_ATE5 ID_TRANSP_EMBAR_5A15 ID_TRANSP_EMBAR_15A35 ///
ID_TRANSP_EMBAR_35 ID_TRANSP_TREM_METRO ID_POSSUI_NEC_ESPECIAL ID_TIPO_NEC_ESP_CEGUEIRA ID_TIPO_NEC_ESP_BAIXA_VISAO ///
ID_TIPO_NEC_ESP_SURDEZ ID_TIPO_NEC_ESP_DEF_AUDITIVA ID_TIPO_NEC_ESP_SURDO_CEGUEIRA ID_TIPO_NEC_ESP_DEF_FISICA ///
ID_TIPO_NEC_ESP_DEF_MENTAL ID_TIPO_NEC_ESP_DEF_MULTIPLAS ID_TIPO_NEC_ESP_AUTISMO ID_TIPO_NEC_ESP_ASPERGER ID_TIPO_NEC_ESP_RETT ///
ID_TIPO_NEC_ESP_TDI ID_TIPO_NEC_ESP_SUPERDOTACAO ID_TIPO_REC_ESP_LEDOR ID_TIPO_REC_ESP_TRANSCRICAO ///
ID_TIPO_REC_ESP_INTERPRETE ID_TIPO_REC_ESP_LIBRAS ID_TIPO_REC_ESP_LABIAL ID_TIPO_REC_ESP_BRAILLE ///
ID_TIPO_REC_ESP_AMPLIADA_16 ID_TIPO_REC_ESP_AMPLIADA_20 ID_TIPO_REC_ESP_AMPLIADA_24 ID_TIPO_REC_ESP_NENHUM ///
ID_INGRESSO_FEDERAIS FK_COD_ETAPA_ENSINO PK_COD_TURMA FK_COD_CURSO_PROF ///
COD_UNIFICADA FK_COD_TIPO_TURMA PK_COD_ENTIDADE COD_MUNICIPIO_ESCOLA FK_COD_ESTADO_ESCOLA ID_DEPENDENCIA_ADM_ESC) (ano id_matricula id_pessoa_fisica dia_nascimento ///
mes_nascimento ano_nascimento idade_referencia idade ///
duracao_ativ_comp_mesma_rede duracao_ativ_comp_outras_redes ///
sexo cor_raca nacionalidade id_pais_origem ///
id_uf_nascimento id_municipio_nascimento id_uf_endereco ///
id_municipio_endereco zona_residencial outro_local_aula ///
transporte_publico responsavel_transporte ///
transporte_vans_kombi transporte_micro_onibus ///
transporte_onibus transporte_bicicleta ///
transporte_tr_animal transporte_outro_veiculo ///
transporte_embarcacao_ate5 transporte_embarcacao_5a15 ///
transporte_embarcacao_15a35 transporte_embarcacao_35 ///
transporte_trem_metro necessidade_especial cegueira ///
baixa_visao surdez deficiencia_auditiva surdocegueira ///
deficiencia_fisica deficiencia_intelectual ///
deficiencia_multipla autismo sindrome_asperger ///
sindrome_rett transtorno_di superdotacao recurso_ledor /// 
recurso_transcricao recurso_interprete recurso_libras ///
recurso_labial recurso_braille recurso_ampliada_16 ///
recurso_ampliada_20 recurso_ampliada_24 recurso_nenhum ///
ingresso_federais etapa_ensino id_turma ///
id_curso_educ_profissional unificada tipo_turma ///
id_escola id_municipio id_uf rede)

tostring id_uf, replace
gen sigla_uf = "PR" if id_uf == "41"
replace sigla_uf = "RS" if id_uf == "43"
replace sigla_uf = "SC" if id_uf == "42"

tostring rede, replace
replace rede = "federal" if rede == "1"
replace rede = "estadual" if rede == "2" 
replace rede = "municipal" if rede == "3"
replace rede = "privada" if rede == "4"

order id_matricula id_pessoa_fisica dia_nascimento mes_nascimento ano_nascimento idade_referencia idade duracao_ativ_comp_mesma_rede duracao_ativ_comp_outras_redes sexo cor_raca nacionalidade id_pais_origem id_uf_nascimento id_municipio_nascimento id_uf_endereco id_municipio_endereco zona_residencial outro_local_aula transporte_publico responsavel_transporte transporte_vans_kombi transporte_micro_onibus transporte_onibus transporte_bicicleta transporte_tr_animal transporte_outro_veiculo transporte_embarcacao_ate5 transporte_embarcacao_5a15 transporte_embarcacao_15a35 transporte_embarcacao_35 transporte_trem_metro necessidade_especial cegueira baixa_visao surdez deficiencia_auditiva surdocegueira deficiencia_fisica deficiencia_intelectual deficiencia_multipla autismo sindrome_asperger sindrome_rett transtorno_di superdotacao recurso_ledor recurso_transcricao recurso_interprete recurso_libras recurso_labial recurso_braille recurso_ampliada_16 recurso_ampliada_20 recurso_ampliada_24 recurso_nenhum ingresso_federais etapa_ensino id_turma id_curso_educ_profissional unificada tipo_turma id_escola id_municipio rede


foreach estado in PR SC RS {
	preserve
keep if sigla_uf == "`estado'"
drop ano sigla_uf id_uf
export delimited "C:/Users/Matheus/Desktop/particionadastata/ano=`t'/sigla_uf=`estado'/microdados_`estado'.csv" , replace
	restore
	
	}
}

*NORDESTE

foreach t in 2014 {

import delimited C:\Users\Matheus\Desktop\docente\a`t'\DOCENTES_NORDESTE.CSV, delimiter("|") encoding(utf8) clear

rename *, upper

if `t' < 2011{
gen NU_DUR_ATIV_COMP_MESMA_REDE = ""
gen NU_DUR_ATIV_COMP_OUTRAS_REDES = ""
}


if `t'<2012{
gen ID_TRANSP_VANS_KOMBI = ""
gen ID_TRANSP_MICRO_ONIBUS = ""
gen ID_TRANSP_ONIBUS = ""
gen ID_TRANSP_BICICLETA = ""
gen ID_TRANSP_TR_ANIMAL = ""
gen ID_TRANSP_OUTRO_VEICULO = ""
gen ID_TRANSP_EMBAR_ATE5 = ""
gen ID_TRANSP_EMBAR_5A15 = ""
gen ID_TRANSP_EMBAR_15A35 = ""
gen ID_TRANSP_EMBAR_35 = ""
gen ID_TRANSP_TREM_METRO = ""
}

if `t' <2013 {
gen NUM_IDADE_REFERENCIA = ""
gen ID_TIPO_REC_ESP_LEDOR = ""
gen ID_TIPO_REC_ESP_TRANSCRICAO = ""
gen ID_TIPO_REC_ESP_INTERPRETE = ""
gen ID_TIPO_REC_ESP_LIBRAS = ""
gen ID_TIPO_REC_ESP_LABIAL = ""
gen ID_TIPO_REC_ESP_BRAILLE = ""
gen ID_TIPO_REC_ESP_AMPLIADA_16 = ""
gen ID_TIPO_REC_ESP_AMPLIADA_20 = ""
gen ID_TIPO_REC_ESP_AMPLIADA_24  = ""
gen ID_TIPO_REC_ESP_NENHUM = ""
gen ID_INGRESSO_FEDERAIS = ""
}

if `t' <2014 {
replace TP_SEXO = "1" if TP_SEXO == "M"
replace TP_SEXO = "2" if TP_SEXO == "F"
}

keep ANO_CENSO PK_COD_MATRICULA FK_COD_ALUNO NU_DIA NU_MES ///
NU_ANO NUM_IDADE_REFERENCIA NUM_IDADE NU_DUR_ATIV_COMP_MESMA_REDE NU_DUR_ATIV_COMP_OUTRAS_REDES ///
TP_SEXO TP_COR_RACA TP_NACIONALIDADE FK_COD_PAIS_ORIGEM FK_COD_ESTADO_NASC FK_COD_MUNICIPIO_DNASC ///
FK_COD_ESTADO_END FK_COD_MUNICIPIO_END ID_ZONA_RESIDENCIAL ID_TIPO_ATENDIMENTO ID_N_T_E_P ///
ID_RESPONSAVEL_TRANSPORTE ID_TRANSP_VANS_KOMBI ID_TRANSP_MICRO_ONIBUS ID_TRANSP_ONIBUS ///
ID_TRANSP_BICICLETA ID_TRANSP_TR_ANIMAL ID_TRANSP_OUTRO_VEICULO ID_TRANSP_EMBAR_ATE5 ID_TRANSP_EMBAR_5A15 ID_TRANSP_EMBAR_15A35 ///
ID_TRANSP_EMBAR_35 ID_TRANSP_TREM_METRO ID_POSSUI_NEC_ESPECIAL ID_TIPO_NEC_ESP_CEGUEIRA ID_TIPO_NEC_ESP_BAIXA_VISAO ///
ID_TIPO_NEC_ESP_SURDEZ ID_TIPO_NEC_ESP_DEF_AUDITIVA ID_TIPO_NEC_ESP_SURDO_CEGUEIRA ID_TIPO_NEC_ESP_DEF_FISICA ///
ID_TIPO_NEC_ESP_DEF_MENTAL ID_TIPO_NEC_ESP_DEF_MULTIPLAS ID_TIPO_NEC_ESP_AUTISMO ID_TIPO_NEC_ESP_ASPERGER ID_TIPO_NEC_ESP_RETT ///
ID_TIPO_NEC_ESP_TDI ID_TIPO_NEC_ESP_SUPERDOTACAO ID_TIPO_REC_ESP_LEDOR ID_TIPO_REC_ESP_TRANSCRICAO ///
ID_TIPO_REC_ESP_INTERPRETE ID_TIPO_REC_ESP_LIBRAS ID_TIPO_REC_ESP_LABIAL ID_TIPO_REC_ESP_BRAILLE ///
ID_TIPO_REC_ESP_AMPLIADA_16 ID_TIPO_REC_ESP_AMPLIADA_20 ID_TIPO_REC_ESP_AMPLIADA_24 ID_TIPO_REC_ESP_NENHUM ///
ID_INGRESSO_FEDERAIS FK_COD_ETAPA_ENSINO PK_COD_TURMA FK_COD_CURSO_PROF ///
COD_UNIFICADA FK_COD_TIPO_TURMA PK_COD_ENTIDADE COD_MUNICIPIO_ESCOLA FK_COD_ESTADO_ESCOLA ID_DEPENDENCIA_ADM_ESC


rename (ANO_CENSO PK_COD_MATRICULA FK_COD_ALUNO NU_DIA NU_MES ///
NU_ANO NUM_IDADE_REFERENCIA NUM_IDADE NU_DUR_ATIV_COMP_MESMA_REDE NU_DUR_ATIV_COMP_OUTRAS_REDES ///
TP_SEXO TP_COR_RACA TP_NACIONALIDADE FK_COD_PAIS_ORIGEM FK_COD_ESTADO_NASC FK_COD_MUNICIPIO_DNASC ///
FK_COD_ESTADO_END FK_COD_MUNICIPIO_END ID_ZONA_RESIDENCIAL ID_TIPO_ATENDIMENTO ID_N_T_E_P ///
ID_RESPONSAVEL_TRANSPORTE ID_TRANSP_VANS_KOMBI ID_TRANSP_MICRO_ONIBUS ID_TRANSP_ONIBUS ///
ID_TRANSP_BICICLETA ID_TRANSP_TR_ANIMAL ID_TRANSP_OUTRO_VEICULO ID_TRANSP_EMBAR_ATE5 ID_TRANSP_EMBAR_5A15 ID_TRANSP_EMBAR_15A35 ///
ID_TRANSP_EMBAR_35 ID_TRANSP_TREM_METRO ID_POSSUI_NEC_ESPECIAL ID_TIPO_NEC_ESP_CEGUEIRA ID_TIPO_NEC_ESP_BAIXA_VISAO ///
ID_TIPO_NEC_ESP_SURDEZ ID_TIPO_NEC_ESP_DEF_AUDITIVA ID_TIPO_NEC_ESP_SURDO_CEGUEIRA ID_TIPO_NEC_ESP_DEF_FISICA ///
ID_TIPO_NEC_ESP_DEF_MENTAL ID_TIPO_NEC_ESP_DEF_MULTIPLAS ID_TIPO_NEC_ESP_AUTISMO ID_TIPO_NEC_ESP_ASPERGER ID_TIPO_NEC_ESP_RETT ///
ID_TIPO_NEC_ESP_TDI ID_TIPO_NEC_ESP_SUPERDOTACAO ID_TIPO_REC_ESP_LEDOR ID_TIPO_REC_ESP_TRANSCRICAO ///
ID_TIPO_REC_ESP_INTERPRETE ID_TIPO_REC_ESP_LIBRAS ID_TIPO_REC_ESP_LABIAL ID_TIPO_REC_ESP_BRAILLE ///
ID_TIPO_REC_ESP_AMPLIADA_16 ID_TIPO_REC_ESP_AMPLIADA_20 ID_TIPO_REC_ESP_AMPLIADA_24 ID_TIPO_REC_ESP_NENHUM ///
ID_INGRESSO_FEDERAIS FK_COD_ETAPA_ENSINO PK_COD_TURMA FK_COD_CURSO_PROF ///
COD_UNIFICADA FK_COD_TIPO_TURMA PK_COD_ENTIDADE COD_MUNICIPIO_ESCOLA FK_COD_ESTADO_ESCOLA ID_DEPENDENCIA_ADM_ESC) (ano id_matricula id_pessoa_fisica dia_nascimento ///
mes_nascimento ano_nascimento idade_referencia idade ///
duracao_ativ_comp_mesma_rede duracao_ativ_comp_outras_redes ///
sexo cor_raca nacionalidade id_pais_origem ///
id_uf_nascimento id_municipio_nascimento id_uf_endereco ///
id_municipio_endereco zona_residencial outro_local_aula ///
transporte_publico responsavel_transporte ///
transporte_vans_kombi transporte_micro_onibus ///
transporte_onibus transporte_bicicleta ///
transporte_tr_animal transporte_outro_veiculo ///
transporte_embarcacao_ate5 transporte_embarcacao_5a15 ///
transporte_embarcacao_15a35 transporte_embarcacao_35 ///
transporte_trem_metro necessidade_especial cegueira ///
baixa_visao surdez deficiencia_auditiva surdocegueira ///
deficiencia_fisica deficiencia_intelectual ///
deficiencia_multipla autismo sindrome_asperger ///
sindrome_rett transtorno_di superdotacao recurso_ledor /// 
recurso_transcricao recurso_interprete recurso_libras ///
recurso_labial recurso_braille recurso_ampliada_16 ///
recurso_ampliada_20 recurso_ampliada_24 recurso_nenhum ///
ingresso_federais etapa_ensino id_turma ///
id_curso_educ_profissional unificada tipo_turma ///
id_escola id_municipio id_uf rede)

tostring id_uf, replace
gen sigla_uf = "AL" if id_uf == "27"
replace sigla_uf = "BA" if id_uf == "29"
replace sigla_uf = "CE" if id_uf == "23"
replace sigla_uf = "MA" if id_uf == "21"
replace sigla_uf = "PB" if id_uf == "25"
replace sigla_uf = "PE" if id_uf == "26"
replace sigla_uf = "PI" if id_uf == "22"
replace sigla_uf = "RN" if id_uf == "24"
replace sigla_uf = "SE" if id_uf == "28"

tostring rede, replace
replace rede = "federal" if rede == "1"
replace rede = "estadual" if rede == "2" 
replace rede = "municipal" if rede == "3"
replace rede = "privada" if rede == "4"

order id_matricula id_pessoa_fisica dia_nascimento mes_nascimento ano_nascimento idade_referencia idade duracao_ativ_comp_mesma_rede duracao_ativ_comp_outras_redes sexo cor_raca nacionalidade id_pais_origem id_uf_nascimento id_municipio_nascimento id_uf_endereco id_municipio_endereco zona_residencial outro_local_aula transporte_publico responsavel_transporte transporte_vans_kombi transporte_micro_onibus transporte_onibus transporte_bicicleta transporte_tr_animal transporte_outro_veiculo transporte_embarcacao_ate5 transporte_embarcacao_5a15 transporte_embarcacao_15a35 transporte_embarcacao_35 transporte_trem_metro necessidade_especial cegueira baixa_visao surdez deficiencia_auditiva surdocegueira deficiencia_fisica deficiencia_intelectual deficiencia_multipla autismo sindrome_asperger sindrome_rett transtorno_di superdotacao recurso_ledor recurso_transcricao recurso_interprete recurso_libras recurso_labial recurso_braille recurso_ampliada_16 recurso_ampliada_20 recurso_ampliada_24 recurso_nenhum ingresso_federais etapa_ensino id_turma id_curso_educ_profissional unificada tipo_turma id_escola id_municipio rede


foreach estado in AL BA CE MA PB PE PI RN SE {
	preserve
keep if sigla_uf == "`estado'"
drop ano sigla_uf id_uf
export delimited "C:/Users/Matheus/Desktop/particionadastata/ano=`t'/sigla_uf=`estado'/microdados_`estado'.csv" , replace
	restore
	
	}
}








