# Igual ao dataset.name mas como lower case.
# Exemplos: br_ibge_populacao, br_inep_censo_escolar
dataset_id: br_mec_prouni

table_id: microdados

# Título da tabela.
title: Programa Universidade para Todos (ProUni)

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description: Detalhamento das bolsas concedidas pelo Prouni por ano, contendo a região; UF; município; instituição de educação superior; curso; modalidade de ensino (presencial ou EAD); turno e tipo de bolsa. Detalhamento do perfil dos beneficiários do Prouni por sexo; raça/cor; data de nascimento e pessoas com deficiência.

# As máximas unidades espaciais que a tabela cobre.
# Exemplo:
#   - sa.br
spatial_coverage:
    - sa.br

# Anos cobertos pela tabela.
# Preencher como lista de intervalos.
# Exemplos: ['1995(1)2019'], ['2002(2)2010', '2016', '2020'].
temporal_coverage:
    - 2005(1)2019

# A unidade temporal com qual a tabela é atualizada.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
update_frequency: one_year

# Nível de observação da tabela: o que representa cada linha.
observation_level: 
    - entity: year
      columns:
      - ano
    - country: br
      entity: state
      columns:
      - sigla_uf
    - entity: municipality
      columns:
      - id_municipio
      - id_municipio_ies
    - entity: person
      columns:
      - cpf
    - entity: sex
      columns:
      - sexo
    - entity: race
      columns:
      - raca_cor
    - entity: date
      columns:
      - data_nascimento
    - entity: school
      columns:
      - id_ies
    - entity: other
      columns:
      - beneficiario_deficiente
      - campus
      - curso
      - turno
      - tipo_bolsa
      - modalidade_ensino

last_updated:
    metadata: '2022-09-04'
    data: '2022-09-04 20:30:15'
    release: '2022-09-04 20:30:16'

# Versão da tabela. Seguindo o padrão de semantic versioning.
# Exemplo: v1.1.3
version: v1.0

# Quem está preenchendo esses metadados?
published_by:
    name: Lucas Moreira
    email: lucas.moreira@basedosdados.org
    github_user: 
    ckan_user:
    website:

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
    name: Lucas Passos Barreto
    email: lucaspassosbarreto@hotmail.com
    github_user: oterrab
    ckan_user:
    website:

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: Criação do dicionário para variáveis categóricas, padronização das variáveis segundo as diretrizes da BD, substituição do nome por id_municipio e decodificação das strings

# Url do código de limpeza dos dados.
data_cleaning_code_url: https://github.com/basedosdados/mais/tree/master/bases/br_mec_prouni/code/microdados

# Organização que ajudou institucionalmente na disponibilização dos dados.
partner_organization:
    name:
    organization_id:

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions:
    - ano
    - sigla_uf

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Algumas colunas existirão apenas na tabela final, você as construirá em `publish.sql`.
# Para esses, defina is_in_staging como False.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: ano
      bigquery_type: int64
      description: Ano de início da concessão da bolsa
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: ano
          column_name: ano
      measurement_unit: year
      has_sensitive_data: no
      observations: Início da vigência
      is_in_staging: true
      is_partition: true
    - name: sigla_uf
      bigquery_type: string
      description: Sigla da Unidade da Federação do beneficiário da bolsa
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: uf
          column_name: sigla
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: true
    - name: id_municipio
      bigquery_type: string
      description: ID Município do beneficiário - IBGE 7 Dígitos
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: municipio
          column_name: id_municipio
      measurement_unit:
      has_sensitive_data: no
      observations: Transformado para id do municipio
      is_in_staging: true
      is_partition: false
    - name: cpf
      bigquery_type: string
      description: CPF do beneficiário da bolsa
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: yes
      observations: CPF anônimo no formato fornecido pelo MEC
      is_in_staging: true
      is_partition: false
    - name: sexo
      bigquery_type: string
      description: Sexo informado pelo beneficiário da bolsa
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: raca_cor
      bigquery_type: string
      description: Raça/Cor informado pelo beneficiário da bolsa
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: data_nascimento
      bigquery_type: date
      description: Data de nascimento do beneficiário da bolsa
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: data
          column_name: data
      measurement_unit:
      has_sensitive_data: yes
      observations: Transformado para o formato 'YYYY-MM-DD'
      is_in_staging: true
      is_partition: false
    - name: beneficiario_deficiente
      bigquery_type: int64
      description: Indicação se o beneficiário da bolsa é portador de algum tipo de
          deficiência
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: id_ies
      bigquery_type: string
      description: Número de identificação da IES
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: instituicao_ensino_superior
          column_name: id_ies
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: campus
      bigquery_type: string
      description: Campus IES
      temporal_coverage:
          - 2020(1)
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: nome_municipio_ies
      bigquery_type: string
      description: Nome do Município da IES
      temporal_coverage:
          - 2020(1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: municipio
          column_name: nome
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: curso
      bigquery_type: string
      description: Nome do curso do beneficiário da bolsa
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: curso_superior
          column_name: curso_superior
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: turno_curso
      bigquery_type: string
      description: Turno do curso do beneficiário da bolsa
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: tipo_bolsa
      bigquery_type: string
      description: Tipo da bolsa concedida ao beneficiário
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: modalidade_ensino
      bigquery_type: string
      description: Modalidade de ensino da bolsa concedida ao beneficiário
      temporal_coverage:
          - (1)
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false

number_rows: 2903378

metadata_modified:
