
dataset_id: mundo_bm_learning_poverty

table_id: pais

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description: Learning Poverty é um indicador do Banco Mundial que traduz a incapacidade de uma criança de 10 anos ler e compreender um texto simples. Este indicador reúne dados de escolaridade e aprendizagem entre as crianças que não alcançaram a proficiência mínima de leitura (medida nas escolas) e é ajustado pela proporção de crianças que estão fora da escola (e se presume que não sabem ler com proficiência).

# A máxima unidade espacial que a tabela cobre.
spatial_coverage: all

# Anos cobertos pela tabela.
# Preencher como lista de intervalos.
# Exemplo: 1995(1)2019.
temporal_coverage:
    - 2001
    - 2003
    - 2006
    - 2007
    - 2011
    - 2012
    - 2013
    - 2014
    - 2015
    - 2016
    - 2017
    - 2018
    - 2019

# A unidade temporal com qual a tabela é atualizada.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
update_frequency: recurring

# Entidade representada por cada linha.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
entity: country

# A unidade temporal representada por cada linha.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
time_unit: uncertain

# O conjunto mínimo de colunas identificando cada linha unicamente.
# Preencha com os nomes de colunas.
# Exemplos: id_municipio, ano.
# Pode ser vazio pois certas tabelas não possuem identificadores.
identifying_columns:
    - year
    - country_code

last_updated:
    metadata:
    data:
    release:

# Versão da tabela. Seguindo o padrão de semantic versioning.
# Exemplo: v1.1.3
version: v1.0

# Quem está preenchendo esses metadados?
published_by:
    name: Gustavo Aires
    email: gustavo.tiago@basedosdados.org
    github_user: gustavoairestiago
    website: https://github.com/gustavoairestiago
    ckan_user:

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
    name: Gustavo Aires
    email: gustavo.tiago@basedosdados.org
    github_user: gustavoairestiago
    ckan_user:
    website: https://github.com/gustavoairestiago
    code_url: https://github.com/basedosdados/mais/tree/master/bases/mundo_bm_learning_poverty/code

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: "Download dos dados \n
    Renomeação das colunas \n"

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

# A tabela tem colunas que precisam de dicionário?
# Opções: yes, no.
covered_by_dictionary: no

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions:

bdm_file_size:

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Algumas colunas existirão apenas na tabela final, você as construirá em `publish.sql`.
# Para esses, defina is_in_staging como False.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: year
      bigquery_type: int64
      description: Ano
      temporal_coverage:
      covered_by_dictionary: 
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: ano
          column_name: ano
      measurement_unit: year
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: country_code
      bigquery_type: string
      description: Sigla País - ISO3
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id: br_bd_diretorios_mundo
          table_id: pais
          column_name: sigla_pais_iso3
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: region_name
      bigquery_type: string
      description: Região mundial
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false 
    - name: children_reading_proficiency
      bigquery_type: float64
      description: Proporção de crianças na idade de fim do ensino fundamental abaixo da proficiência mínima em leitura ajustada por crianças fora da escola (%)
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false 
    - name: female_children_reading_proficiency
      bigquery_type: float64
      description: Proporção de meninas na idade de fim do ensino fundamental abaixo da proficiência mínima em leitura ajustada por crianças fora da escola (%)
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: male_children_reading_proficiency
      bigquery_type: float64
      description: proporção de meninos na idade de fim do ensino fundamental abaixo da proficiência mínima em leitura ajustada por crianças fora da escola (%)
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: children_out_of_school
      bigquery_type: float64
      description: Crianças em idade escolar fora da escola (%)
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: female_children_out_of_school
      bigquery_type: float64
      description: Crianças do sexo feminino em idade escolar fora da escola (%)
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: male_children_out_of_school
      bigquery_type: float64
      description: Crianças do sexo masculino em idade escolar fora da escola (%)
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: pupil_reading_proficiency_gaml
      bigquery_type: float64
      description: Alunos abaixo da proficiência mínima de leitura no final do primário (%)
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: female_pupil_reading_proficiency_gaml
      bigquery_type: float64
      description: Alunas abaixo da proficiência mínima de leitura no final do primário (%)
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no 
      is_in_staging: true
      is_partition: false
    - name: male_pupil_reading_proficiency_gaml
      bigquery_type: float64
      description: Alunos do sexo masculino abaixo da proficiência mínima de leitura no final do primário (%)
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no 
      is_in_staging: true
      is_partition: false

metadata_modified:
