
# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: br-inep-indicadores-educacionais

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Indicadores Educacionais

# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Exemplos: br-ibge, br-tse, br-rj-gov
organization:
    - br-inep

# Descrição do conjunto
notes: Os indicadores educacionais atribuem valor estatístico à qualidade do ensino,
    atendo-se não somente ao desempenho dos alunos mas também ao contexto econômico
    e social em que as escolas estão inseridas. Eles são úteis principalmente para
    o monitoramento dos sistemas educacionais, considerando o acesso, a permanência
    e a aprendizagem de todos os alunos. Dessa forma, contribuem para a criação de
    políticas públicas voltadas para a melhoria da qualidade da educação e dos serviços
    oferecidos à sociedade pela escola.

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
    - educacao

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos: fertilidade, preco, desmatamento.
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
    - creche
    - educacao basica
    - educacao superior
    - ensino medio

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified: '2022-02-14T01:25:00.333671'
