
dataset_id: br_ons_energia_armazenada

table_id: subsistemas

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description:
    Dados das grandezas de energia armazenada em periodicidade diária por subsistemas.

# A máxima unidade espacial que a tabela cobre.
spatial_coverage:

# Anos cobertos pela tabela.
temporal_coverage:
    - 2000
    - 2001
    - 2002
    - 2003
    - 2004
    - 2005
    - 2006
    - 2007
    - 2008
    - 2009
    - 2010
    - 2011
    - 2012
    - 2013
    - 2014
    - 2015
    - 2016
    - 2017
    - 2018
    - 2019
    - 2020
    - 2021
# A unidade temporal com qual a tabela é atualizada.
update_frequency: day

# Entidade representada por cada linha.
entity:

# A unidade temporal representada por cada linha.
time_unit:

# O conjunto mínimo de colunas identificando cada linha unicamente.
# Preencha com os nomes de colunas. Ex: id_municipio, ano.
# Pode ser vazio pois certas tabelas não possuem identificadores.
identifying_columns:
    - data
    - subsistema

last_updated:
    metadata:
    data:
    release:

version: v1.1

# Quem está preenchendo esses metadados?
published_by:
    name: Crislane Alves
    email: crislanealves@basedosdados.org
    github_user: crislanealves
    website:
    ckan_user: crislanealves

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
    name: Bruno Mioto 
    email: brunomioto97@gmail.com
    github_user: brunomioto
    ckan_user:
    website: brunomioto.com.br
    code_url: https://github.com/brunomioto/reservatoriosBR

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: "Limpeza para consistência" 
# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

covered_by_dictionary: no

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions:

bdm_file_size:

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Algumas colunas existirão apenas na tabela final, você as construirá em `publish.sql`.
# Para esses, defina is_in_staging como False.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: data
      bigquery_type: date
      description: Data
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: data
          column_name: data
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: no
    - name: subsistema
      bigquery_type: string
      description: Nome do subsistema
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: no
    - name: energia_armazenada_maxima
      bigquery_type: float64
      description: Valor de energia armazenada máxima por subsistema
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: no
    - name: energia_armazenada_verificada
      bigquery_type: float64
      description: Valor de energia armazenada verificada no dia por subsistema
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: no
    - name: proporcao_energia_armazenada_verificada
      bigquery_type: float64
      description: Porcentagem de energia armazenada verificada no dia por subsistema
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: no

metadata_modified:
