name: Python package

on:
  push:
    paths:
      - bases/**.yaml

jobs:
  get-changes:
    runs-on: ubuntu-latest
    steps:

      - name: Create Changes
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4

      - name: Copy Changes
        run: cp $HOME/files.json files.json

      - name: Upload Changes
        uses: actions/upload-artifact@v2
        with:
          name: push-changes
          path: files.json

  check-data:
    runs-on: ubuntu-latest
    env:
      DEV_PROD: ${{ secrets.GCP_BD_DEV_PROD }}
      DEV_STAG: ${{ secrets.GCP_BD_DEV_STAGING }}
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Data Check
      uses: ./.github/workflows/check_data/