name: data-check

on:
  pull_request:
    types:
      - labeled
jobs:
  get_changes:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'data-check-trigger'
    steps:
      - name: Create Changes
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4
      - name: Copy Changes
        run: cp $HOME/files.json files.json
      - name: Upload Changes
        uses: actions/upload-artifact@v2
        with:
          name: push-changes
          path: files.json

  data-check:
    needs: get_changes
    runs-on: ubuntu-latest
    env:
      GCP_BD_DEV_PROD: ${{ secrets.GCP_BD_DEV_PROD }}
      GCP_BD_DEV_STAGING: ${{ secrets.GCP_BD_DEV_STAGING }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download changes
        uses: actions/download-artifact@v2
        with:
          name: push-changes
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
      - name: Initialize report
        run: echo -e "Data Check Report\n---\n\n" > report.md
      - name: Test data and fill report
        uses: ./.github/workflows/data-check/
      - name: Finalize report
        if: ${{ always() }}
        id: get-comment-body
        run: |
          body=$(cat report.md)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo ::set-output name=body::$body
      - name: Create comment
        if: ${{ always() && github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.get-comment-body.outputs.body }}

