name: etl-caged

on:
  push:
    branches:
      - "feat/br_me_caged"

jobs:
  get-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check file changes
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4
      - name: Copy file changes
        run: cp $HOME/files.json files.json
      - name: Upload file changes
        uses: actions/upload-artifact@v2
        with:
          name: push-changes
          path: files.json

  etl-caged:
    needs: get-changes
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Download changes
        uses: actions/download-artifact@v2
        with:
          name: push-changes
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install basedosdados toml
      - name: Install etl dependencies
        run: |          
          cd bases/br_me_caged/code/caged_novo/
          pip install -r requirements_caged_novo.txt   
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_MAIN_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY_TASK_CALLER }}
          export_default_credentials: true
      - name: Set up base dos dados environment
        run: python .github/workflows/env-setup/env_setup.py
        shell: bash
        env:
          BUCKET_NAME: basedosdados
          PROJECT_NAME_PROD: basedosdados
          PROJECT_NAME_STAGING: basedosdados-staging
          GCP_BD_PROD: ${{ secrets.GCP_BD_DEV_PROD }}
          GCP_BD_STAGING: ${{ secrets.GCP_BD_DEV_STAGING }}
          CKAN_URL: "https://staging.basedosdados.org"
          CKAN_API_KEY: ${{ secrets.CKAN_STAGING }}
      - name: Run ETL-CAGED
        run: python bases/br_me_caged/code/caged_novo/caged_novo.py
        shell: bash