name: python-ci

on:
  push:
    paths:
      - python-package/**
      - .github/workflows/setup-env*
      - .github/workflows/python-ci.yml

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'
    - name: Install dependencies
      run: |
        cd python-package
        pip install -r requirements-dev.txt
        pip install coveralls
      shell: bash
    - name: Install package
      run: |
        cd python-package
        python setup.py develop
      shell: bash
    - name: Set up base dos dados environment
      run: python .github/workflows/env-setup/env_setup.py
      env:
        BUCKET_NAME: basedosdados-dev
        PROJECT_NAME_PROD: basedosdados-dev
        PROJECT_NAME_STAGING: basedosdados-dev
        GCP_BD_PROD: ${{ secrets.GCP_BD_DEV_PROD }}
        GCP_BD_STAGING: ${{ secrets.GCP_BD_DEV_STAGING }}
      shell: bash
    - name: Test and assess coverage
      run: |
        cd python-package
        coverage run --source=basedosdados -m pytest tests
        coveralls --service=github
      shell: bash
      env:
        COVERALLS_FLAG_NAME: linux
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'
    - name: Install dependencies
      run: |
        cd python-package
        pip install -r requirements-dev.txt
        pip install coveralls
      shell: cmd
    - name: Install package
      run: |
        cd python-package
        python setup.py develop
      shell: cmd
    - name: Set up base dos dados environment
      run: python .github\workflows\env-setup\env_setup.py
      shell: cmd
      env:
        BUCKET_NAME: basedosdados-dev
        PROJECT_NAME_PROD: basedosdados-dev
        PROJECT_NAME_STAGING: basedosdados-dev
        GCP_BD_PROD: ${{ secrets.GCP_BD_DEV_PROD }}
        GCP_BD_STAGING: ${{ secrets.GCP_BD_DEV_STAGING }}
    - name: Test and assess coverage
      run: |
        cd python-package
        coverage run --source=basedosdados -m pytest tests
        coveralls --service=github
      shell: cmd
      env:
        COVERALLS_FLAG_NAME: windows
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
