name: update-check

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-check:
    runs-on: ubuntu-latest
    env:
      SPREADSHEET_ID: "1vcrf2JGiJfu5_NuiB358mkHZh1sPSyeXOLVHKQMFSMc"
      RANGE_NAME: "OutdatedDatasets!A1:Z1000"
      GDOCS_SERVICE_ACCOUNT: ${{ secrets.GDOCS_SERVICE_ACCOUNT }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel arrow pyyaml google-auth google-api-python-client
      - name: Search for outdated datasets
        run: |
          cd .github/workflows/update-check
          python update_check.py
        shell: bash
      - name: Send report to gsheets
        run: |
          cd .github/workflows/update-check
          python to_sheets.py
        shell: bash
