# Nome (slug) do conjunto no CKAN
# Exemplos: br-ibge-populacao, br-tse-eleicoes
name: br-me-pensionistas

# Título do conjunto, a ser exibido no mecanismo de busca.
# Exemplo: População brasileira
title: Gestão de Pessoas (Executivo Federal) - Pensionistas

# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list
# Exemplos: br-ibge, br-tse, br-rj-gov
organization:
    - br-me

# Descrição do conjunto
notes: "As informações disponibilizadas referem-se ao pagamento (rendimento bruto)\
    \ recebido por pensionistas de servidores instituidores de pensão, constantes\
    \ no Sistema Integrado de Administração de Pessoal (Siape).\r\n\r\nCabe ressaltar\
    \ que o Ministério da Economia é responsável pelas informações dos servidores\
    \ instituidores de pensão e pensionistas do Poder Executivo Federal, não incluindo\
    \ dados dos poderes Judiciário e Legislativo. Também não constam nos arquivos,\
    \ dados relativos aos servidores do Banco Central do Brasil (1), Ministério da\
    \ Defesa (2) (com exceção de militares de ex-territórios ou que assumiram cargos\
    \ civis no Poder Executivo Federal) e Governo do Distrito Federal (3) (Fundo Constitucional),\
    \ responsáveis pela publicação dos seus dados em portais próprios.\r\n\r\nEm relação\
    \ à Agência Brasileira de Inteligência (Abin), os dados funcionais de pessoal\
    \ são protegidos pela legislação vigente Lei nº 9883 (4) e Portaria Conjunta n°\
    \ 5, de 05/08/2015/MPOG (5).\r\n\r\nDestacamos que todas as pensões acima do teto\
    \ do funcionalismo público estão sujeitas ao abate-teto. Aos pensionistas com\
    \ mais de um benefício, aplica-se o abate-teto em cima da soma das pensões, considerando\
    \ os valores proporcionais a cada uma.\r\n\r\n### Conceito\r\n\r\nBeneficiário\
    \ de pensão ou pensionista: Dependente do servidor titular de cargo efetivo da\
    \ União ou do aposentado que faleceu; dependente de anistiado político ou pessoa\
    \ que receba pensão especial graciosa ou indenizatória, concedida por meio de\
    \ Lei ou Decreto Presidencial; ou beneficiados dessas condições por decisão judicial,\
    \ a quem tenha sido concedido o benefício da pensão.\r\n\r\n### Política Pública\r\
    \n\r\nPolítica de aperfeiçoamento contínuo dos processos de gestão de pessoas\
    \ no âmbito da administração pública federal, no que se refere ao aspecto de aprimorar\
    \ a cultura de transparência pública de forma a franquear a todos o acesso de\
    \ forma aberta, aos dados produzidos ou acumulados pelo Poder Executivo federal,\
    \ sobre os quais não recaia vedação expressa de acesso.\r\n\r\n### Legislação\r\
    \n\r\nLei nº 8112 de 11 de dezembro de 1990, Lei nº 13.135, de 17 de junho de\
    \ 2015."

# Quais temas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
# Importante: preencher com a chave, e não o valor.
groups:
    - gov-fin-pub

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Exemplos: fertilidade, preco, desmatamento.
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:
    - pensao
    - servico militar

# Não altere esse campo.
# Data da última modificação dos metadados gerada automaticamente pelo CKAN.
metadata_modified: '2022-02-14T01:25:04.248378'
