/*

Query para publicar a tabela.

Esse é o lugar para:
    - modificar nomes, ordem e tipos de colunas
    - dar join com outras tabelas
    - criar colunas extras (e.g. logs, proporções, etc.)

Qualquer coluna definida aqui deve também existir em `table_config.yaml`.

# Além disso, sinta-se à vontade para alterar alguns nomes obscuros
# para algo um pouco mais explícito.

TIPOS:
    - Para modificar tipos de colunas, basta substituir STRING por outro tipo válido.
    - Exemplo: `SAFE_CAST(column_name AS NUMERIC) column_name`
    - Mais detalhes: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types

*/

CREATE VIEW basedosdados-dev.br_ms_sinan.microdados AS
SELECT 
SAFE_CAST(data_notificacao AS DATE) data_notificacao,
SAFE_CAST(id_categoria_cid10 AS STRING) id_categoria_cid10,
SAFE_CAST(id_subcategoria_cid10 AS STRING) id_subcategoria_cid10,
SAFE_CAST(tipo_notificacao AS INT64) tipo_notificacao,
SAFE_CAST(id_uf_notificacao AS STRING) id_uf_notificacao,
SAFE_CAST(id_municipio_notificacao AS STRING) id_municipio_notificacao,
SAFE_CAST(id_municipio_6_notificacao AS STRING) id_municipio_6_notificacao,
SAFE_CAST(id_unidade_notificacao AS STRING) id_unidade_notificacao,
SAFE_CAST(id_regional_saude_notificacao AS STRING) id_regional_saude_notificacao,
SAFE_CAST(data_ocorrencia AS DATE) data_ocorrencia,
SAFE_CAST(id_uf_ocorrencia AS STRING) id_uf_ocorrencia,
SAFE_CAST(id_municipio_ocorrencia AS STRING) id_municipio_ocorrencia,
SAFE_CAST(id_municipio_6_ocorrencia AS STRING) id_municipio_6_ocorrencia,
SAFE_CAST(hora_ocorrencia AS TIME) hora_ocorrencia,
SAFE_CAST(local_ocorrencia AS INT64) local_ocorrencia,
SAFE_CAST(outro_local_ocorrencia AS STRING) outro_local_ocorrencia,
SAFE_CAST(outras_vezes_ocorrencia AS INT64) outras_vezes_ocorrencia,
SAFE_CAST(id_uf_residencia AS STRING) id_uf_residencia,
SAFE_CAST(id_municipio_6_residencia AS STRING) id_municipio_6_residencia,
SAFE_CAST(id_municipio_residencia AS STRING) id_municipio_residencia,
SAFE_CAST(id_regional_saude_residencia AS STRING) id_regional_saude_residencia,
SAFE_CAST(idade_paciente AS INT64) idade_paciente,
SAFE_CAST(sexo_paciente AS INT64) sexo_paciente,
SAFE_CAST(gestante_paciente AS INT64) gestante_paciente,
SAFE_CAST(raca_paciente AS INT64) raca_paciente,
SAFE_CAST(escolaridade_paciente AS INT64) escolaridade_paciente,
SAFE_CAST(ocupacao_paciente AS STRING) ocupacao_paciente,
SAFE_CAST(situacao_conjugal_paciente AS INT64) situacao_conjugal_paciente,
SAFE_CAST(orientacao_sexual_paciente AS INT64) orientacao_sexual_paciente,
SAFE_CAST(identidade_genero_paciente AS INT64) identidade_genero_paciente,
SAFE_CAST(motivacao_violencia AS INT64) motivacao_violencia,
SAFE_CAST(violencia_relacionada_trabalho AS INT64) violencia_relacionada_trabalho,
SAFE_CAST(emitiu_cat AS INT64) emitiu_cat,
SAFE_CAST(deficiencia_transtorno_paciente AS INT64) deficiencia_transtorno_paciente,
SAFE_CAST(deficiencia_fisica_paciente AS INT64) deficiencia_fisica_paciente,
SAFE_CAST(deficiencia_mental_paciente AS INT64) deficiencia_mental_paciente,
SAFE_CAST(deficiencia_visual_paciente AS INT64) deficiencia_visual_paciente,
SAFE_CAST(deficiencia_auditiva_paciente AS INT64) deficiencia_auditiva_paciente,
SAFE_CAST(transtorno_mental_paciente AS INT64) transtorno_mental_paciente,
SAFE_CAST(transtorno_comportamental_paciente AS INT64) transtorno_comportamental_paciente,
SAFE_CAST(outras_deficiencias_paciente AS INT64) outras_deficiencias_paciente,
SAFE_CAST(quais_outras_deficiencias_paciente AS STRING) quais_outras_deficiencias_paciente,
SAFE_CAST(lesao_autoprovocada AS INT64) lesao_autoprovocada,
SAFE_CAST(ocorreu_violencia_fisica AS INT64) ocorreu_violencia_fisica,
SAFE_CAST(ocorreu_violencia_psicologica AS INT64) ocorreu_violencia_psicologica,
SAFE_CAST(ocorreu_tortura AS INT64) ocorreu_tortura,
SAFE_CAST(ocorreu_violencia_sexual AS INT64) ocorreu_violencia_sexual,
SAFE_CAST(ocorreu_trafico_ser_humano AS INT64) ocorreu_trafico_ser_humano,
SAFE_CAST(ocorreu_violencia_financeira AS INT64) ocorreu_violencia_financeira,
SAFE_CAST(ocorreu_negligencia_abandono AS INT64) ocorreu_negligencia_abandono,
SAFE_CAST(ocorreu_trabalho_infantil AS INT64) ocorreu_trabalho_infantil,
SAFE_CAST(ocorreu_intervencao_legal AS INT64) ocorreu_intervencao_legal,
SAFE_CAST(ocorreu_outra_violencia AS INT64) ocorreu_outra_violencia,
SAFE_CAST(ocorreu_qual_outra AS STRING) ocorreu_qual_outra,
SAFE_CAST(meio_forca AS INT64) meio_forca,
SAFE_CAST(meio_enforcamento AS INT64) meio_enforcamento,
SAFE_CAST(meio_objeto_contundente AS INT64) meio_objeto_contundente,
SAFE_CAST(meio_objeto_perfurante AS INT64) meio_objeto_perfurante,
SAFE_CAST(meio_objeto_quente AS INT64) meio_objeto_quente,
SAFE_CAST(meio_envenenamento AS INT64) meio_envenenamento,
SAFE_CAST(meio_arma_fogo AS INT64) meio_arma_fogo,
SAFE_CAST(meio_ameaca AS INT64) meio_ameaca,
SAFE_CAST(meio_outros AS INT64) meio_outros,
SAFE_CAST(meio_qual_outro AS STRING) meio_qual_outro,
SAFE_CAST(houve_assedio AS INT64) houve_assedio,
SAFE_CAST(houve_estupro AS INT64) houve_estupro,
SAFE_CAST(houve_pornografia_infantil AS INT64) houve_pornografia_infantil,
SAFE_CAST(houve_exploracao_sexual AS INT64) houve_exploracao_sexual,
SAFE_CAST(houve_outra_violencia_sexual AS INT64) houve_outra_violencia_sexual,
SAFE_CAST(houve_qual_outra_violencia_sexual AS STRING) houve_qual_outra_violencia_sexual,
SAFE_CAST(profilaxia_dst AS INT64) profilaxia_dst,
SAFE_CAST(profilaxia_hiv AS INT64) profilaxia_hiv,
SAFE_CAST(profilaxia_hepatite_b AS INT64) profilaxia_hepatite_b,
SAFE_CAST(coleta_sangue AS INT64) coleta_sangue,
SAFE_CAST(coleta_semen AS INT64) coleta_semen,
SAFE_CAST(coleta_secrecao_vaginal AS INT64) coleta_secrecao_vaginal,
SAFE_CAST(profilaxia_contraceptivo AS INT64) profilaxia_contraceptivo,
SAFE_CAST(aborto AS INT64) aborto,
SAFE_CAST(numero_envolvidos_violencia AS INT64) numero_envolvidos_violencia,
SAFE_CAST(autor_pai AS INT64) autor_pai,
SAFE_CAST(autor_mae AS INT64) autor_mae,
SAFE_CAST(autor_padrasto AS INT64) autor_padrasto,
SAFE_CAST(autor_madrasta AS INT64) autor_madrasta,
SAFE_CAST(autor_conjugue AS INT64) autor_conjugue,
SAFE_CAST(autor_ex_conjugue AS INT64) autor_ex_conjugue,
SAFE_CAST(autor_namorado_a AS INT64) autor_namorado_a,
SAFE_CAST(autor_ex_namorado_a AS INT64) autor_ex_namorado_a,
SAFE_CAST(autor_filho_a AS INT64) autor_filho_a,
SAFE_CAST(autor_desconhecido AS INT64) autor_desconhecido,
SAFE_CAST(autor_irmao AS INT64) autor_irmao,
SAFE_CAST(autor_conhecido AS INT64) autor_conhecido,
SAFE_CAST(autor_cuidador AS INT64) autor_cuidador,
SAFE_CAST(autor_patrao_chefe AS INT64) autor_patrao_chefe,
SAFE_CAST(autor_institucional AS INT64) autor_institucional,
SAFE_CAST(autor_policial AS INT64) autor_policial,
SAFE_CAST(autor_propria_pessoa AS INT64) autor_propria_pessoa,
SAFE_CAST(autor_outros AS INT64) autor_outros,
SAFE_CAST(autor_relacao_outros AS STRING) autor_relacao_outros,
SAFE_CAST(autor_sexo AS INT64) autor_sexo,
SAFE_CAST(autor_usou_alcool AS INT64) autor_usou_alcool,
SAFE_CAST(encaminhamento_saude AS INT64) encaminhamento_saude,
SAFE_CAST(encaminhamento_assistencia_social AS INT64) encaminhamento_assistencia_social,
SAFE_CAST(encaminhamento_educacao AS INT64) encaminhamento_educacao,
SAFE_CAST(encaminhamento_atendimento_mulher AS INT64) encaminhamento_atendimento_mulher,
SAFE_CAST(encaminhamento_conselho_tutelar AS INT64) encaminhamento_conselho_tutelar,
SAFE_CAST(encaminhamento_conselho_idoso AS INT64) encaminhamento_conselho_idoso,
SAFE_CAST(encaminhamento_delegacia_idoso AS INT64) encaminhamento_delegacia_idoso,
SAFE_CAST(encaminhamento_direitos_humanos AS INT64) encaminhamento_direitos_humanos,
SAFE_CAST(encaminhamento_mpu AS INT64) encaminhamento_mpu,
SAFE_CAST(encaminhamento_delegacia_crianca AS INT64) encaminhamento_delegacia_crianca,
SAFE_CAST(encaminhamento_delegacia_mulher AS INT64) encaminhamento_delegacia_mulher,
SAFE_CAST(encaminhamento_delegacia AS INT64) encaminhamento_delegacia,
SAFE_CAST(encaminhamento_justica_infancia_juventude AS INT64) encaminhamento_justica_infancia_juventude,
SAFE_CAST(encaminhamento_defensoria_publica AS INT64) encaminhamento_defensoria_publica,
SAFE_CAST(data_encerramento AS DATE) data_encerramento,
SAFE_CAST(ano AS INT64) ano
from basedosdados-dev.br_ms_sinan_staging.microdados as t